Massgov 1160 upcoming event title
massgov/mayflower-patternlab pull request #244
Opened 2016-12-08 02:08 UTC by ygannett

Replace `<div>` with `<h3>` for upcoming event titles, and adjust the style to match the existing one in a location page.

## Affected page types
* [Location](http://localhost:3000/patterns/05-pages-LOC-Southbridge-RMV/05-pages-LOC-Southbridge-RMV.html)

## Current Code
```
<section class="ma__action-event">
  <div class="ma__action-event__name">
    <span class="ma__decorative-link">
      <a href="#" class="js-clickable-link">Fishing Clinic&nbsp;<svg focusable="false" role="presentation" class="svg-arrow"><use xlink:href="/assets/images/svg-sprite.svg#arrow"/></svg></a>
    </span>
  </div>
  <div class="ma__action-event__date">June 24, 2017, 12:00pm</div>
  <div class="ma__action-event__description">
    This is a description of the event that will happen at a future date
  </div>
</section>
```

## Changed to
```
<section class="ma__action-event">
  <h3 class="ma__action-event__name">
    <span class="ma__decorative-link">
      <a href="#" class="js-clickable-link">Fishing Clinic&nbsp;<svg focusable="false" role="presentation" class="svg-arrow"><use xlink:href="/assets/images/svg-sprite.svg#arrow"/></svg></a>
    </span>
  </h3>
  <div class="ma__action-event__date">June 24, 2017, 12:00pm</div>
  <div class="ma__action-event__description">
    This is a description of the event that will happen at a future date
  </div>
</section>
```

### Edited Files 
* source/_patterns/02-molecules/action-event.twig
* source/assets/scss/02-molecules/_action-event.scss

2016-12-08 15:01 UTC, gender404 requested changes

2016-12-08 15:01 UTC, gender404 commented on styleguide/source/assets/scss/02-molecules/_action-event.scss
> -
There should be a blank line between selectors even nested ones.

Also to get the styling back to being a div instead of the h3 styling, you just need to add the following to &__name {
font-size: inherit;
line-height: inherit;
margin-bottom: 0;

2016-12-08 15:01 UTC, gender404 commented on styleguide/source/assets/scss/02-molecules/_action-event.scss
> +  }
I don't understand why this is here.  It reads like the code that is on the contained a tag.  I don't think any of this is required.

2016-12-08 15:41 UTC, ygannett commented on styleguide/source/assets/scss/02-molecules/_action-event.scss
> -
I tried inherit first, but I didn't see the same style at my end.  I might have missed something.  Thank you for the correction.

2016-12-08 15:44 UTC, gender404 commented on styleguide/source/assets/scss/02-molecules/_action-event.scss
> -
I did that in the Chrome inspector tools so it's possible I missed something, but please try again.  If it doesn't work then I think we can copy the styles from the body tag for those two items instead.

2016-12-08 15:46 UTC, ygannett commented on styleguide/source/assets/scss/02-molecules/_action-event.scss
> +  }
It seems I accidentally grabbed the wrong styles from .ma__decorative-link a.  I'm sorry about the confusion.  The entire h3.ma__action-event__name has been removed and the change has been pushed.

2016-12-09 13:57 UTC, merged

2016-12-09 14:22 UTC, gender404 commented
I'm updating the PL dev environment now.  should be there in about 15 minutes