Mgrp 258 mayflower docs molecules
massgov/mayflower-patternlab pull request #246
Opened 2016-12-12 17:43 UTC by gleroux02

This is ready for review. It adds documentation to the molecule section of the styleguide.

2016-12-15 05:17 UTC, gleroux02 commented
I still need to update a few states and add notes to the ones that I do. Otherwise this is ready for review.

2016-12-20 16:20 UTC, gender404 requested changes

2016-12-20 16:20 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/action-seq-list.md
> +### Contains:
I think we need to figure out how we want to document something that includes a RTE element.  The implementation in PL will never match how a RTE is implemented in a CMS.  Maybe we should just state it includes an RTE and leave out the path and data object?

2016-12-20 16:20 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/contact-us.md
> +### Required Variables
Just a note, I'd like to refactor this a bit to remove the "hidden" variable.  Instead the twig file can split the groups array into to for loops first two and everything else.

2016-12-20 16:20 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/header-contact.md
> +
this is incorrect.  Should be Action Header.

2016-12-20 16:20 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/header-contact.md
> +
Should this be depreciated as well so we can replace the "address" section with a Contact Group now that address exists as an option within Contact Group?

2016-12-20 16:20 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/header-search.md
> +~~~
This is completely wrong.  I think this is the md for the Stats Callout not the header search

2016-12-20 16:20 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/illustrated-link.md
> +}
missing required fields

2016-12-20 16:20 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/location-icons.md
> +### Required Variables
Used in Action Header - one of the widgets that go in the right section

2016-12-20 16:20 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/section-links.md
> +      type: string/path to svg
this as been refactored in this sprint to be "icon" instead of "svg"

2016-12-20 19:44 UTC, gender404 commented
Found another items that needs to be changed.  All md file names with ~ in them need to be changed to - in order for them to work (at least on my PC based local).

2016-12-22 18:37 UTC, gender404 commented
@patrickfweston - Do you think you can complete these changes this week?  Or do you need some help with them?

2017-01-04 18:52 UTC, gleroux02 commented on styleguide/source/_patterns/02-molecules/action-seq-list.md
> +### Contains:
I agree that PL will never match how it is implemented in a CMS. However, there is work that needs to be done in order better accommodate both systems and something that can I hope we can resolve in https://jira.state.ma.us/browse/MGRP-287. I agree that we can state that it includes a RTE and then link off to that organism.  If and when 287 is worked and the RTE is updated there would also be less documentation to update.

2017-01-04 19:08 UTC, merged