296 Homepage
massgov/mayflower-patternlab pull request #248
Opened 2016-12-13 20:10 UTC by gender404

Tickets:
https://jira.state.ma.us/browse/MGRP-304
https://jira.state.ma.us/browse/MGRP-328
https://jira.state.ma.us/browse/MGRP-296

2016-12-15 22:33 UTC, gender404 commented
I think that is all the code needed.  I need to do some more testing before I'm comfortable removing the WIP label, but feel free to review what's there.

2016-12-21 14:38 UTC, patrickfweston commented on styleguide/source/_patterns/02-molecules/footer-links.twig
> +  {% for item in footerLinks.items %}
Having things in Twig loops, etc. will be really helpful when working with Drupal or another CMS. This is great!

2016-12-21 14:56 UTC, patrickfweston commented
@legostud : I'm still getting acclimated to the project (and am waiting on JIRA access), but the changes to the atoms look like a definite step in the right direction. Feel free to reach out when you have this ready for review.

2016-12-21 15:02 UTC, gender404 commented
You can assume a PR is ready for review if it is missing the WIP label.  I saw the ticket for the footer links this morning and realized that I missed that part of the homepage comp so I tried to sneak it in.

2017-01-03 00:06 UTC, gleroux02 commented on styleguide/source/_patterns/03-organisms/by-author/search-banner.twig
> +    <form class="ma__search-banner__form" action="{{searchBanner.action}}">
The form should be rendered differently so that it is easier to implement within a system. I'm stuck on how this should be implemented but I think it should be at least broken out into it's own molecule. And I'd like a way to add either add the form piece by piece as you are doing here or by just rendering a form variable where the system implementing the code has bundled everything up into one variable already.

2017-01-03 04:17 UTC, gleroux02 commented on styleguide/source/_patterns/03-organisms/by-author/search-banner.twig
> +    <form class="ma__search-banner__form" action="{{searchBanner.action}}">
I've created a PR against this branch that will provide what I was describing: https://github.com/massgov/mayflower/pull/278.

2017-01-03 04:48 UTC, gleroux02 requested changes

2017-01-03 04:48 UTC, gleroux02 commented on styleguide/source/_patterns/02-molecules/footer-links.twig
>  <section class="ma__footer-links">
This needs a footer-links.md

2017-01-03 13:49 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/footer-links.twig
>  <section class="ma__footer-links">
You already did them => https://github.com/massgov/mayflower/pull/246

2017-01-03 13:49 UTC, merged