DP-796 mvp header
massgov/mayflower-patternlab pull request #295
Opened 2017-01-11 19:31 UTC by gender404

https://jira.state.ma.us/browse/DP-796

Refactored Utility Nav.
1. Removed Alerts section along with corresponding sccs and html code
2. Removed Sites Setting section along with corresponding sccs and html code
3. Created new State Organizations content panel
4. moved language dropdown up to the top level links
5. Refactored the html in Utility Nav to pull data from JSON
6. Updated content in login content panel
7. Updated dropdown molecule to pull data from JSON
8. Promoted Util Nav from molecule to organism

2017-01-12 00:41 UTC, gleroux02 requested changes
There are a few small things here. But otherwise it looks good.

2017-01-12 00:41 UTC, gleroux02 commented on styleguide/source/_patterns/02-molecules/utility-nav.md
> +- [@molecules/states-util](?p=molecules-states-util)
This link is not working properly. Also can we add the data structure from the utilityNav.json file here?

2017-01-12 00:41 UTC, gleroux02 commented on styleguide/source/_patterns/02-molecules/utility-nav.twig
>  <section class="ma__utility-nav js-util-nav">
I'd argue that since we are including other molecules that this should be an organism instead.

2017-01-12 00:41 UTC, gleroux02 commented on styleguide/source/_patterns/02-molecules/dropdown.twig
>      <select
Should there be a form element here with an action? Even if the submit is hidden? I'm not sure how we are going to do the language switch on the system side but I'd think we would need a form that the js can interact with.

2017-01-12 00:41 UTC, gleroux02 commented on styleguide/source/_data/stateUtil.json
> +}
Need a new line at end of file. There are a few places where this is the case.

2017-01-12 14:42 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/dropdown.twig
>      <select
I haven't put to much effort into this drop down, because I believe it is going to be replaced with google translate in the future.  A form and a visually hidden submit button would probably be fine.

2017-01-13 19:37 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/dropdown.twig
>      <select
I put the form on the Util Nav along with a hidden button.

2017-01-13 21:34 UTC, gleroux02 approved these changes

2017-01-13 21:41 UTC, merged