DP 1347 rmv wait time component update
massgov/mayflower-patternlab pull request #301
Opened 2017-01-18 20:31 UTC by jesconstantine

This PR alters the markup, presentation, and variable structure for the wait time component, based on the screenshot from visual design work done in [DP-822](https://jira.state.ma.us/browse/DP-822).

User Story: https://jira.state.ma.us/browse/DP-1347

Looking Design and Front End UAT.

## To Test

Either use screenshots below or:

1. Pull down branch and build styleguide
2. See molecule isolated at: /?p=molecules-wait-time
3. See component on rmv location page at: /?p=pages-LOC-Southbridge-RMV

## Screenshots

### From DP-822
![1-17_velir_mass_gov_waittimecomponent_psd___100___icon_copy_2__rgb_8__](https://cloud.githubusercontent.com/assets/3279883/22081541/f8f562e8-dd91-11e6-80c1-e68e61d18a5d.png)

### From work done (on org page)

#### Small
![image](https://cloud.githubusercontent.com/assets/3279883/22081662/6cdf00a6-dd92-11e6-91cd-7e38834a99b3.png)

#### Full
![image](https://cloud.githubusercontent.com/assets/3279883/22081686/86fc1604-dd92-11e6-9515-d78379ca7b1b.png)

### From work done (No wait time)
![image](https://cloud.githubusercontent.com/assets/3279883/22081750/d4b605d0-dd92-11e6-96e2-3770251d6005.png)

### From work done (closed)
![image](https://cloud.githubusercontent.com/assets/3279883/22081715/a186d0e0-dd92-11e6-884a-c78e01291c6a.png)

### From work Done (with error state)
![image](https://cloud.githubusercontent.com/assets/3279883/22081779/f92766fc-dd92-11e6-9838-b90d425ddd98.png)

2017-01-18 20:33 UTC, jesconstantine commented
@legostud I'm not positive that this PR should be merged, we mentioned removing this component all together.  But I thought it was a good place to start since you got my 85% of the way there with the existing component.

2017-01-19 17:44 UTC, gender404 requested changes

2017-01-19 17:44 UTC, gender404 commented on styleguide/source/assets/scss/02-molecules/_wait-time.scss
> +    margin-bottom: 1rem;
The display: flex and it's two other attributes can be removed

2017-01-19 17:44 UTC, gender404 commented on styleguide/source/assets/scss/02-molecules/_wait-time.scss
> -    margin-bottom: 20px;
flex-... aren't needed

2017-01-19 17:44 UTC, gender404 commented on styleguide/source/assets/scss/02-molecules/_wait-time.scss
> +  }
with flex removed, width: 100% isn't needed

2017-01-19 17:44 UTC, gender404 commented on styleguide/source/assets/scss/02-molecules/_wait-time.scss
>      font-size: 2.125rem;
should be &__time {

2017-01-19 17:44 UTC, gender404 commented on styleguide/source/assets/scss/02-molecules/_wait-time.scss
> +    font-style: italic;
font-size: italic; should be in the 06-themes version of this file.

2017-01-19 21:24 UTC, jesconstantine commented on styleguide/source/assets/scss/02-molecules/_wait-time.scss
> +    margin-bottom: 1rem;
Thanks for all of your feedback @legostud - addressed in https://github.com/massgov/mayflower/pull/301/commits/6f6db2c73f216c0c2424204d43f73ffc661d9588

2017-01-19 21:24 UTC, jesconstantine commented on styleguide/source/assets/scss/02-molecules/_wait-time.scss
> -    margin-bottom: 20px;
addressed in https://github.com/massgov/mayflower/pull/301/commits/6f6db2c73f216c0c2424204d43f73ffc661d9588

2017-01-19 21:24 UTC, jesconstantine commented on styleguide/source/assets/scss/02-molecules/_wait-time.scss
> +  }
addressed in https://github.com/massgov/mayflower/pull/301/commits/6f6db2c73f216c0c2424204d43f73ffc661d9588

2017-01-19 21:24 UTC, jesconstantine commented on styleguide/source/assets/scss/02-molecules/_wait-time.scss
>      font-size: 2.125rem;
addressed in https://github.com/massgov/mayflower/pull/301/commits/6f6db2c73f216c0c2424204d43f73ffc661d9588

2017-01-19 21:24 UTC, jesconstantine commented on styleguide/source/assets/scss/02-molecules/_wait-time.scss
> +    font-style: italic;
addressed in https://github.com/massgov/mayflower/pull/301/commits/6f6db2c73f216c0c2424204d43f73ffc661d9588

2017-01-19 21:47 UTC, gender404 approved these changes

2017-01-19 21:48 UTC, gender404 commented
I'm ok with merging this in.

2017-01-19 21:59 UTC, gender404 commented
If we decide to merge this in, could this please be added to the release notes for Sprint 11.

https://github.com/massgov/mayflower/blob/dev/release-notes.md

thanks.

2017-01-19 22:00 UTC, jesconstantine commented
Thanks again, @legostud ... just waiting for design input for this component in general.  I'll label WIP to make sure it doesn't get merged in until that happens.

2017-01-19 22:02 UTC, gender404 commented
@reenybeeny looked at on my computer and didn't have any immediate issues with it.  She usually reviews it after it has been merged into the dev environment.

2017-01-20 16:41 UTC, jesconstantine commented
Thanks @legostud and @reenybeeny -- I'll talk to @isaacchansky to get his thoughts on adding / removing this component from Mayflower.  If we merge, I'll certainly also add this to the release notes.

2017-01-20 17:23 UTC, isaacchansky commented
This looks good to me

2017-01-20 17:23 UTC, isaacchansky approved these changes

2017-07-01 10:48 UTC, closed without merging