DP-1279: Add rich text atom for use with WYSIWYG editors.
massgov/mayflower-patternlab pull request #308
Opened 2017-01-23 22:11 UTC by gleroux02

Ticket: https://jira.state.ma.us/browse/DP-1279

Creates an atom to display the "BLOB" from a rich text field. This would serve a need for any system that is implementing styleguide, but not for patternlab itself.

2017-01-24 15:40 UTC, gender404 requested changes
I'm going to start over now that I've reviewed both Pull Requests.  It appears that you are doing something quite clever with the Rich-Text Pattern when used in Drupal by including a blob of html code instead of the array of elements I'm using in PatternLab.  

This seems like a great solution.

The naming of this atom as "rich-text" is, however, confusing since the content displayed isn't rendered to match a Rich Text editor.  I think it would be better to call it "html-embed" or something like that since it is just a raw html field.

2017-01-25 14:30 UTC, gleroux02 commented
@legostud what about "raw-text" or "raw-html"?

2017-01-25 14:32 UTC, gender404 commented
I can go with "raw-html"

2017-01-25 14:34 UTC, gleroux02 commented
Yay, we named something! I'm sure we won't regret it in 5 minutes.

2017-01-25 14:36 UTC, gender404 commented
probably.  I'm already stifling other potential names, like uncooked-html (raw).

2017-01-25 16:39 UTC, gleroux02 commented
@legostud updated the name. And also removed the "Deprecated" state on paragraph as we can leave that alone.

2017-01-25 21:27 UTC, gender404 requested changes

2017-01-25 21:27 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/11-text/raw-html.json
> +  "richText" : {
Sorry to be a stickler, but this should be rawHtml for consistency (should match the filename)

2017-01-25 21:37 UTC, gleroux02 commented
@legostud updated.

2017-01-25 21:51 UTC, merged