DP-1270 structured data location
massgov/mayflower-patternlab pull request #310
Opened 2017-01-25 17:30 UTC by ygannett

Added Schema.org markup for page content elements to the following pages:
- LOC MT GRAYLOCK STATE PARK
- LOC SOUTHBRIDGE RMV
Any markup in this branch shouldn't be added to any other page types.

2017-01-26 16:36 UTC, gender404 requested changes
This code needs to be done differently.  This code has too many dependency between Patterns. For example the decorative-link pattern shouldn't be checking for a variable set in the action-event pattern.

We should find a better way to do this similar to what you have done for the link pattern.  That one is better approach, but naming it "map" doesn't feel very descriptive to me.

I ask Giles to take a look at this.  Maybe he can provide some idea.

2017-01-26 22:01 UTC, ygannett commented
I apologize for the lengthy reading.  Here is Structured Data 101.  My notes are shown in the blockquorts.
Please let me know for any questions.

### What is structured data?

Structured data is the data you add to your website to make it easier to understand for search engines. You need a vocabulary to make it work and the one big search engines use, is called Schema.org. Schema.org provides a series of tags and properties to mark up your products, reviews, local business listings, etc in detail. The major search engines, Google, Bing, Yandex, and Yahoo, collectively developed this vocabulary to reach a shared language in a quest to get a better understanding of websites.

> The markup is not visible to site users in browsers.

If implemented correctly, search engines can use the applied structured data to understand the contents of your page better. As a result, you might get a better presentation in the search results, for instance, in the form of rich snippets or rich cards. However, there are no guarantees you’ll get rich listings; it’s all up to the search engines.

### Why do you need Schema.org data?

Marking up your products, reviews, events, and more with structured data in the form of Schema.org makes your site instantly comprehensible by search engines. What this means, is that you can tell exactly what every part of your site is about. Search engines no longer have to guess that a product listing is a product listing, you can now say it is.

> By using the markup, you can establish the relationship between the data (= semantics of the data) in the page in relation to the main object of the page.
> 
> Examples: 
> 
> * you can tell search engines a specific address in the page is for the organization, office, or an event location 
> * you can tell what the main object of the page (= what the page is about) 
> 

### Is Schema.org important for your SEO?

To cut a long story short: yes, structured data in the form of Schema.org is important for your SEO. Correctly implementing data might not give you better rankings, but it will indirectly make your site a better search result.

Enhanced listings give searchers an easier way to pick a result from the list of links. If your listing is rich, and your page does what your listing promises, you are a valid result for the customer and that will lead to a lower bounce rate. A lower bounce rate tells Google that your site is a well-regarded result that promises and delivers.

> The correctly implemented markup can help search engines refine their resutls for better relevancy against search queries.  Then, search users could get to a page they want to be and wouldn't go back and forth between a search resutls page and listed pages on it. 

### Structured data leads to rich results

By making your site understandable for search engines, you give them the opportunity to do interesting things with your content. Schema.org and its support is in a constant flow, so changes will happen. Structured data forms the basis for a lot of new developments in the SEO world, so there’s bound to be more in the near future. Below are the kinds of rich search results that are in use at this moment.

#### Rich Snippets

Rich snippets are the extra pieces of information shown in a search result. In addition to the regular black lines of meta description text, a search result can be enhanced with product information like prices or reviews, or extra navigational tools like breadcrumbs or site search.

#### Sitelinks Searchbox

A Searchbox is the internal search engine of a site presented within the search results of Google. Google uses Schema.org code for this as well. 

#### Rich Cards

A Rich Card appears on mobile and is a new kind of rich search result developed by Google. Search results for certain types of items, like local restaurants, recipes, movies and courses, can get a special treatment in the mobile results. These are presented in a touch-friendly, swipeable way.

#### Knowledge Graph

The Knowledge Graph is the big block of information on the right-hand side in Google. This block details different kinds of information about a particular search result. If you have a validated company or if you are an authority on a certain subject, you might see your name, logo and social media profiles appear.

#### Featured snippets

This might be a sneaky addition because featured snippets are rich search results, but they do not get their content from structured data. A featured snippet answers a search question directly in the search results, but uses regular content from the viable web page to do so.

## Different kinds of Schema.org

If you look at the Schema.org website, you’ll notice that there are a lot of possibilities to add structured data to your site. Not everything is relevant, though. Before you start implementing Schema.org, you must know what you need to markup. Do you have a product in an online store? Do you own a restaurant? Or do you have a local business providing services to the community? Whatever it is, you need to know what you want to do and explore the possibilities.

Don’t go for the most obscure ones; pick the ones that are relatively easy to implement. Some Schema.orgs appear on less than a thousand sites, but others appear on millions. It’s possible to put the major Schema.orgs into two groups: Creative Works and Commerce. Within these groups, you will find the most common items to markup with Schema.org. 

## The technical details

To get started with making up your pages, you need to know about how Schema.org actually works. If you look closely at the [full specs on Schema.org](http://schema.org/docs/full.html), you’ll see that there is a strict hierarchy in the vocabulary. Everything is connected, just like everything is connected on your pages. Scroll through the list to see all the options at a glance and note down the ones you think you need.

>In Mass.gov, we have at least these 7 as a main entity of a page:
>
> 1. Thing > Intangible > Permit > ***GovernmentPermit***
> 2. Thing > Intangible > Service > ***GovernmentService***
> 3. Thing > Organization > ***GovernmentOrganization***
> 4. Thing > Organization > LocalBusiness > ***GovernmentOffice***
> 5. Thing > Place > GovernmentBuilding > ***Courthouse***
> 6. Thing > Place > GovernmentBuilding > ***LegislativeBuilding***
> 7. Thing > Place > CivicStructure > ***Park***
> 
> Their implementation is not programatically straightforward because of the way content types are created. So, picked something relatively easier to imeplement than the others.  That is the Location content type, ***Park*** for state parks and ***GovernmentOrganization*** for RMV as you see in DP-1270 structured data location #310.

> 
> 
> Starting from establishing the authensity of the site and the source of the information,
> In ***DP-1267 structure data page elements***, the Items 1 and 2 are implemented.  The Item 3 is some plumbing work for the next step, Item 4.  
> 
> 1. Identify what site the page blong to. (this is established in the home page of the site)
> 	```
> 	  <script type="application/ld+json">
> 	    {
> 	      "@context":"http://schema.org",
> 	      "@type":"WebSite",
> 	      "url":"https://www.mass.gov",
> 	      "name":"Mass.Gov",
> 	      "alternateName":"The Official Website of the Commonwealth of Massachusetts",
> 	      "copyrightHolder":"Commonwealth of Massachusetts",
> 	      "potentialAction":{
> 	        "@type":"SearchAction",
> 	         "target":"https://www.mass.gov/?s={search_term_string}&post_type=post",
> 	         "query-input":"required name=search_term_string"}
> 	    }
> 	  </script>
> 	```
> 2. Identify who owns the site and the page. (this is established in every page in the site. this can be omitted for error pages and other utility pages which are not necessary to be indexed by search engines)
> 	```
> 	<script type="application/ld+json">
> 	    { 
> 	      "@context" : "http://schema.org",
> 	      "@type" : "Orga [...]

2017-01-27 14:12 UTC, ygannett commented
This is the results of the validation of Google Structured Data Testing Tool.  
The validation was done with the content of the 2 location pages in Mayflower.
It shows how Google sees the data with the markup set up with this PR.
https://jira.state.ma.us/secure/attachment/71955/LOCATION_google_validation.docx

2017-01-27 19:03 UTC, gender404 requested changes

2017-01-27 19:03 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/action-section.twig
> +  {% set  sectionId = actionSection.id %}
I would merge this into actionSection.data instead of creating a new sectionId variable.  It's better to make sure all of your data is properly namespaced.

http://twig.sensiolabs.org/doc/2.x/filters/merge.html

2017-01-27 19:03 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/action-event.twig
> +      </span>
These meta tags should be actionEvent.meta.image.src, actionEvent.meta.image.alt, etc...

2017-01-27 19:03 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/action-event.twig
> +{% endif %}
Avoid duplicating your code.  more if else withing the code itself instead

2017-01-31 19:08 UTC, gender404 commented
Looks like you need to merge dev into this branch to resolve conflicts.

Contact Group seemed a bit complex so this is the merged code:
```
      {% elseif item.type == "address" %}
        <div class="ma__contact-group__address">
          {{item.value | raw}}
        </div>
        {% if item.link %}
          <div class="ma__contact-group__directions"{% if schemaPageType %} property="hasMap" typeof="Map"{% endif %}>
            {% set linkProperty = schemaPageType ? "url" : "" %}
            {% set link = { "text": "Directions", "href": item.link, "chevron": "true", "googleMapLink": linkProperty } %}
            {% include "@atoms/11-text/link.twig" %}
          </div>
        {% endif %}
```

2017-01-31 19:50 UTC, gender404 requested changes
This is getting better.  Still some rough spots.

FYI: @GBirch

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/11-text/link.json
> +    "googleMapLink": ""
This has very limited scope.  This could be used for more than just a map's url.  These links are used everywhere so being more generic would be better.

I'd rather see "property": "url" instead of "googleMapLink": "true"

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/11-text/link.md
> +        type: boolean
based on above comment, this would be:

```
property:
  type: string/optional
```

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/11-text/link.twig
> +<a class="ma__content-link {{link.chevron == 'true' ? 'ma__content-link--chevron' : ''}}" href="{{link.href}}"{% if link.googleMapLink == 'true'%} property="url"{% endif %}><span>{{link.text}}</span>
Better would be:
```
{% if link.property %} property="{{ link.property }}{% endif %}
```

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/decorative-link.twig
> +    <a href="{{decorativeLink.href}}" class="js-clickable-link"{% if decorativeLink == actionEvent.name and schemaPageType %} property="url"{% endif %}>{{decorativeLink.text}}{% if decorativeLink.inf
Better would be:
```
{% if link.property %} property="{{ link.property }}{% endif %}
```

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/decorative-link.twig
> +    <a href="{{decorativeLink.href}}" class="js-clickable-link"{% if decorativeLink == actionEvent.name and schemaPageType %} property="url"{% endif %}>{{decorativeLink.text}}{% if decorativeLink.inf
Better would be:
```
{% if link.property %} property="{{ link.property }}{% endif %}
```

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/decorative-link.twig
>  </span>
We need to update to the json and md files for this component similar to the link.json and link.md files.

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/action-section.twig
> +{% include actionSection.path with actionSection.data %}
missing the newline at the end

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/action-section.json
> +        "schemaSdProperty": "description",
This one is a bit tricky due to how the rich-text pattern was built.  It should have had a parent "richText" object, but I used rteElements array instead which was a mistake on my part.

To accomplish this we'll need to put in a breaking change shown below, which means updating a lot of PatternLab patterns and Drupal code.

```
"data": {
  "richText": {
    "property": "description",
    "rteElements": [{ ... }]
  }
}
```

Maybe @GBirch can help advise here

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +        </span>
I would move the meta tag to either before or after the span tag.  not within it.

Also we can use the new property value used for telephone here as well.

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +        {% endif %}
"Main:" is a weak test.  This is content so the content editor could enter "Main" or "Primary" and break your code.

Maybe we add another data attribute to contactGroup, like the property value used on links.

TWIG
```
{% if item.property %}
  <meta property="{{ item.property }}" content="{{ item.value }}" />
{% endif %}

JSON
```
{
      "type": "phone",
      "property": "telephone",
      "label": "Main:",
      "value": "(413) 499-4262",
      "link": "14134994262",
      "details": "This line is open from 9:00 a.m. - 5:00 p.m., M-F"
}
```

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/header-contact.json
> +      "googleMapLink": "true"
"property": "url"

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/header-contact.md
> +      type: boolean
based on above comment, this would be:

```
property:
  type: string/optional
```

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/header-contact.twig
>    </div>
This file will be depreciated after this sprint.  The header will be using the contact us pattern instead.

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/rich-text.twig
> +{% endfor %}
This just doesn't work.  You can't put the `<section>` within the for loop

2017-01-31 19:50 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-template/action-header.json
>        "icon": "@atoms/05-icons/svg-phone.twig",
"headerContact" is being replaced with "actionHeader.contactUs" during this sprint.

2017-01-31 20:09 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/rich-text.twig
> +{% endfor %}
I think we could work towards the ideal solution without making a breaking change.  We can make this pattern look for rteElements at the root level or within a new richText object.

JSON
```
{
  "richText": {
    "property": "description",
    "rteElements": [{ ... ]];
  }
} 
```

Twig
```
{# Backward compatible with v3.2 #}
{% if richText.rteElements %}
  {% set rteElements = richText.rteElements %}
{% endif %}

<section class="ma__rich-text js-ma-rich-text"{% if richText.property %} property="{{ richText.property }}{% endif %}>
...
```

2017-01-31 20:11 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/action-section.json
> +        "schemaSdProperty": "description",
See a new comment on the rich-text.twig that describes a way to do this without it actually breaking anything.

2017-01-31 21:41 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +        {% endif %}
I was under the assumption that the label's value is coming from a dropdown list or some sort of pre-populated options.  I don't want the telephone property to be used for fax, TTY, TRS and other types. Currently, "telephone" and "faxNumber" are only properties defined by Schema.org.  I think I need to think about this more...

2017-01-31 21:53 UTC, ygannett commented
@legostud, thank you very much for the detailed notes.  I'll go through and work on them.

2017-01-31 22:07 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +        {% endif %}
if we use 'property', then Drupal can make sure to target the correct contact, probably the first or via an interface if needed.

2017-02-01 14:53 UTC, ygannett commented on styleguide/source/_patterns/01-atoms/11-text/link.json
> +    "googleMapLink": ""
"googleMapLink": "true" is replaced with "property": "url".
I was not clear how it works with "property": "url" before, but I have better understanding of this. It makes more sense than "googleMapLink": "true"/"map": "true".

2017-02-01 16:18 UTC, ygannett commented on styleguide/source/_patterns/01-atoms/decorative-link.twig
> +    <a href="{{decorativeLink.href}}" class="js-clickable-link"{% if decorativeLink == actionEvent.name and schemaPageType %} property="url"{% endif %}>{{decorativeLink.text}}{% if decorativeLink.inf
For this template, `decorativeLink.property` instead of `link.property`?

2017-02-01 16:46 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +        {% endif %}
I see. Thank you.

2017-02-01 17:01 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/decorative-link.twig
> +    <a href="{{decorativeLink.href}}" class="js-clickable-link"{% if decorativeLink == actionEvent.name and schemaPageType %} property="url"{% endif %}>{{decorativeLink.text}}{% if decorativeLink.inf
yes. thanks for catching that.  I did a poor copy and paste

2017-02-01 21:04 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +        {% endif %}
Now, I can see how this is scalable.  This is great! I used it to the other types in the template, too.

2017-02-02 02:19 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/header-contact.twig
>    </div>
I didn't do anything for the change to the contact us pattern at this round.

2017-02-03 14:09 UTC, gender404 requested changes
Nice job.  This is really good.

One change for the Rich Text and I think this is good to go.

2017-02-03 14:09 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/action-details.json
> +        "property": "description",
needs to be 
```
"data": {
  "richText": {
    "property": "description",
    "rteElements: [{ ... }]
  }
}

2017-02-03 14:09 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/action-details.json
> +        "property": "description",
same with the ones below

2017-02-03 14:09 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/rich-text.twig
> +<section class="ma__rich-text js-ma-rich-text"{% if property %} property="{{property}}"{% endif %}>
instead of "property" use richText.property.  I commented on the code in the action-details.json to make this work.

2017-02-03 14:09 UTC, gender404 commented on styleguide/source/_patterns/05-pages/LOC-Southbridge-RMV.json
> +        "property":"description",
Should be 
```
"data": {
  "richText": {
   "property": ...
```

same as mentioned above

2017-02-03 14:09 UTC, gender404 commented on styleguide/source/_patterns/05-pages/LOC-Mt-Greylock-State-Park.json
> +        "property": "description",
Should be 
```
"data": {
  "richText": {
    "property":...
```
same as mentioned above

2017-02-03 19:33 UTC, gender404 approved these changes

2017-02-03 19:35 UTC, merged