Dp 1374 convey menu state to screen reader
massgov/mayflower-patternlab pull request #329
Opened 2017-02-07 14:39 UTC by yriahi

## Overview
This PR enables the the main nav to convey menu state to screen readers.

## Testing
- Go to http://localhost:3000/?p=molecules-main-nav
- Enable screen reader
- Click inside the browser window to bring it to focus
- Hit tab
- Screen reader will announce menu items as collapsed (see screenshot).
<img width="714" alt="screen_shot_2017-02-07_at_1_46_00_pm" src="https://cloud.githubusercontent.com/assets/1906849/22706119/138660a8-ed3c-11e6-9327-9f69f72ec13a.png">

2017-02-07 19:49 UTC, isaacchansky commented on styleguide/source/assets/js/modules/mainNav.js
> +      // show($link.find('.js-main-nav-content'));
Let's remove the above block entirely instead of commenting it out if it isn't useful code.

2017-02-07 19:52 UTC, isaacchansky requested changes

2017-02-07 19:52 UTC, isaacchansky commented on styleguide/source/assets/js/modules/mainNav.js
> +       if((e.keyCode === 38) || (e.keyCode === 9 && isShift)) {
Can we extend this comment indicating that this is "up arrow or tab + shift?

2017-02-07 19:52 UTC, isaacchansky commented on styleguide/source/assets/js/modules/mainNav.js
> +      if((e.keyCode === 40) || (e.keyCode === 9 && !isShift)) {
Can we extend this comment indicating that this is "down arrow or tab ?

2017-02-07 20:09 UTC, yriahi commented on styleguide/source/assets/js/modules/mainNav.js
> +      // show($link.find('.js-main-nav-content'));
Addressed in 1ea8651a0a8f76748983564c34a67579d8e78243

2017-02-07 20:11 UTC, yriahi commented on styleguide/source/assets/js/modules/mainNav.js
> +      if((e.keyCode === 40) || (e.keyCode === 9 && !isShift)) {
Addressed in 39b682858e43374ebe60959a1a816a6ff658250c

2017-02-07 20:11 UTC, yriahi commented on styleguide/source/assets/js/modules/mainNav.js
> +       if((e.keyCode === 38) || (e.keyCode === 9 && isShift)) {
Addressed in 39b682858e43374ebe60959a1a816a6ff658250c

2017-02-07 20:56 UTC, gender404 requested changes

2017-02-07 20:56 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/main-nav.twig
> +      {% set menuId =  nav.text|lower ~ '-' ~ loop.index %}
Clever approach to creating ids, but these aren't valid ids => "visiting & exploring-button-4"  You should be able to do this with just `buttonId = 'button' ~ loop.index  and menuId = 'menu' ~ loop.index
```
ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").
```

2017-02-07 20:56 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/main-nav.twig
> +            <ul id="{{ menuId }}" role="menu" aria-labelledby="{{ buttonId }}" class="ma__main-nav__container">
I can't find where menuId is referenced.  Is this needed?

2017-02-07 20:56 UTC, gender404 commented on styleguide/source/assets/js/modules/mainNav.js
> +          console.log(isShift);
you left a console.log in the code.

2017-02-08 13:11 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/main-nav.twig
> +            <ul id="{{ menuId }}" role="menu" aria-labelledby="{{ buttonId }}" class="ma__main-nav__container">
Yep, the `<button>` has an `aria-controls` attribute which references the menuId.

2017-02-08 13:46 UTC, yriahi commented on styleguide/source/assets/js/modules/mainNav.js
> +          console.log(isShift);
Addressed in e379f8a

2017-02-08 15:48 UTC, yriahi commented on styleguide/source/_patterns/02-molecules/main-nav.twig
> +      {% set menuId =  nav.text|lower ~ '-' ~ loop.index %}
Addressed in a331f1d

2017-02-09 18:08 UTC, isaacchansky approved these changes

2017-02-09 18:45 UTC, jesconstantine approved these changes
Seems to me like @yriahi has addressed @legostud's concerns.  I'm going to merge this.

2017-02-09 18:46 UTC, merged