DP-1370 Radio buttons and checkboxes more visible in feedback forms
massgov/mayflower-patternlab pull request #357
Opened 2017-03-06 15:48 UTC by mrossi113

Accessibility fix to make the radio buttons and check boxes more visible on feedback form. The border color for these were changed to #757575 per Sarena and Harlan request in the comments. These checkbox and radio buttons borders were changed from border-color: $c-bd-input; to border-color: #757575;

JIRA ticket: https://jira.state.ma.us/browse/DP-1370

To test:
Compare the radio button with the current pilot.mass.gov/topics/health-social-services feedback form.
Inspect the radio button and change the .ma__input-radio border color to #757575
To compare the check box go to http://localhost:3000/?p=pages-pilot-transition vs current site https://pilot.mass.gov/leaving-pilot?continueURL=http://www.mass.gov/dor/child-support/court-information/paternity-establishment/

2017-03-06 16:20 UTC, gender404 reviewed
We have been trying to not use colors directly in SASS files to help maintain consistency.  To make this #757575 you should either create a new variable $c-bd-input-dark or change the value of $c-bd-input to #757575.

Variables are named using a pattern:
c => color variable
bd => applies to borders
input => descriptive name
dark => optional modifier

I'm going to go out on a limb here and say that we are most likely going to need to change the border color on all inputs to #757575 for readability.  

You just need to search the scss file to determine what other items are using this variable before updating.

2017-03-06 16:22 UTC, reenybeeny commented
@legostud / @mrossi113 - it was decided not to change the border color on inputs or dropdowns at this time, so the change should only apply to radio buttons and checkboxes.

2017-03-06 16:45 UTC, mrossi113 commented
@legostud / @reenybeeny  Okay I will create a new variable in the SASS file with #757575 for just these two radio buttons and checkboxes border color.

2017-03-08 20:51 UTC, isaacchansky commented
Probably a good idea to darken the borders, but the real purpose of this ticket is to fix the issue of identifying _focus_.

So the user-story here is "as someone with potential visual impairment, it should be easy for me to tell where my keyboard focus is." 

It looks like the focus styles haven't changed, they're still:
```
outline-color: -webkit-focus-ring-color;
```

2017-03-09 14:23 UTC, gender404 commented
The radio button is missing the outline.  You can try adding that to make it more visible.

.ma__input-radio input:focus ~ label:before {
  outline: -webkit-focus-ring-color auto 5px;
}

.ma__input-radio label:before {
 ... 
 overflow: hidden;
  ...
}

2017-03-09 20:08 UTC, mrossi113 commented
Talked with @WheresHJ about the border color and the focus for checkboxes and radio buttons. From the discussion was to keep the #757575 as the border color as well as the suggestion from @legostud 

`.ma__input-radio input:focus ~ label:before {
outline: -webkit-focus-ring-color auto 5px;
}
.ma__input-radio label:before {
...
overflow: hidden;
...
}`

@isaacchansky Harlan said he would talk with you about these changes.

2017-03-09 20:09 UTC, gender404 requested changes
Just a few changes

2017-03-09 20:09 UTC, gender404 commented on styleguide/source/assets/scss/06-theme/00-base/_colors.scss
> +$c-bd-input-dark: $c-gray-757575;
nicely done

2017-03-09 20:09 UTC, gender404 commented on styleguide/source/assets/scss/01-atoms/_forms.scss
> +      overflow: hidden;
I don't believe this is needed here.  I added it to the radio button due to the font-size being larger than the height.  

If you want to see an interesting outline shape, use the inspector tools to turn overflow:hidden off on the radio button before element.

2017-03-09 20:09 UTC, gender404 commented on styleguide/source/assets/scss/06-theme/01-atoms/_forms.scss
> +      outline: -webkit-focus-ring-color auto 5px;
outline includes outline-color so you don't need both.

2017-03-09 20:09 UTC, gender404 commented on styleguide/source/assets/scss/06-theme/01-atoms/_forms.scss
> +      outline: -webkit-focus-ring-color auto 5px;
outline includes outline-color so you don't need both.

2017-03-09 20:15 UTC, isaacchansky commented
Cool this looks good for now. We'll plan to circle back later and look at all focus states holistically to ensure that we're consistent and deliberate about how the whole system works together.

2017-03-09 20:15 UTC, merged

2017-03-09 20:41 UTC, mrossi113 commented on styleguide/source/assets/scss/01-atoms/_forms.scss
> +      overflow: hidden;
Yes the `overflow:hidden` was not needed for the checkboxes only the radio buttons. Made the change.

2017-03-09 20:41 UTC, mrossi113 commented on styleguide/source/assets/scss/06-theme/01-atoms/_forms.scss
> +      outline: -webkit-focus-ring-color auto 5px;
Removed the outline-color

2017-03-09 20:41 UTC, mrossi113 commented on styleguide/source/assets/scss/06-theme/01-atoms/_forms.scss
> +      outline: -webkit-focus-ring-color auto 5px;
Removed the outline-color

2017-03-09 20:53 UTC, isaacchansky commented
Sorry, closed this too early: adjustments @legostud suggested are being done here: https://github.com/massgov/mayflower/pull/365/files