DP-1795 a11y Alert Elements changes
massgov/mayflower-patternlab pull request #358
Opened 2017-03-06 16:54 UTC by ygannett

## DP-1854

Note: Please inquire of @mrossi113 this item.  Her change is in my PR because it happened to be in the template I'd been working on.

Add `tabindex="0"` to `.ma__emergency-alert` container.

## DP-1874

Add semantics to the alert section.

### Alert Heading

`<div class="ma__emergency-header">` is replaced with `<h2>` to accommodate the alert type addressed in `.ma__emergency-header__label` as a part of the header.

Ensure the icon is invisible to AT by wrapping it with `<span aria-hidden="true" role="presentation">`. 

It was suggested to add `title` to the icon to replace `<span>Emergency Alerts</span>`, but took this approach to allow the icon for other use just in case if such needs arise in the future.

### Alert Message

Create the semantics between the alert message and its contained link by replacing `<div>` container with `<p>`.

To maintain valid HTML, all nested `<div>`s inside the `<p class="ma__emergency-alert">` are replaced with `<span>`s.

### CSS changes
To maintain the same visual as the original code's, some adjustment was added to  related styles.  The affected styles are all emergency alert specific ones, wouldn't affect other part of the page elements.

## Outcome with This PR
1. No visual changes.
2. HTML output

```
<section class="ma__emergency-alerts js-accordion js-emergency-alerts" data-id="1488812019">
  <div class="ma__emergency-alerts__header">
    <div class="ma__emergency-alerts__container">
      <h2 class="ma__emergency-header">
        <div class="ma__emergency-header__label">
            <svg aria-hidden="true" id="SvgjsSvg1000" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" width="48" height="44" viewBox="0 0 48 44"><defs id="SvgjsDefs1001"/><path id="SvgjsPath1007" d="..."/></svg>   
          <span>Emergency Alerts</span>
        </div>
        <div class="ma__emergency-header__title">emergency alert headline 2</div>
      </h2>
      <div class="ma__emergency-alerts__header-interface js-accordion-link">
        <button class="ma__button-alert">
          <span class="ma__button-alert__hide">hide</span>
          <span class="ma__button-alert__show">show</span> alerts
        </button>
      </div>
    </div>
  </div>

  <div class="ma__emergency-alerts__content js-accordion-content" style="display: none;">
    <div class="ma__emergency-alerts__container">
      <p class="ma__emergency-alert" tabindex="0">
        <span class="ma__emergency-alert__message">emergency alert message <span class="ma__emergency-alert__time-stamp">03.06.17, 9:53 am</span></span>
        <span class="ma__emergency-alert__link">
          <a class="ma__content-link ma__content-link--chevron" href="/alerts#13613"><span>more</span></a>
        </span>
      </p>
      <p class="ma__emergency-alert" tabindex="0">
        <span class="ma__emergency-alert__message">emergency alert message2 <span class="ma__emergency-alert__time-stamp">03.06.17, 9:53 am</span></span>
        <span class="ma__emergency-alert__link">
          <a class="ma__content-link ma__content-link--chevron" href="/alerts#13614"><span>see more</span></a>
        </span>
      </p>
    </div>
  </div>
  <div class="ma__emergency-alerts__interface js-accordion-link">
    <button class="ma__button-alert">
      <span class="ma__button-alert__hide">hide</span>
      <span class="ma__button-alert__show">show</span> alerts
    </button>
  </div>
</section>

```

## Testing

1. Check for above code in HTML
2. The visual maintains the current one. See the screenshots.
![alert_close](https://cloud.githubusercontent.com/assets/9633303/23619188/dafb7b8a-0260-11e7-8daf-362631278f63.png)
![alert_open](https://cloud.githubusercontent.com/assets/9633303/23619193/dfc3c23a-0260-11e7-95c3-ce2cdf0673fa.png)
3. Screen readers should
	*  announce the alert label text as a part of the alert title, "emergency alerts *emergency alert headline 2*",
	*  recognize the link within `<p class="ma__emergency-alert">` is associated with the alert message.

2017-03-06 17:27 UTC, mrossi113 commented
## Testing-DP-1854
- [ ] Type in URL http://localhost:3000/?p=organisms-emergency-alerts
- [ ] Than tab until user come to "show alert" click return to show the alerts the focus should stay on "hide alerts"
- [ ] Next time the user tabs it should go to "MassPort is operating..." and through each message alert.

2017-03-06 18:47 UTC, gender404 requested changes
This first obvious issue I see is that the styling for this no longer correct.  Desktop is too tall, icon has grown in size, and as you shrink the width of the browser the items no longer wrap correctly.

When making changes to html, please, always compare the styling between your local:
localhost:3000/?p=organisms-emergency-alerts
and prod:
http://mayflower.digital.mass.gov/?p=organisms-emergency-alerts

2017-03-06 18:47 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/emergency-header.twig
> +    <span aria-hidden="true" role="presentation">{% include "@atoms/05-icons/svg-alert.twig" %}</span>
this isn't needed.  All svg icons already have aria-hidden on the SVG element.  We determined this to be the more common use case for icons.

2017-03-06 18:47 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/emergency-alert.twig
> +  <span class="ma__emergency-alert__link">
This is technically correct in that you are just replacing the div with a span.  Looking beyond that, it appears that the if statement was placed in the wrong spot originally.  The "ma__emergency-alert__link" span tags should be inside the if statement to prevent rendering and empty span tag.

2017-03-06 18:47 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/emergency-header.twig
> +    <span aria-hidden="true" role="presentation">{% include "@atoms/05-icons/svg-alert.twig" %}</span>
Also adding a layer of nesting broken the CSS on the icon (it's too large)

.ma__emergency-header__label > svg {
    height: 32px;
    width: 36px;
}

2017-03-06 18:47 UTC, gender404 commented on styleguide/source/assets/scss/02-molecules/_emergency-header.scss
> +h2.ma__emergency-header {
using h2. isn't necessary or desired.  This adds an extra layer of specificity that doesn't appear to be needed.

2017-03-06 18:47 UTC, gender404 commented on styleguide/source/assets/scss/02-molecules/_emergency-header.scss
> +
Using inherit would probably be better than setting this, but I could go either way.
    font-size: inherit;
    line-height: inherit;

you also need to add margin: 0; to this to correct the styling.

2017-03-07 16:28 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/emergency-header.twig
> +    <span aria-hidden="true" role="presentation">{% include "@atoms/05-icons/svg-alert.twig" %}</span>
Will remove the span.

2017-03-07 16:31 UTC, ygannett commented on styleguide/source/assets/scss/02-molecules/_emergency-header.scss
> +h2.ma__emergency-header {
Will remove this section.

2017-03-07 16:40 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/emergency-alert.twig
> +  <span class="ma__emergency-alert__link">
The if statement for the link has been moved outside to wrap `<span class="ma__emergency-alert__link">` to prevent empty `<span>`.

2017-03-07 16:40 UTC, ygannett commented on styleguide/source/assets/scss/02-molecules/_emergency-header.scss
> +
These styles are added to `.ma__emergency-header`.

2017-03-07 19:59 UTC, gender404 commented on styleguide/source/assets/scss/02-molecules/_emergency-header.scss
> +
There are still styling issues.  Maybe I confused things with the above comment "correct the styling" that was just to fix the header.  let me know if you would like some help fixing the other styling issues.

2017-03-08 14:12 UTC, powpow12 commented
@ygannett I am running into a [local bug with my mayflower implementation](https://github.com/massgov/mayflower/issues/363) so I cannot troubleshoot the code well but I do see some visual differences.  

- Align to the left
- Missing button
- Alerts accordion starts opened

![image](https://cloud.githubusercontent.com/assets/3721535/23707103/0f6b46e6-03df-11e7-910b-4b8337b23864.png)

2017-03-08 20:34 UTC, isaacchansky commented
I'm not seeing any visual difference between the local build & the mayflower.digital.mass version (see gif of me switching between local & mayflower.digital.mass version)

@legostud are you still noticing differences?

![alerts-comparison](https://cloud.githubusercontent.com/assets/1397914/23722689/57c5c1d4-0414-11e7-84f3-5d53837a0742.gif)

2017-03-08 20:35 UTC, isaacchansky approved these changes

2017-03-09 14:03 UTC, gender404 commented
It looks fine to me now.

2017-03-09 14:03 UTC, gender404 approved these changes

2017-03-09 14:04 UTC, gender404 commented
This Pull Request still says WIP, but I think it's okay to merge.

2017-03-09 14:39 UTC, ygannett commented
Thank you all for your help. I just removed the WIP label.

2017-03-09 15:26 UTC, merged