DP-1893 [a11y] add the status of alert message display with aria
massgov/mayflower-patternlab pull request #361
Opened 2017-03-07 19:03 UTC by ygannett

No visual change.

Add `aria-expanded` to the alert `<button>` to tell the current status of the display of the alert messages. Its value gets changed between `true` and `false` with JavaScript as the button is clicked.

## Testing
- [ ] The `aria-expanded` value is `false` when the alert messages are hidden.
<img width="751" alt="button_close" src="https://cloud.githubusercontent.com/assets/9633303/23672879/2a289372-033e-11e7-9675-5fa2120e16c9.png">
- [ ] The `aria-expanded` value is `true` when the alert messages are shown.
<img width="748" alt="button_open" src="https://cloud.githubusercontent.com/assets/9633303/23672885/2efb3e2c-033e-11e7-9640-b76d523419d7.png">
- [ ] The status gets updated as the `<button>` is clicked accordingly.

2017-03-07 19:47 UTC, gender404 requested changes
Sorry for all the small changes.  They kind of built on top of each other as I was reviewing.

2017-03-07 19:47 UTC, gender404 commented on styleguide/source/assets/js/modules/emergencyAlerts.js
> +     $buttonState === 'false' ? $buttonState = 'true' : $buttonState = 'false';
for future reference this would be written $buttonState = $buttonState === 'false' ? 'true' : 'false';

2017-03-07 19:47 UTC, gender404 commented on styleguide/source/assets/js/modules/emergencyAlerts.js
> +        $buttonState = $(this).find('.ma__button-alert').attr('aria-expanded');
This isn't the right approach.  
1. You're using a CSS class to target an element using JS.  You should only use JS classes ('.js-...')
2. This button may not always be an accordion button so having the attribute in the code is not ideal.  Would be better to have the JS add the attribute instead.
3. We already have a variable (open) tracking the state of the accordion so we can just use that variable instead.

2017-03-07 19:47 UTC, gender404 commented on styleguide/source/assets/js/modules/emergencyAlerts.js
> +     $(this).find('.ma__button-alert').attr('aria-expanded',$buttonState);
This made me realized that the click event should have been on the button not the div wrapping it.

Once that change is made, this can be simplified to $el.attr('aria-expanded', open);

I'm pretty certain we can pass a boolean value to the attribute, but if it doesn't work then use a ternary to switch it to a string value => open ? 'true' : 'false';

2017-03-07 19:47 UTC, gender404 commented on styleguide/source/assets/js/modules/emergencyAlerts.js
>      $el.on('click','.js-accordion-link',function(){
There appears to be an existing issue here.  The click really should be on the button not the js class and we're missing the e.preventDefault(); to make sure we don't accidentally submit a form on the page.

$button.trigger('click');

and 

$button.on('click', function(e) {
  e.preventDefault();

2017-03-07 19:47 UTC, gender404 commented on styleguide/source/assets/js/modules/emergencyAlerts.js
>        // cookieValue is a string so we can't use the value directly
in this conditional we should also include an update to the button.
$button.attr('aria-expanded', open);

2017-03-07 19:47 UTC, gender404 commented on styleguide/source/assets/js/modules/emergencyAlerts.js
> +        $buttonState = $(this).find('.ma__button-alert').attr('aria-expanded');
I would suggest we create a new variable to save the button element.
$button = $el.find('.js-accordion-link button');

2017-03-07 19:47 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/button-alert.twig
> +<button class="ma__button-alert" aria-expanded="false">
Let's leave this off since the button could be used elsewhere and not need aria-expanded.  We'll have the JS add it instead.

2017-03-08 21:15 UTC, ygannett commented on styleguide/source/assets/js/modules/emergencyAlerts.js
>      $el.on('click','.js-accordion-link',function(){
Would you like to have everything in `$el.on('click','.js-accordion-link',function(){}` to be in `$button.on('click', function(e) {}`, or just the what I added?  Just making sure, I don't know how the cookie stuff would be affected by this.

2017-03-09 14:55 UTC, gender404 commented on styleguide/source/assets/js/modules/emergencyAlerts.js
>      $el.on('click','.js-accordion-link',function(){
everything should be in there.

2017-03-09 15:16 UTC, ygannett commented on styleguide/source/assets/js/modules/emergencyAlerts.js
> +     $buttonState === 'false' ? $buttonState = 'true' : $buttonState = 'false';
Ok.  Thank you.

2017-03-09 15:17 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/button-alert.twig
> +<button class="ma__button-alert" aria-expanded="false">
That has been removed from this template and inserted by JS.

2017-03-09 15:18 UTC, ygannett commented on styleguide/source/assets/js/modules/emergencyAlerts.js
> +     $(this).find('.ma__button-alert').attr('aria-expanded',$buttonState);
Used the open variable to all related areas.

2017-03-09 15:25 UTC, gender404 requested changes
This is much better, but there are still a couple of changes.

2017-03-09 15:25 UTC, gender404 commented on styleguide/source/assets/js/modules/emergencyAlerts.js
> +        $buttonState = $button.attr('aria-expanded', !open);
$buttonState = $button.attr('aria-expanded', !open);
This line isn't needed.  It will be set either by line 18 or by line 37 to the proper value.

2017-03-09 15:25 UTC, gender404 commented on styleguide/source/assets/js/modules/emergencyAlerts.js
>      });
This can be reduced to just $(this).attr('aria-expanded', open);

2017-03-09 15:25 UTC, gender404 commented on styleguide/source/assets/js/modules/emergencyAlerts.js
> +      $buttonState = $buttonState === open ? !open : open;
This isn't needed and doesn't make any sense to me.  Sorry to be blunt, but that is a very odd line of code.  You are basically saying if the two values are equal make them not match and if they don't match make then equal.

2017-03-10 17:52 UTC, ygannett commented
I noticed some inconsistent behaviors when the page is loaded. Sometimes the `<button>` has `aria-expanded="false"`, sometimes it doesn't.  It seems that it doesn't have the attribute when the page is loaded for the first time (= no cache, no history of the alert).
<img width="729" alt="alerts-first_load" src="https://cloud.githubusercontent.com/assets/9633303/23804804/74249c4e-0589-11e7-914b-597ec1ef79a9.png">

When the button is clicked with this condition, the attribute's value is set opposite.  It's set to `true` when it's supposed to be `false`.

@isaacchansky helped me to see it's coming from the condition;
```
 if(typeof(cookieValue) != 'undefined' && cookieValue === 'false') {
      // cookieValue is a string so we can't use the value directly
      open = false;

      $button.attr('aria-expanded', open);
    }
```
When the condition is changed to
```
if(typeof(cookieValue) === 'undefined' || cookieValue === 'false')
```
the attribute is inserted to the `<button>` every time the page is loaded with the correct value, and the value is updated correctly with clicks.

So, the question is that how this change affects the cookie. I don't know what's this cookie is about. Should the cookie and the aria-expanded have their own conditions for each to maintain their own features?

2017-03-10 22:13 UTC, gender404 commented
Thank you for finding that bug.  It was interesting to figure out what was actually happening in the code.

Originally, I was triggering the click on the js-accordion-link element and everything appeared to be working fine.  In reality it wasn't quite doing what I thought.  I had assumed that it was calling the click event in emergencyAlerts, but since the click event hadn't been bound yet, it was just calling the accordion click event and nothing else.  This gave the impression that things were working properly.

It also appears that we were triggering the accordion twice since we have two buttons in the code now so I'm guessing that also added some issues.

I pushed up some changes and it should be working fine now.

2017-03-10 22:14 UTC, merged