Dp 2114 service page
massgov/mayflower-patternlab pull request #373
Opened 2017-03-17 14:32 UTC by gender404

This is still being worked on, but I'm hoping to wrap it up today.

Ticket:
https://jira.state.ma.us/browse/DP-2114

Goal - Create new Services Page.

New Patterns:
- Teaser Text - Rich Text with an optional decorative link (learn more)
- Services Template - Based on stacked row, but with some additional classes

Updated Patterns:
- Video - added float right option
  - Added new data variable => position
- Action Finder - New view triggered by removing the background image
  - Added new variables => Id and hideFilter
- Page Banner - New overlay style 
  - Added new variable => color
  - Added new value to size => 'overlay'
- Link list - Added controls for heading type and single vs double column
  - Added new variable => stacked to trigger the single column view
  - changed variable 'title' to be either compHeading or sidebarHeading
  - added v3.5 code to set compHeading if the 'title' is still being used
- Split Columns - adjusted the spacing for 50/50 split.
- Mapped Locations
  - new variables => info and property

2017-03-17 15:23 UTC, jesconstantine commented
@legostud  Do you know if this PR is touching so many files because we never synced master back down to dev after the release?  cc: @isaacchansky

2017-03-17 16:36 UTC, isaacchansky commented
Doesn't seeeeem to be related - the attached img is the visualized state of git.

<img width="379" alt="screen shot 2017-03-17 at 12 33 10 pm" src="https://cloud.githubusercontent.com/assets/1397914/24053126/5bdae258-0b0e-11e7-95da-6efb1b833bf7.png">

2017-03-17 20:01 UTC, gender404 commented
@lukewertz - Services page

2017-03-17 21:34 UTC, gender404 commented
@jesconstantine, @isaacchansky - Yes, the extra files in there are because dev doesn't include master.  I always create my branches off of master to make sure I'm working with clean code to start.  This process works well with small changes.

This, being a larger task, required a merge from dev so the code isn't quiet as clean as I prefer.

2017-03-20 21:46 UTC, gleroux02 requested changes

2017-03-20 21:46 UTC, gleroux02 commented on styleguide/source/_patterns/03-organisms/by-author/link-list.twig
> +    {# added for backward compatibilty with v3.5 #}
The changes to the link list seem to be an issue on the org page. 
![screen shot 2017-03-20 at 4 13 59 pm](https://cloud.githubusercontent.com/assets/394763/24122038/69ddd794-0d88-11e7-946c-c605b9225995.png)

2017-03-20 21:46 UTC, gleroux02 commented on styleguide/source/_patterns/04-templates/01-content-types/services.twig
> +{% include "@organisms/by-template/header.twig" %}
Should the services here also show the "Related Services" and "Additional Resources" link lists that display in the 05-pages directory? I guess I'm not sure why we need to have it in both places.

2017-03-20 21:46 UTC, gleroux02 commented on styleguide/source/_patterns/04-templates/01-content-types/services.twig
> +              {% include "@atoms/09-media/image.twig" %}
I don't have a solution, but my preference would be to not print this image twice for performance reasons.

2017-03-20 21:46 UTC, gleroux02 commented on styleguide/source/_patterns/04-templates/01-content-types/services.twig
> +        <aside class="sidebar sidebar--intro">
All of the elements inside of the aside are optional, let's make the aside markup optional too.

2017-03-20 21:46 UTC, gleroux02 commented on styleguide/source/_patterns/04-templates/01-content-types/services.twig
> +{% include "@organisms/by-template/header.twig" %}
I don't think that this file should have the header or footer in it. As the system that implements it won't have that data at this level.

2017-03-21 13:25 UTC, gender404 commented on styleguide/source/_patterns/04-templates/01-content-types/services.twig
> +              {% include "@atoms/09-media/image.twig" %}
There shouldn't be any performance issues if it is the exact same image (same path).  The Browser will only do one request to fetch the image and then display it in multiple locations.

2017-03-21 15:55 UTC, gender404 commented
@gleroux02 - I think I fixed all of the issues you found.  I wasn't sure how to check if a block was empty so I added a flag to toggle the view between full and two column.

I am wondering if I need the blocks at all due to the structured nature of the content type.  thoughts?

2017-03-21 17:35 UTC, gleroux02 commented
@legostud a way that you can check if a block exists would be like:
```
% set _block = block('sidebar') %}
{% if _block is not empty %}
{{ _block|raw }}
{% endif %}
```
Now do we need to have them? I need to think a bit longer on that.

2017-03-21 17:48 UTC, gender404 commented
If I use that code, how to I add dummy content to the content type in Pattern Lab?  

I'm pretty sure sidebar would be considered empty and the content type would render full width instead of two columns.

2017-03-21 19:58 UTC, gleroux02 approved these changes

2017-03-21 20:03 UTC, merged