DP 2206 org page schema
massgov/mayflower-patternlab pull request #374
Opened 2017-03-17 14:41 UTC by jesconstantine

This PR implements schema.org for the org landing page and provides a hook for adding schema.org data objects to template and page patterns.

Ticket: https://jira.state.ma.us/browse/DP-2206

## To test:

- [ ] Pull down branch
- [ ] Build pattern lab
- [ ] Browse to /?p=pages-ORG-Health-Services
- Inspect the rendered markup, verify:
  - [ ] the `<script type="application/ld+json">` appears just before the `</main>` tag
  - [ ] the properties / values match the expected "Rendered json+ld data object" in the page pattern docs
- [ ] Copy the page pattern markup (inspect the page, grab the pattern `<html>` element from within the patter iframe
- [ ] Verify that you can see the properties picked up in google's [structured data testing tool](https://search.google.com/structured-data/testing-tool/u/0/) (see screenshots below)
- [ ] Verify that meta/schema && page docs are understandable, helpful for potential implementation

## Screenshots

### Google SDTT finds governmentOrganization object
![image](https://cloud.githubusercontent.com/assets/3279883/24049601/f3b2dae2-0b02-11e7-902d-3cd9286f555b.png)

### Google SDTT finds governmentOrganization properties + connects with "memberOf" global "Commonwealth" Organization
![image](https://cloud.githubusercontent.com/assets/3279883/24049674/1c0a5ac4-0b03-11e7-9f56-2ea28fd75591.png)

2017-03-17 21:22 UTC, gender404 requested changes
I'll review this on Monday, but I saw this and wanted to make a note.

2017-03-17 21:22 UTC, gender404 commented on styleguide/source/_patterns/04-templates/stacked-row-template.twig
> +  {% endblock %}
for consistency, can we move this after the `</main>` tag

2017-03-18 15:39 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/stacked-row-template.twig
> +  {% endblock %}
Yep, good catch.  Thanks.

2017-03-20 19:37 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/stacked-row-template.twig
> +  {% endblock %}
Addressed in: https://github.com/massgov/mayflower/pull/374/commits/a6b24d0e5e647f1c6227dc147352d3e60181e7a9

I actually moved them all inside of the `<main>` for consistency with how they would be implemented  elsewhere (IE Drupal or Wordpress)

2017-03-20 19:59 UTC, gender404 approved these changes

2017-03-20 22:35 UTC, gleroux02 approved these changes

2017-03-20 22:36 UTC, gleroux02 commented
@jesconstantine this looks good to me.

2017-03-21 10:38 UTC, merged