Release 3.6.0 - Sprint 15 work
massgov/mayflower-patternlab pull request #382
Opened 2017-03-29 11:19 UTC by jesconstantine

# Mayflower 3.6.0 Release Notes

## SUMMARY
If you'd like to read about these changes in JIRA:
* [DP-2114](https://jira.state.ma.us/browse/DP-2114) - [pattern lab] Service Page
* [DP-2181](https://jira.state.ma.us/browse/DP-2181) - Update Guide Page in Mayflower
* [DP-2206](https://jira.state.ma.us/browse/DP-2206) - Implement org page level structured data json+ld object in Mayflower 
* [DP-2569](https://jira.state.ma.us/browse/DP-2569) - Change header in Service page
* [DP-2471](https://jira.state.ma.us/browse/DP-2471) - Mayflower: guide section with all possible elements

## NEW FEATURES
- Ahem... introducing the latest page type to our family: Services! (Pages > Service Unemployment Benefits).  This is a great page type to use to help surface tons of information related to services, including: branding information, instructional videos, links to how-to's, location information listings, etc.
- We're making Org Landing Pages (Pages > Org Landing Page) more machine and search friendly by adding a Government Organization structured data pattern (Meta > Schema > Government Organization) to the bottom of the page markup. 
- For Mayflower implementers, we've created an example Guide page which shows all of the possible elements that can go into a Guide section (Pages > Guide Section Example)  

## IMPROVEMENTS
- We've revisited the guide page with some updates.  We've consolidated the formerly 3 guide pages into one shiny new guide page with just those components that our content friends have identified as being pertinent:
  - removed the testimony component
  - alerts links are now optional
  - section key agencies are now optional
  - the related guides show the guide card treatment as opposed to the related pages image thumbnail treatment.

Thanks for reading and if you have any feedback, questions, or suggestions, send an email to me.
 
~ Delivered with <3 from the MassIT Digital Services team

2017-03-29 13:13 UTC, isaacchansky requested changes

2017-03-29 13:13 UTC, isaacchansky commented on release-notes.md
> +### Pillar 1
This may be getting at a bigger problem we have w/ workflow, but is there a way to make these headings more descriptive? Frankly "Pillar 1" means nothing to me so I ignore it. 

I find the sections formatted like 3.0.0 (Sprint 9) super helpful though.

2017-03-29 13:33 UTC, jesconstantine commented on release-notes.md
> +### Pillar 1
Pillars were how some people were referring to the larger cross-functional teams that we are split up into.  The name of the board for all of the tickets under that heading is Cycle 3 - Pillar 1.

Should we be using the name of the cross functional team at all in the release notes?  If so, should we refer to them by a different name?  Like the short name of the team?  I think in this case, that would be Content Types and Groups.  (or something like that)

2017-03-29 15:59 UTC, isaacchansky commented on release-notes.md
> +### Pillar 1
Hm, idk - I think focusing on the type of work VS the team that did it is helpful for people trying to follow along who weren't part of the work. So, for example, questions I have on this release are:
- which of these are bugfixes 
- what is brand new work 
- what sections of the site (i.e guides, how-to pages, other components) have incremental changes 
- what tickets have breaking changes to existing things

2017-03-29 21:02 UTC, jeffmaher approved these changes
Release notes review: The notes look great and will be easy to pop into an email and a release tag upon delivery! Only suggestion is to remove the "Fixed" section.

2017-03-30 00:17 UTC, isaacchansky approved these changes

2017-03-30 11:00 UTC, jesconstantine commented
Merging this release after some good feedback and conversation in slack with @plusjeff and @isaacchansky -- thanks fellas!

2017-03-30 11:00 UTC, merged