DP-4053 Document developer build and deploy process
massgov/mayflower-patternlab pull request #501
Opened 2017-07-04 12:04 UTC by jesconstantine

This PR begins documentation for developer contribution and deployment.  It also updates the main readme and creates templates for issues and PRs.  Finally, it adds the Github Pages deploy script to the repo.

**JIRA ticket: **
https://jira.state.ma.us/browse/DP-4053

**Dependencies:**
In order for the deploy script to be meaningful, work in [DP-4046](https://jira.state.ma.us/browse/DP-4046) must be complete.

To test:
- [ ]  Read the repo readme and verify that it is clear where the documentation for contributing and deploying can be found
- [ ] Follow steps in CONTRIBUTING.md to verify that you can set up your Mayflower fork and local repo
- [ ] Follow steps in /docs/deploy.md to verify that you can deploy to your Mayflower fork Github Pages

2017-07-05 12:36 UTC, jesconstantine commented
@isaacchansky if you've got the time I'd love any feedback on the docs, but I'd especially love a quick code review of the deploy script: https://github.com/jesconstantine/mayflower/blob/8e3b38aa5fadd8924faf1d1627341f1bdefa7058/scripts/deploy-gh-pages.sh

We'll be testing it pretty heavily next sprint but just looking for a gut check as I'm pretty new to bash scripts. :)

2017-07-05 14:17 UTC, legostud commented
I feel we should be merging all of our work into a Release branch instead of dev to make sure it isn't blocking on going development.  Does that sound ok to you?

2017-07-05 14:54 UTC, isaacchansky requested changes
Overall looks really great, just a few comments

2017-07-05 14:54 UTC, isaacchansky commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Did you learn anything valuable in your work for this PR that you could share with the team?  You could list any relevant blogs, docs, or stack overflow posts that helped you with this work. -->
I like this 👍

2017-07-05 14:54 UTC, isaacchansky commented on CONTRIBUTING.md
> +## Spinning up a branch
Maybe re-title this to "creating a branch" to be consistent with git terminology for newbies

2017-07-05 14:54 UTC, isaacchansky commented on CONTRIBUTING.md
> +Now you can spin up your new branch:
spin -> create

2017-07-05 14:54 UTC, isaacchansky commented on CONTRIBUTING.md
> +1. Swap back to the browser and navigate to your Mayflower fork and (since you've recently pushed your branch up) you'll see that your new branch is listed at the top with a handy green "Compare & pu
I'm thinking we should avoid putting github UI specific things in here. If they change the UI at all this kinda becomes more confusing than helpful.

2017-07-05 14:54 UTC, isaacchansky commented on README.md
> +### Mayflower Artifacts
Might be helpful to add an explanation of what artifacts actually are and why we need this in the first place

2017-07-05 14:54 UTC, isaacchansky commented on scripts/deploy-gh-pages.sh
> +if [[ "$targetEnv" == "jesconstantine/mayflower" ]]; then
Maybe move this to be parameter-based instead of hardcoded.
something like an addition of `-cname stage-mayflower.digital.mass.gov`

2017-07-05 15:16 UTC, gender404 requested changes
I went through just the text portion of this PR.  I haven't actually tried the deploy script yet.  I'll do that in a bit.

2017-07-05 15:16 UTC, gender404 commented on CONTRIBUTING.md
> +1. Move into the styleguide directory `cd mayflower/styleguide`
The setup instructions are a built more complicated that this.  We have documentation for it already that can be included here or linked to.

2017-07-05 15:16 UTC, gender404 commented on CONTRIBUTING.md
> +Any new features and non-emergency bugfixes should branch from the `dev` branch.  Make sure you're on the `dev`  branch and that it's up-to-date with the source repo.
We should discuss which branch they should be using to create their feature branch off of.  Dev might not be clean enough to safely work with since it may not be stable.

2017-07-05 15:16 UTC, gender404 commented on CONTRIBUTING.md
> +If you just forked it, it always will be—but if there have been a lot of changes to the original repo since you forked it, yours might be out of sync. Here's how to get yours in sync:
'it always will be—but' This doesn't read well

2017-07-05 15:16 UTC, gender404 commented on CONTRIBUTING.md
> +1. Familiarize yourself with Mayflower:
I would make the first step a link to the Pattern Lab documentation.

2017-07-05 15:16 UTC, gender404 commented on CONTRIBUTING.md
> +## Committing your work
I'm not sure this part is needed.  In the Mayflower repo would should only have the PR commits and we've defined the format of those commits.  These commits could be useful if we find an issue in the future with the PR, but I'm not sure how useful.

2017-07-05 15:16 UTC, gender404 commented on CONTRIBUTING.md
> +In order to create a Pull Request (PR) where maintainers can review your work, you first need to push your branch to the origin remote (your Mayflower fork) and then press some buttons on GitHub.
"some buttons on Github" ??  we should try to be more specific or link to a Github page explaining how to create a PR.

2017-07-05 15:16 UTC, gender404 commented on CONTRIBUTING.md
> +# Contributing
I feel like this file is a bit flat.  I would like to see it grouped a bit more.  I see a few areas `##` to call out in more detail or link to other pages.  
1. Setting up a local environment
2. Writing code (Code Guidelines)
3. Submitting your code

Each of these could be it's own file.

2017-07-05 15:16 UTC, legostud commented on README.md
> +1. Install PHP ([v5.6.4](https://secure.php.net/get/php-5.6.4.tar.bz2/from/a/mirror))
this could part of a setting up an environment md file which would be referenced in Contribute.

2017-07-05 15:16 UTC, legostud commented on README.md
> +Mayflower is the enterprise design system for the Commonwealth of Massachusetts.
I would keep this document very high level with links to more detailed pages.  That will make it easier for them to quickly understand what Mayflower is and how to use it.

2017-07-05 15:16 UTC, legostud commented on docs/deploy.md
> +    - Where `-t` is the target remote repo (required): likely `<your-github-username>/mayflower`.  For example, the fork at [github.com/jesconstantine/mayflower](http://github.com/jesconstantine/mayf
I would avoid using your personal repo.  Can we use the massgov account as the example instead?

2017-07-05 15:18 UTC, legostud commented on CONTRIBUTING.md
> +Any new features and non-emergency bugfixes should branch from the `dev` branch.  Make sure you're on the `dev`  branch and that it's up-to-date with the source repo.
Maybe they should be branching off of Master instead

2017-07-06 11:59 UTC, jesconstantine commented on docs/deploy.md
> +    - Where `-t` is the target remote repo (required): likely `<your-github-username>/mayflower`.  For example, the fork at [github.com/jesconstantine/mayflower](http://github.com/jesconstantine/mayf
Good call, thanks.  Fixed in e3192f3881da1be1e45101415fb6635a3581e093

2017-07-06 12:01 UTC, jesconstantine commented on CONTRIBUTING.md
> +In order to create a Pull Request (PR) where maintainers can review your work, you first need to push your branch to the origin remote (your Mayflower fork) and then press some buttons on GitHub.
Do the more specific instructions (pending changes from @isaacchansky's comments about avoiding reference to github's UI) address the PR explanation?  I can just remove this verbiage.

2017-07-06 12:02 UTC, jesconstantine commented on CONTRIBUTING.md
> +## Committing your work
I understand your point about the PR commits, but I think it's still a good practice, especially for MassIT developers, so I'd like to keep it in.

2017-07-06 12:03 UTC, jesconstantine commented on CONTRIBUTING.md
> +Any new features and non-emergency bugfixes should branch from the `dev` branch.  Make sure you're on the `dev`  branch and that it's up-to-date with the source repo.
How do you feel about leaving as is for now and once we have mapped out the business process for contributing (next sprint) we'll adjust the documentation accordingly?

2017-07-06 12:04 UTC, jesconstantine commented on scripts/deploy-gh-pages.sh
> +if [[ "$targetEnv" == "jesconstantine/mayflower" ]]; then
Great idea!  Updated in 5ad608ebdf7740e7d0ed99606efc3f03e31e5a18 (I haven't tested the script after this addition yet, but I will)

2017-07-06 12:15 UTC, jesconstantine commented on CONTRIBUTING.md
> +1. Swap back to the browser and navigate to your Mayflower fork and (since you've recently pushed your branch up) you'll see that your new branch is listed at the top with a handy green "Compare & pu
Good call, fixed in 6a6263b592e7930f3c9ed80577a7ecc021909270

2017-07-06 12:17 UTC, jesconstantine commented on CONTRIBUTING.md
> +## Spinning up a branch
Good suggestion, fixed in 8662b1f8d80b72c9ef88946ebc58ea7bde1cc8fd

2017-07-06 12:17 UTC, jesconstantine commented on CONTRIBUTING.md
> +Now you can spin up your new branch:
Fixed in 8662b1f8d80b72c9ef88946ebc58ea7bde1cc8fd

2017-07-06 12:18 UTC, jesconstantine commented on CONTRIBUTING.md
> +1. Familiarize yourself with Mayflower:
Good suggestion, added in: c667e7f59b5efbd196f79d5a9086665792998a90

2017-07-06 12:30 UTC, jesconstantine commented on README.md
> +### Mayflower Artifacts
Good call.  How do the changes in 5fa898ad51304d94be3a8f73ecb3fc1a7e14c2b2 look?

2017-07-06 12:33 UTC, jesconstantine commented
@legostud @isaacchansky I updated the base, however I'm second guessing myself here.  I think most of the work we'll be doing should be kept in the C4 documentation integration branch, but I wonder if this kind of documentation, which doesn't affect any functionality, but only clarifies business + technical processes might not be useful sooner rather than later.  Thoughts?

2017-07-06 12:41 UTC, jesconstantine commented on CONTRIBUTING.md
> +If you just forked it, it always will be—but if there have been a lot of changes to the original repo since you forked it, yours might be out of sync. Here's how to get yours in sync:
Thanks, fixed in 232296fcf5c077b3519982f44994aad064c08897

2017-07-06 13:05 UTC, legostud commented on CONTRIBUTING.md
> +Any new features and non-emergency bugfixes should branch from the `dev` branch.  Make sure you're on the `dev`  branch and that it's up-to-date with the source repo.
that's fine.  I think we'll probably revisit a lot of this documentation again over this cycle.

2017-07-06 13:11 UTC, jesconstantine commented on README.md
> +1. Install PHP ([v5.6.4](https://secure.php.net/get/php-5.6.4.tar.bz2/from/a/mirror))
Thanks, I chunked some sections out into their own files, see 700b3b7fe8c183cb24672a76067710046a0a286c

2017-07-06 13:15 UTC, legostud commented on docs/deploy.md
> +    - Where `-t` is the target remote repo (required): likely `<your-github-username>/mayflower`.  For example, the fork at [github.com/jesconstantine/mayflower](http://github.com/jesconstantine/mayf
I think the main issue I have is that you are linking to your repo.  It's possible that you will eventually delete that repo and create a broken link here.  I agree with your statement though so how about we remove the 'For example ...' here, but leave the example below this line that uses your personal forked repo in the example.

2017-07-06 13:17 UTC, jesconstantine commented on README.md
> +Mayflower is the enterprise design system for the Commonwealth of Massachusetts.
Made some updates to keep this high level.  What do you think?  https://github.com/massgov/mayflower/pull/501/files#diff-04c6e90faac2675aa89e2176d2eec7d8

2017-07-06 13:20 UTC, jesconstantine commented on CONTRIBUTING.md
> +# Contributing
Thanks, I've added some grouping (see https://github.com/massgov/mayflower/pull/501/files#diff-8cc7b2b0d78dd2501610391c086a8516), but for now I think I want to keep what's left in this file.  I can certainly see us separating them into more files in a future sprint, though I'd like to get an idea of what works well for developers following the instructions as we test.  Sound good?

2017-07-06 13:24 UTC, jesconstantine commented on docs/deploy.md
> +    - Where `-t` is the target remote repo (required): likely `<your-github-username>/mayflower`.  For example, the fork at [github.com/jesconstantine/mayflower](http://github.com/jesconstantine/mayf
Ah, gotcha.  Fixed in 17c18f36d9663e5c468cb3d57337de81684bdb3f

2017-07-06 13:24 UTC, legostud commented
Just because we're doing the work in the C4 Documentation branch doesn't mean we can't merge it into a release branch.  If we feel the documentation is accurate we could do some cherry picking to make a release.

2017-07-06 13:27 UTC, jesconstantine commented on CONTRIBUTING.md
> +Any new features and non-emergency bugfixes should branch from the `dev` branch.  Make sure you're on the `dev`  branch and that it's up-to-date with the source repo.
^^ agreed.

2017-07-06 13:29 UTC, jesconstantine commented on CONTRIBUTING.md
> +1. Move into the styleguide directory `cd mayflower/styleguide`
Is everything for setup captured between the setting up your environment file (https://github.com/massgov/mayflower/pull/501/files#diff-a37ba21e2c82b3d0feaa1461beec7b75) and either the demo install file (https://github.com/massgov/mayflower/pull/501/files#diff-ecfc820ec14dcadd59b4ee8d36266836) or contributing docs (https://github.com/massgov/mayflower/pull/501/files#diff-8cc7b2b0d78dd2501610391c086a8516)?

2017-07-06 13:42 UTC, legostud commented on README.md
> +1. Check CircleCI builds for Mayflower project to see if there are any errors.
Mayflower Artifacts still feels a bit detailed, but I'm not sure how I would break this into a new file.  We could put a paragraph in here describing what Artifacts are (like the current stable version of Mayflower files) and then a link to how Mass.gov is using them as an example?

2017-07-06 13:43 UTC, legostud commented on README.md
> +1. Check CircleCI builds for Mayflower project to see if there are any errors.
Overall, I really like the format of this file now.

2017-07-06 13:44 UTC, jesconstantine commented on README.md
> +1. Check CircleCI builds for Mayflower project to see if there are any errors.
Maybe once we've got some docs in the massgov/mass repo we can link to that file from this section in the mayflower readme after a paragraph describing what they are?

2017-07-06 13:59 UTC, legostud commented on README.md
> +1. Check CircleCI builds for Mayflower project to see if there are any errors.
that sounds like a great idea.

2017-07-10 19:39 UTC, isaacchansky commented on scripts/deploy-gh-pages.sh
> +        line="Please include a cname value for production deployments.  Execute the script again with a value for [-cname] i.e. 'mayflower.digital.mass.gov'."
I think the suggested flag here should be `-c` rather than `-cname`

2017-07-10 19:42 UTC, isaacchansky commented on scripts/deploy-gh-pages.sh
> +    assetsPath="assets\""
This doesn't let you both customize the assets path and a cname value.

I have my isaacchansky.github.io aliased to isaacchansky.com, so to deploy to my branch I'd have to both pass a cname value, and set the asset path to `mayflower/assets`. Not sure if we want to cater to that scenario, but wanted to point it out.

2017-07-10 20:22 UTC, jesconstantine commented on scripts/deploy-gh-pages.sh
> +        line="Please include a cname value for production deployments.  Execute the script again with a value for [-cname] i.e. 'mayflower.digital.mass.gov'."
@isaacchansky the flag passed to the script is actually `-c` I just assign the arg value to `cname` in the script as a variable.  Is that what you mean?

2017-07-10 20:24 UTC, jesconstantine commented on scripts/deploy-gh-pages.sh
> +    assetsPath="assets\""
Good call.  I was definitely working under an assumption that devs would deploy to *.github.io/mayflower and not a personal custom cname.  Seems like that's a poor assumption though, right?

2017-07-11 11:01 UTC, jesconstantine commented on scripts/deploy-gh-pages.sh
> +    assetsPath="assets\""
@isaacchansky can you see if updates in https://github.com/massgov/mayflower/pull/501/commits/f0db75064dbb4f21abb7dac4f8b3e9227a48be24 work for you?  You can now optionally pass flag `-a` with an assetsPath

2017-07-11 13:29 UTC, isaacchansky commented on scripts/deploy-gh-pages.sh
> +        line="Please include a cname value for production deployments.  Execute the script again with a value for [-cname] i.e. 'mayflower.digital.mass.gov'."
I was referring to this line in specific "Execute the script again with a value for [-cname] i.e. 'mayflower.digital.mass.gov'.", I saw this and tried to use -cname as a flag :P 
It would make more sense to me to say:

> Execute the script again with a value for [-c] i.e. 'mayflower.digital.mass.gov'.

2017-07-11 18:11 UTC, jesconstantine commented on scripts/deploy-gh-pages.sh
> +        line="Please include a cname value for production deployments.  Execute the script again with a value for [-cname] i.e. 'mayflower.digital.mass.gov'."
oh thank you, i missed that one!  i'll update that right now.

2017-07-11 18:31 UTC, jesconstantine commented on scripts/deploy-gh-pages.sh
> +        line="Please include a cname value for production deployments.  Execute the script again with a value for [-cname] i.e. 'mayflower.digital.mass.gov'."
Updated in https://github.com/massgov/mayflower/pull/501/commits/58beead8b04543759a3395d9cf86a6ec3deb69a7 thanks again :)

2017-07-12 19:45 UTC, isaacchansky commented on scripts/deploy-gh-pages.sh
> +
@jesconstantine why's this all commented out? (should I be reviewing now? if not I can back off! haha)

2017-07-12 19:53 UTC, isaacchansky commented on scripts/deploy-gh-pages.sh
> +
(with this uncommented it works great 👍 )

2017-07-12 20:04 UTC, jesconstantine commented on scripts/deploy-gh-pages.sh
> +
Shoot because I comment it out to get the script to pause so I could check the lines above (had to commit in order to test the script) and never uncommented!  I'll do that now.  Thanks!

2017-07-18 11:30 UTC, jesconstantine commented on README.md
> +1. Check CircleCI builds for Mayflower project to see if there are any errors.
Done: https://github.com/massgov/mayflower/pull/501/commits/cef2d8b478e42d8e18d37ca39184d8848f42000e

2017-07-18 16:21 UTC, jesconstantine commented on .github/CONTRIBUTING.md
> +### Creating a Pull Request
Describe labels for identifying types of changes patch / minor / major

2017-07-18 16:21 UTC, jesconstantine commented on .github/CONTRIBUTING.md
> +### Creating a Pull Request
Link to description of github labels in versioning document

2017-07-19 12:57 UTC, yriahi reviewed
Thanks @jesconstantine 
I apologize if I have been over-externally-reviewing this; and for the amount of comments :-).

2017-07-19 12:57 UTC, yriahi commented on scripts/deploy-gh-pages.sh
> +function cleanup {
As a possible future enhancement and for a more contained working directory where the script performs its operartions,  I suggest stamping the mayflower temp directory such that at the beginning of the script e.g. `/tmp/mayflower_09123801` is created and stored in a variable. At the end of the script run a "clean up" function that removes the the stamped temp directory created above.

2017-07-19 12:57 UTC, yriahi commented on .github/CONTRIBUTING.md
> +Right now, you have a fork of the Mayflower repository, but you don't have the files in that repository on your computer. Let's create a clone of your fork locally on your computer.
I suggest to add the command to clone here since it is not an elaborate or complex procedure that needs its own page or documentation.
e.g. `git clone https://github.com/<your-github-username>/mayflower-2`

2017-07-19 12:57 UTC, yriahi commented on .github/CONTRIBUTING.md
> +If you check your remotes (`git remote -v`), you can now see that you have two "remotes" that your local repo is pointed towards: `origin`, which points to *your* Mayflower fork, and `upstream`, whic
Please add a small note about the conventional name `upstream` that this is what is generally used, preferred or as best practice.

2017-07-19 12:57 UTC, yriahi commented on .github/CONTRIBUTING.md
> +Any new features and non-emergency bugfixes should branch from the `dev` branch.  Make sure you're on the `dev`  branch and that it's up-to-date with the source repo.
I apologize for being little picky here. At some point, I would like to see us name this `develop`
:-) my zshell aliase `gcd` does not work :-(

2017-07-19 12:57 UTC, yriahi commented on .github/CONTRIBUTING.md
> +### Creating a Pull Request
Also, Github labels: `quick fix`, `internal review` and `external review`. Please ignore, if this is not the right place for this comment.

2017-07-19 12:57 UTC, yriahi commented on .github/CONTRIBUTING.md
> +Once your work is complete, deploy your branch to your Mayflower fork's Github Pages, so that its functionality can be tested and reviewed by someone who doesn't have Mayflower running locally.  See
`[our deployment docs]` link is broken :-(

2017-07-19 12:57 UTC, yriahi commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Please use TICKET Description of ticket as PR title (i.e. DP-1234 Add back-to link on Announcement template)  -->
I noticed that the PR body pre-fill with this tempalte is not taking place. Does that have anything to do my testing branch coming from a fork into main mayflower dev branch?

2017-07-19 12:57 UTC, yriahi commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Please use TICKET Description of ticket as PR title (i.e. DP-1234 Add back-to link on Announcement template)  -->
I think we should have a `.github` directory in the root with the content of this PR tempalte

2017-07-19 12:57 UTC, yriahi commented on .github/ISSUE_TEMPLATE.md
> +### Description:
I also saw that the issue template is not take populating the body of a new test issue that I tried to create. 
Similar to the PR template below, issue template markdown may need to live in the same directory as the PR template markdown `.github`

2017-07-19 13:07 UTC, jesconstantine commented on scripts/deploy-gh-pages.sh
> +function cleanup {
@yriahi this is a great idea!  will definitely keep it in mind for v2 :)

2017-07-19 13:09 UTC, jesconstantine commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Please use TICKET Description of ticket as PR title (i.e. DP-1234 Add back-to link on Announcement template)  -->
This PR adds that directory and template.  So once this PR makes its way into master then I think you'll see the PR template.

2017-07-19 13:10 UTC, jesconstantine commented on .github/ISSUE_TEMPLATE.md
> +### Description:
Same thing here - I think they'll be added once the changes from this PR make their way into master.

2017-07-21 11:52 UTC, jesconstantine commented on .github/CONTRIBUTING.md
> +Right now, you have a fork of the Mayflower repository, but you don't have the files in that repository on your computer. Let's create a clone of your fork locally on your computer.
Added in https://github.com/massgov/mayflower/pull/501/commits/4d7c86d0cfe5538da84fee88d0c4f56b480df851

2017-07-21 17:24 UTC, yriahi commented
Looks goods @jesconstantine 👍

2017-07-21 17:26 UTC, merged