DP-4080 - Versioning Documentation
massgov/mayflower-patternlab pull request #504
Opened 2017-07-06 21:14 UTC by legostud

https://jira.state.ma.us/browse/DP-4080

Describing how Versioning works within Mayflower.

2017-07-07 14:06 UTC, jesconstantine commented on docs/versioning.md
> +4. Adding new variables to a pattern's data object (.json or .twig).
Are there ways to do this that are cause for both Minor and Major versions?

For example, would conditional / non-required new variables be considered Minor and required new variables be considered Major?

2017-07-07 15:45 UTC, legostud commented on docs/versioning.md
> +4. Adding new variables to a pattern's data object (.json or .twig).
Well, adding new variables to the data object will always be fine.  It's the implementation of those variables in the markup that could cause a breaking change.

2017-07-07 21:26 UTC, legostud commented
I pushed a second draft

2017-07-10 20:00 UTC, isaacchansky requested changes

2017-07-10 20:00 UTC, isaacchansky commented on docs/versioning.md
> +4. Data Oject - The json data used for a pattern
*Object

2017-07-10 20:00 UTC, isaacchansky commented on docs/versioning.md
> +Patch versions will require an update the CSS or JS files.  In order to get all of the fixes, you may have to update your markup to match Mayflower's, but a patch will always work with older markup f
>"you may have to update your markup to match Mayflower's, but a patch will always work with older markup from the same minor release" 

This seems a little contradictory at first glance - is it equivalent to say "a patch will never visually break code using existing markup from the same minor release"?

2017-07-10 20:00 UTC, isaacchansky commented on docs/versioning.md
> +The Mayflower Style Library is using Semantic Versioning to help maintain dependencies with consumers of the patterns contained within.  This method will help convey what will be required to upgrade
*Mayflower

2017-07-10 20:00 UTC, isaacchansky commented on docs/versioning.md
> +Versions on Mayflower are denoted in by three values 1.0.0 that represent Major, Minor, and Patch changes respectively.  Major changes can contain Minor changes which can contain Patch changes.  When
*Versions of Mayflower are denoted by...

2017-07-14 10:48 UTC, jesconstantine commented on docs/versioning.md
> +Patch versions will require an update the CSS or JS files.  In order to get all of the fixes, you may have to update your markup to match Mayflower's, but a patch will always work with older markup f
I think that's also worth an example with version numbers.  We want this document to be as clear and understandable as possible, in order to mitigate any version / update implementation risk.

2017-07-18 16:22 UTC, plusjeff commented on docs/versioning.md
> +*- Pages are there as examples to show different ways to combining patterns.*
Suggestion:

Mayflower patch and minor versions will not introduce changes to markup, CSS, JS, and Data Object APIs/contract. Patches releases existing functionality that is broken. Minor releases add new functionality, without modifying the contract of the existing features. Consumers can safely upgrade to newer patch and minor versions without having to a thorough regression test of their code.

Major versions can change anything. It's expected that consumers upgrading to a major version need to retest areas of their code that utilize Mayflower.

2017-07-19 10:35 UTC, jesconstantine commented on docs/versioning.md
> +*- Pages are there as examples to show different ways to combining patterns.*
RE: minor versions, I also like what @isaacchansky was saying about the open / close principle: patterns are open for extension but closed for modification.  So a markup change that extends current functionality but doesn't modify it would be okay.

For example if we wanted to introduce the practice of using `data-attr` vs `.js-class` for js hooks in markup, then the minor version way of doing it would be to release code wth both `data-attr` and `.js-class` in the markup while the major way of doing it would be to replace `.js-class` with `data-attr`

@plusjeff how does that resonate with your comment above that minor versions will not introduce changes to markup (and even css / js in other examples)

@legostud how does this relate to how you've been thinking about and drafting minor versions?

2017-07-19 14:08 UTC, plusjeff commented on docs/versioning.md
> +*- Pages are there as examples to show different ways to combining patterns.*
@jesconstantine That sounds great!

2017-07-19 18:14 UTC, legostud commented on docs/versioning.md
> +*- Pages are there as examples to show different ways to combining patterns.*
As a little insight, which I'll add to the contract, is that my assumption is that the consumer will always being pulling in the latest JS and CSS bundles with each release.  Possibly doing this from a CDN that provides a version for each Major release.  This way the only 'changes' the consumer will have to do is updated markup or upgrade everything to a new Major release.

2017-07-20 20:34 UTC, legostud commented
new version uploaded for review.  I need to find better examples of Patch releases now, because the one I used isn't valid anymore.

2017-07-21 10:01 UTC, jesconstantine commented on docs/versioning.md
> +* Artifacts - The SVG icons, fonts, CSS, and JavaScript files
What do you think about using Assets or even Static Assets here?

2017-07-21 10:05 UTC, jesconstantine commented on docs/versioning.md
> +A Minor version is created when new features are added to an existing Pattern, a new Pattern is created, or an issue has been resolved that required Markup changes. New features will always be writte
I think 

> an issue has been resolved that required Markup changes

needs to be called out in the "Our Contract with the consumer" section:

> *Minor:* consumer doesn't need to re-write any Markup, has access to new features available, maybe an option to do something a better way, nothing breaks just by updating

Maybe:

> *Minor:* consumer only needs to re-write Markup in order to fix a broken pattern, has access to new features available, maybe an option to do something a better way, nothing breaks just by updating

Thoughts?

2017-07-21 10:07 UTC, jesconstantine commented on docs/versioning.md
> +A Major version is created when the new code requires changes to the Markup or Data Object to prevent breaking existing styling or functionality.
Can you clarify

> ... to prevent breaking existing styling or functionality

2017-07-21 12:47 UTC, legostud commented on docs/versioning.md
> +A Minor version is created when new features are added to an existing Pattern, a new Pattern is created, or an issue has been resolved that required Markup changes. New features will always be writte
I think I want to say "doesn't need to re-write any Markup unless specifically stated in the release notes, ...".   The expectation is that for the majority of Minor releases they shouldn't have to re-write any Markup.

Thoughts?

2017-07-21 12:49 UTC, legostud commented on docs/versioning.md
> +A Major version is created when the new code requires changes to the Markup or Data Object to prevent breaking existing styling or functionality.
yes, it means your site will break.  Maybe I change it to state that and then add another sentence describing what "break" could mean.

2017-07-21 13:00 UTC, jesconstantine commented on docs/versioning.md
> +A Minor version is created when new features are added to an existing Pattern, a new Pattern is created, or an issue has been resolved that required Markup changes. New features will always be writte
That works for me!

2017-07-21 14:44 UTC, legostud commented on docs/versioning.md
> +* Artifacts - The SVG icons, fonts, CSS, and JavaScript files
Assets works for me.

2017-07-21 14:45 UTC, legostud commented on docs/versioning.md
> +A Major version is created when the new code requires changes to the Markup or Data Object to prevent breaking existing styling or functionality.
I changed this to "A Major version is created when the new code will break existing code unless updates are made to the Markup or Data Object."

2017-07-21 18:54 UTC, jesconstantine approved these changes
Nice work here @legostud !!

2017-07-21 19:42 UTC, legostud commented
@plusjeff - any comments?

@isaacchansky - did I fix the changes requested and does this work for you?

2017-07-24 13:45 UTC, plusjeff commented
@legostud : This looks great! Thanks for writing up!

2017-07-26 17:52 UTC, merged