DP-3232 Key actions showing multiple times throughout page
massgov/mayflower-patternlab pull request #518
Opened 2017-07-24 19:25 UTC by mrossi113

For accessibility reasons added an aria-labelledby to the key actions section and used the compHeading.id to identify each of the key actions section. 

JIRA ticket: https://jira.state.ma.us/browse/DP-3232

The key actions are being used both on the Guide (harden-content type) and the Stacked Layout (prototype - current homepage) at the moment. Used the compHeading.id instead of compHeading.title not to duplicate the key action title.

2017-07-24 20:22 UTC, gender404 requested changes
This ticket leans towards some improvements that I was hoping to do.  Maybe this change could be incorporated as part of this fix.

What I'd like to do is retire the Sidebar Heading, by adding a 'sidebar' variable to the Comp Heading that when set to true would render the Comp Heading as a sidebar.  This variable would add a modifier class (ma__comp-heading--sidebar) to the Comp Heading.  The scss would be updated to the following:
~~~
.ma__comp-heading {

  &:not(&--sidebar) {
    @include ma-comp-heading;
  }

  &--sidebar,
  .sidebar & {
    @include ma-sidebar-heading;
  }

  &--centered {
    text-align: center;

    &:after {
      left: 50%;
      transform: translateX(-50%);
    }
  }

  .sidebar--colored & {
    @include ma-heading-colored($direction: left);
    border-bottom: none;

    &:after {
      display: block;
    }
  }
}
~~~

2017-07-24 20:22 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/key-actions.twig
> +    <div class="ma__key-actions__items" aria-labelledby="{{compHeading.id}}">
if compHeading is set to null and a sidebarHeading is used instead this will fail.

2017-07-24 20:22 UTC, legostud commented on styleguide/source/_patterns/01-atoms/04-headings/sidebar-heading.twig
> +<h3 class="ma__sidebar-heading" aria-labelledby="{{compHeading.id}}">{{sidebarHeading.title}}</h3>
You should never ever reference variables from another namespace (compHeading vs sidebarHeading).  If I was to include a pattern with a Comp Heading containing an ID every Sidebar Heading would inherit that same value. 
 And IDs are not allowed to be duplicated on a page.

To solve this you should add an 'id' value to the sidebarHeading which defaults to null.  

CC: @jesconstantine

2017-07-26 17:51 UTC, legostud commented on styleguide/source/assets/scss/01-atoms/_comp-heading.scss
> -    &:after {
I think the &:after is still going to be needed, but can be moved to within the `&--sidebar, .sidebar & {` selector.

2017-08-02 19:45 UTC, mrossi113 commented on styleguide/source/assets/scss/01-atoms/_comp-heading.scss
> -    &:after {
@legostud moved the `&after` within the `&--sidebar, .sidebar & {` which works fine in the http://localhost:3000/?p=atoms-comp-heading. But the http://localhost:3000/?p=atoms-comp-heading-centered `&after` is left align now in this twig. I tried a few things, but it won't position the bar correctly in the center. Not sure what to do with this?

2017-08-03 15:24 UTC, legostud commented on styleguide/source/assets/scss/01-atoms/_comp-heading.scss
> -    &:after {
There were two &:after { ... } blocks and you had the one for centering inside the .sidebar.  I moved that, but it still didn't work due to the :not() adding more specificity so I fixed that as well and it should be centering now.

2017-08-03 15:28 UTC, legostud commented
I found a few other issues in there when I was working on this.  

1. If the sidebar variable was set to true, two headings were being rendered.  
2. The new sidebar variable wasn't added to the compHeading.json file which is the source of truth for which variables are used.
3. The compHeading.md file wasn't updated with the new variable
4. A variant compHeading~as-sidebar-heading.json wasn't created.

I pushed a fix to correct those.

Do this code still meet your requirements?

2017-08-03 15:40 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/key-actions.twig
> +    <div class="ma__key-actions__items" aria-labelledby="">
I'm pretty sure this should be populated.

2017-08-03 15:41 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/key-actions.twig
> +    <div class="ma__key-actions__items" aria-labelledby="">
I updated this to use keyActions.compHeading.id

2017-08-03 17:08 UTC, mrossi113 commented
@legostud Yes, the code changes you made meets all of the requirements for both of the JIRA tickets. Thank you!

2017-08-07 15:12 UTC, merged