DP-4181 define process for Mayflower contributions
massgov/mayflower-patternlab pull request #525
Opened 2017-07-30 12:15 UTC by jesconstantine

This PR updates the contributing documentation to include the a broader range of contributions (bug reports, feature requests, pull requests).  It also proposes issue labels and updates the issue template which corresponds to language in the contributing docs.

2017-07-31 17:38 UTC, isaacchansky requested changes

2017-07-31 17:38 UTC, isaacchansky commented on .github/CONTRIBUTING.md
> +
I'm curious on the utility of this section. I've never had a bug report that was caused by a browser not also result in a workaround to be implemented since regardless of the reason for the bug, it's something not right on our site.

2017-07-31 17:38 UTC, isaacchansky commented on .github/CONTRIBUTING.md
> +- `gulp` - Issues with our build system, which is used to run all our tests, concatenate and compile source files, and more.
Maybe rename this to 'build' ? that way it applies to build/tooling in general.

2017-07-31 18:18 UTC, jesconstantine commented on .github/CONTRIBUTING.md
> +
Fair enough, also likely overkill for now.  I'll remove it. :)

2017-08-02 13:39 UTC, jesconstantine commented
Close in favor of #532 (re-roll)

2017-08-02 13:39 UTC, closed without merging

2017-08-02 13:40 UTC, jesconstantine commented on .github/CONTRIBUTING.md
> +- `gulp` - Issues with our build system, which is used to run all our tests, concatenate and compile source files, and more.
Updated in re-rolled PR: https://github.com/massgov/mayflower/pull/532/commits/b163a40898518052ee9f54d6eb1e3eb75bbe13d7

2017-08-02 13:40 UTC, jesconstantine commented on .github/CONTRIBUTING.md
> +
Removed in re-rolled PR: https://github.com/massgov/mayflower/pull/532/commits/d3956a62d1ac943b7accb465989a2527e378b83b