DP-4178 topic page
massgov/mayflower-patternlab pull request #529
Opened 2017-08-01 18:32 UTC by legostud

This PR provides documentation for every pattern used on the Location Page that hasn't already be documented:
http://mayflower.digital.mass.gov/?p=pages-topic
http://mayflower.digital.mass.gov/?p=pages-topic-your-government

NOTE: This PR includes the changes found in https://github.com/massgov/mayflower/pull/521, https://github.com/massgov/mayflower/pull/523, https://github.com/massgov/mayflower/pull/524, and https://github.com/massgov/mayflower/pull/527 so please merge those PRs first.

Jira:
https://jira.state.ma.us/browse/DP-4178
https://jira.state.ma.us/browse/DP-4177

Documentation was added to these patterns (with some twig changes):
Topic Page
* Single Column Template
* Section Three Up
* Link List

2017-08-13 12:07 UTC, jesconstantine requested changes
Great work, once again, @legostud .  A few notes based on changes that we've been making based on your prior work, some questions for my own learning, and some food for thought...  Thanks!

2017-08-13 12:07 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/single-column.md
> +* Emergency Alerts
Let's add the line about Twig Blocks (similar to https://github.com/massgov/mayflower/pull/527/files#diff-9a4ea54dbd98f96d766b9af9ff39b32e) here

2017-08-13 12:07 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-author/sections-three-up.md
> +* Comp Heading
Are we missing Section Links here?

2017-08-13 12:07 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-author/sections-three-up.md
> +This patten shows a grid of Section Link Patterns.
Curious about the name for Sections Three Up and Section Links.  Is it because when we created these patterns we were using "Section Landing Pages? and the concept of a Section was a thing?  I'd like to consider renaming these.  What do you think?

2017-08-13 12:07 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/section-links-with-callout-links.md
> +* set the "sectionLinks.type" variable to "callout"
Does it make sense / is it feasible to make this a property of each link as opposed to the whole molecule?  Or would we only ever want all links or all callouts?

2017-08-13 12:07 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/section-links.md
> -title: Section links
See earlier comment about renaming this pattern.  I'm not sure exactly what - seems like we have callouts, callout grids, cards, card grids...

2017-08-13 12:07 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/section-links.md
> +* This pattern uses JavaScript for the accordions (js/modules/accordions.js)
Is this mobile-only functionality?  Is it worth noting that hear?  I know we haven't really been adding any viewport specific language up to this point...

2017-08-13 12:07 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/section-links.md
> +    type: decorativeLink and calloutLink / required
Should "and" be "or" here?  And maybe it's intuitive enough, but `calloutLink` should only be used when `sectionLinks.type` = `callout` right?

2017-08-13 12:07 UTC, jesconstantine commented on styleguide/source/_patterns/01-atoms/05-icons/cat-icon.md
> -title: Category Icon
Just so it's crystal clear that this is not actually an icon of a cat 🐱, maybe we should call this category-icon.

2017-08-13 12:07 UTC, jesconstantine commented on styleguide/source/_patterns/01-atoms/05-icons/cat-icon.twig
> +<figure class="ma__category-icon {{catIcon.small == "true" ? 'ma__category-icon--small' : ''}}" aria-hidden>
Can you help me understand the benefit of exposing the `figure` to screenreaders when the contents are only a hidden `svg` and we don't have any `figcaption` or other helpful text?

2017-08-13 12:07 UTC, jesconstantine commented on styleguide/source/_patterns/01-atoms/05-icons/readme.md
> +# SVG Icons
💯 thank you!

2017-08-13 12:07 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/single-column.twig
> +{% block header %}
Let's make sure we track this change for Drupal implementers...

2017-08-14 15:55 UTC, legostud commented on styleguide/source/_patterns/02-molecules/section-links-with-callout-links.md
> +* set the "sectionLinks.type" variable to "callout"
It's supposed to be all of one type.  There some business logic around this that I don't quite remember, but it was based on the type of page that the Section Link represented.

2017-08-14 16:03 UTC, legostud commented on styleguide/source/_patterns/01-atoms/05-icons/cat-icon.twig
> +<figure class="ma__category-icon {{catIcon.small == "true" ? 'ma__category-icon--small' : ''}}" aria-hidden>
that's why I added the `aria-hidden` attribute to hide the `figure` from screen readers. I don't feel that the icon is adding value for screen readers.

2017-08-14 20:07 UTC, legostud commented
Change have been made.  Let me know if you see anything else.

2017-08-15 17:36 UTC, jesconstantine reviewed
Thanks @legostud I think there's just one question / comment left: https://github.com/massgov/mayflower/pull/529/files#r132839306

But we're getting soooo close :)

2017-08-15 17:36 UTC, jesconstantine commented on styleguide/source/_patterns/01-atoms/05-icons/cat-icon.twig
> +<figure class="ma__category-icon {{catIcon.small == "true" ? 'ma__category-icon--small' : ''}}" aria-hidden>
Oh jeez.  I must've been tired when I reviewed this - I definitely thought you were removing it.  Ha.  😫

2017-08-15 17:36 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-author/sections-three-up.md
> +This patten shows a grid of Section Link Patterns.
Comment added to pattern inventory google sheet. 🎉

2017-08-15 18:37 UTC, legostud commented on styleguide/source/_patterns/02-molecules/section-links.md
> +    type: decorativeLink and calloutLink / required
I think I'll just take out the confusion altogether.  Both patterns use the same Data Object format so I'll just put the variables in here instead to make it easier to understand.

2017-08-15 18:38 UTC, legostud commented
This should be fine now.

2017-08-18 11:57 UTC, jesconstantine approved these changes

2017-08-18 12:41 UTC, merged