DP-4198: Changes a tag to div to fix google translate.
massgov/mayflower-patternlab pull request #534
Opened 2017-08-02 15:35 UTC by smurrayatwork

**Description:** 

This pull request changes the anchor tags used to contain the markup within callout-link.twg to be a div instead. Without this change, google translate ends up duplicating the for every callout link on the homepage, breaking the Featured Actions section.

Making this change is also more consistent with other links that are rendered on the page that use divs.

**Jira:** 
https://jira.state.ma.us/browse/DP-4198

**To Test:**
- [ ] Go to the homepage and scroll down to the Featured Actions section. Verify that the Featured Actions section renders properly.
- [ ] Scroll back up and use the dropdown labeled "Select Language" to choose any other language than English. Scroll back down to the Featured Actions section and verify that the Featured Actions section is still rendered properly.

**Post Deploy Steps:**
N/A

**Relevant Screenshots/GIFs:**
N/A

**Additional Notes:**
N/A
---

2017-08-02 16:13 UTC, gender404 requested changes
This is broken.

1. The SVG arrow icon is no longer part of the link
2. The Icon wraps to a new line (orphans) for longer text (I'm assuming this based on the code)
3. You've pretty much reverted the changes made for DP-1521

Also since the Callout Link is pretty much the same structure as a Decorative Link, do we have a problem with Decorative Links on the site as well.

![image](https://user-images.githubusercontent.com/1462168/28883446-7da6207a-777c-11e7-87be-162fc47e9a04.png)

2017-08-03 15:18 UTC, isaacchansky commented
As for point 3 above while it might change the markup back to what it was like, the issue before was JS hi-jacking the anchor tag, so if this acts just as a normal anchor I think we're good.

2017-08-03 15:20 UTC, smurrayatwork commented
@legostud I've put the svg arrow back into the anchor tag. Does this address your concerns, here? If not, let me know. Thanks!

2017-08-03 17:28 UTC, legostud commented
@smurrayatwork - that doesn't appear to have fixed the issue with the arrows (see below).  Also now the entire box isn't clickable although the mouse pointer still says it is.

It does appear that you've found a bug with the arrows wrapping to a new line too early.  This doesn't appear to be happening in Prod, but I can see it in Dev.  Apparently the new hidden info span tag between the arrow and the text was adding extra white space causing the arrow to wrap.

I think a better approach to this is to wrap the a tag in a div.  

![image](https://user-images.githubusercontent.com/1462168/28931229-60c1c1f4-7843-11e7-80d6-7919a8ebf6ee.png)

2017-08-03 17:33 UTC, legostud commented
See new PR to include those changes => https://github.com/massgov/mayflower/pull/535

2017-08-03 19:07 UTC, gender404 approved these changes

2017-08-07 15:11 UTC, merged