add headerTags to pageBanner
massgov/mayflower-patternlab pull request #539
Opened 2017-08-07 18:18 UTC by labbydev

Include the headerTags as options to the pageBanner

Updated patterns:
* http://localhost:3000/?p=organisms-page-banner

2017-08-07 19:23 UTC, gender404 requested changes
I think the overall request here is incorrect.  The ticket shouldn't be to added header tags to the Page Banner,  It should be to add them to the site Header instead since they can exist on any page regardless of which Page Header/Banner used.

I would suggest creating a new 'Page Navigation' Pattern (or some other name) by spinning off the the code used in the Page Header for these tags and Social Links.

Doing it this way will allow header tags on any page.  It will also allow us to place the header tags outside of the #main element making it possible for screen readers to skip these links as well when they click 'skip navigation'

2017-08-07 19:23 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-template/page-banner.twig
> +  <div class="ma__page-banner__tags">
This is an anti-pattern since you can't have a child `ma__page-banner__tags` element located outside of a parent element `ma__page-banner`.

2017-08-07 19:28 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_page-banner.scss
> +  &__tags {
I think you forgot to also create the 'theme' version (colors, and font-weights) of this code.

2017-08-08 12:40 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-template/page-banner.twig
> +  <div class="ma__page-banner__tags">
I would suggest moving this conditional block inside of the parent component `section.ma__page-banner` similar to how we see [@molecules/header-tags included on @organisms/by-template/page-header](https://github.com/massgov/mayflower/blob/master/styleguide/source/_patterns/03-organisms/by-template/page-header.twig#L6).  What do you think @labbydev @legostud ?

2017-08-08 12:46 UTC, jesconstantine commented
@legostud @gleroux02 let's talk about the architecture needed for this ticket and what is proposed in Jonathan's review comment so we can provide a path forward for @labbydev 

It seemed logical to me to add the `@molecules/header-tags` as a child pattern to whichever `@organism` was responsible for rendering the page title and other "pre-content" of the page, which would mean adding it to `@organisms/by-template/page-banner` `@organisms/by-template/illustrated-header` as it already exists on `@organisms/by-template/page-header`.  

The reason why it seemed logical to me is because in order to render, this pattern needs page-level data (i.e. relationship information--not hierarchical) and not site-level data.

What do people think?

2017-08-08 13:17 UTC, legostud commented
if it needs page-level data, then it might not be best to add it to the header.  I would then suggest we make it a stand alone Pattern that can be placed at the top of the page above the various Page Headers/Banners.  Similar to how we were doing breadcrumbs.

2017-08-08 13:18 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-template/page-banner.twig
> +  <div class="ma__page-banner__tags">
It can't be added there, because the background image is applied to the parent class so we would have to do a lot more work to tweak the Page Banner.  I think making it a stand alone pattern placed above the Page Banner would be a better approach.

2017-08-08 13:20 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-template/page-banner.twig
> +  <div class="ma__page-banner__tags">
Good call @legostud that makes sense to me.

2017-08-09 19:30 UTC, gender404 requested changes
There is an overall issue with this new Pattern, you have used the same name for this pattern as an existing Pattern (header-tags) that is not allowed except for pages.

Simplest solution is to rename this Pattern, but I could also see us renaming the molecule to Relationship Links.

2017-08-09 19:30 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-template/header-tags.json
> +}
Channeling Greg here, you're missing the extra line ending on your new files.

2017-08-09 19:30 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-template/header-tags.json
> +  "headerTags": {
The data object for all Patterns in Mayflower, excluding pages and templates, should be contained in a single object that matches the files name.  This of course means your going to have { headerTags: { headerTags: { } } } which tells me this new pattern is named incorrectly.

Example: sample-pattern.json
~~~
{
  samplePattern {
    headerTags { ... }
    socialLinks { ... }
  }
}
~~~

2017-08-09 19:30 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-template/header-tags.twig
> +  <div class="ma__header-tags__container">
Incorrect BEM syntax used here.  I see a child class that isn't within a parent class.

2017-08-09 19:30 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_header-tags.scss
> +.ma__header-tags__container {
Something is obviously wrong if the outer wrapper is a child class.  Also since this pattern is called header-tags, the parent class should be .ma__header-tags { ... }.  Filename determines the class name to keep everything in sync and help avoid having multiple patterns using to same parent class.

Using .ma__header-tags isn't possible here since we are already using that elsewhere.

2017-08-09 19:30 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_header-tags.scss
> +  clear: both;
I don't think we'll need the clear both here.

2017-08-09 19:30 UTC, legostud commented on styleguide/source/assets/scss/index.scss
> +@import "03-organisms/header-tags";
I'm pretty sure there are theme SCSS styles (border-color) for this pattern.

2017-08-09 19:56 UTC, labbydev commented
@legostud @jesconstantine take a look at this update and LMK how it looks to you.

2017-08-10 12:45 UTC, jesconstantine commented
@legostud @labbydev Does it make sense to call the pattern something like Content Eyebrow?

So `@organisms/by-author/content-eyebrow` would include `@molecules/header-tags` and `@molecules/social-links`.

Data structure would be:
```
{
  contentEyebrow: {
    headerTags: {},
    socialLinks: {}
  }
}
```

And we'd still remove `headerTags` from `pageHeader` -- can we do this in a minor version?

2017-08-10 13:09 UTC, legostud commented
Creating a new pattern = minor release.  
Removing code from the twig and data object for Page Header = minor release.  
Removing the CSS from page-header.scss = Major release (breaks pre-existing markup).

A minor release needs to work with pre-existing markup and data from the current Major release (5).  Adding the new pattern is easy, but modifying the Page Header will take some care to keep it backward compatible.  Technically, we don't need to modify page-header at all since the header tags are optional and can just be turned off by not passing any data.  I would still request it be removed, but that work could be done as part of a future 6.0 release.  

My suggestion is to do two PRs.  One to create the new pattern and update the pages in Mayflower (minor release) and one to remove the header tags and social links from all the Page Header files (major release).

2017-08-10 13:18 UTC, jesconstantine commented
Assuming @labbydev creates the PR that you mention (creating the new pattern) for a minor release for this ticket; @labbydev can implement that new pattern on pages that need the `headerTags` but currently use the `pageBanner` and leave the pages that use the `pageHeader` to send `headerTags` as is until we implement the future PR / major release to remove the `headerTags` + `socialLinks` from `pageHeader` and updates those pages that include `pageHeader` to use the new pattern.  I think that's out of scope for this ticket for Lauren, but Iet's at least create the ticket and ear mark it for future refactoring.

How does that sound for a path forward for everyone?

2017-08-10 13:45 UTC, legostud commented
sounds fine with me.

2017-08-10 17:24 UTC, labbydev commented
@jesconstantine @legostud sounds good to me, I just want to confirm the action items:
* [ ]  Create new ticket to remove `headerTags` from `pageHeader` 
   _@jesconstantine is this something you're going to do or do you want me to do this?_
* [ ] Create a new pattern for the `headerTags` 
   _`contentEyebrow` sounds promising_
* [ ] Put the styles back in `page-header.scss` to prevent backward breaking changes
* [ ] If a pattern is already using `pageHeader` leave it as is (with `headerTags` and `socialLinks` included)
* [ ] Additional scss fixes pointed out by @legostud (see previous comments)

Does this seem correct?

2017-08-10 17:35 UTC, jesconstantine commented
@labbydev This sounds right to me as well.  I'll create the ticket mentioned in your first bullet.

2017-08-10 17:41 UTC, labbydev commented
Thanks, sounds like a plan

2017-08-11 15:15 UTC, labbydev commented on styleguide/source/assets/scss/index.scss
> +@import "03-organisms/header-tags";
@legostud I couldn't find where the border color for this is being defined, do you know where that is?

2017-08-11 15:18 UTC, labbydev commented
@jesconstantine I have added the new organism and reverted the breaking changes with `pageHeader` would you like to me to add the `contentEyebrow` to any of the other patterns?

2017-08-11 16:11 UTC, gender404 requested changes
Almost there.

Missing the border color still:
![image](https://user-images.githubusercontent.com/1462168/29221832-31b6906e-7e8e-11e7-8495-75f2aa906da3.png)

2017-08-11 16:11 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-template/content-eyebrow.json
> +  "contentEyebrow": {
perfect

2017-08-11 16:11 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-template/content-eyebrow.twig
> +  {% if contentEyebrow.headerTags.taxonomyTerms or contentEyebrow.socialLinks.items %}
I would put this outside of the section tag to remove all the html if there aren't any items to render.

2017-08-11 16:11 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-template/content-eyebrow.twig
> +</section>
line ending.

2017-08-13 12:47 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-template/content-eyebrow.json
> +  "contentEyebrow": {
@legostud based on [our discussion re: `by-template` vs `by-author`](https://github.com/massgov/mayflower/pull/527#discussion_r131629182), should this pattern live under `by-author` instead?

2017-08-13 13:05 UTC, jesconstantine reviewed
@labbydev this is great work - thanks!  Based on your Drupal ticket, we should see "relationship indicators" on the following Mayflower pages: 
- "Detail for service, how-to, location" page - done in Mayflower
- "Service" - let's add the `content-eyebrow` to `@templates/01-content-types/services` in the `preContent` block before the include for `pageBanner` and populate with data for both `@tempaltes/01-content-types-services` and `@pages/service`
- "Guide" - this one is tricky because it uses `illustrated-header` which includes `page-header` but @legostud and I [determined that the design doesn't support header-tags](https://github.com/massgov/mayflower/pull/524#discussion_r131552721).  I think we already have the hook to add it to `@templates/stacked-row-template` via the `preContent` block; so let's add and populate`content-eyebrow` on the guide page, by including it before the illustrated header -- what do you think, @legostud ?
- "Location" - uses `page-header` so we should be able to just populate `pageHeader.headerTags` in `@pages/location-general-content.json`
- "Topic" - uses 'page-banner' so I think we need to include `content-eyebrow` before `include "@organisms/by-template/page-banner.twig"` in `@pages/topic.twig` and add the `content-eyebrow` data structure as the first property to  `@pages/topic.json`

2017-08-14 13:12 UTC, gender404 commented
The direction I received from Sarena and Ned was that every page should have relationship indicators (except the homepage I guess).  Which means any page that doesn't start with a Page Header should have this new Content Eyebrow added.

As to the Illustrated Header, the Page Header tags will not work properly in that configuration so it does need the content eyebrow.

2017-08-14 13:59 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-template/content-eyebrow.json
> +  "contentEyebrow": {
If it was in the by-author area I would expect the user to be able to place this pattern anywhere on the page (in one of the various placeholders like Page Content or Right Rail).  This new pattern is only designed to be use in one location (Pre-Conntent) and should be at the top of that location so it has very strict placement requirements.

2017-08-14 17:50 UTC, labbydev commented
@legostud where is that screenshot coming from? I don't see that code in `styleguide/source/assets/scss/03-organisms/_page-header.scss`? Could you possibly link me to the line in github? I'm confused since the code is basically the same between `_page-header.scss` and `_content-eyebrow.scss` what I'm missing when it comes to the border color.

2017-08-14 17:59 UTC, labbydev commented
@legostud @jesconstantine RE:Illustrated header not getting the content eyebrow, since guide pages use the illustrated header, but also require relationship indicators, how should that be addressed?

2017-08-14 18:32 UTC, labbydev commented
Should we have an option for border or no border? Seems awkward to see the border with the banner.
<img width="1185" alt="screen shot 2017-08-14 at 1 26 47 pm" src="https://user-images.githubusercontent.com/1653723/29285698-f901f4e8-80f4-11e7-89b8-942016fa8ed3.png">

2017-08-14 18:42 UTC, gender404 commented
1. Most patterns in Mayflower have two Scss files associated with it.  The first is do the base styling and the second is to apply the Mayflower theme.  You'll see a folder in scss/06-theme. https://github.com/massgov/mayflower/blob/dev/styleguide/source/assets/scss/06-theme/03-organisms/_page-header.scss
2. Please add the new Content Eyebrow above the illustrated header on the guide page (pre-content block)
3. I agree the border looks odd there.  Feel free to add a new `hideBorder` boolean variable and `.ma__content-eyebrow--without-border` class to set `&--without-border { border: none; }` in the scss.

EDIT: that css selector isn't correct.

2017-08-14 20:54 UTC, jesconstantine commented
@labbydev @legostud for this PR let's stick with the list of page types from my [earlier comment](https://github.com/massgov/mayflower/pull/539#pullrequestreview-55965628) -- with the exception of the org page, the majority of the other page types seem to have them already anyway.

2017-08-14 21:11 UTC, gender404 requested changes
almost there.  Nice job.

2017-08-14 21:11 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-template/content-eyebrow.twig
> +  <section class="ma__content-eyebrow{{contentEyebrow.hideBorder ? '--borderless' : ''}}">
modifier classes `--something` are always pair with a parent class when using BEM syntax.  This way the modifier only contains the CSS need to override or change the default styling (no duplication)

`ma__content-eyebrow ma__content-eyebrow--borderless`

2017-08-14 21:11 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_content-eyebrow.scss
> +    @include clearfix;
these two includes shouldn't be needed once the you fix my other comment.

2017-08-14 21:11 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_content-eyebrow.scss
> +    @include clearfix;
it will also need to be `&--borderless &__tags {` to achieve the proper specificity

2017-08-15 12:57 UTC, gender404 approved these changes

2017-08-15 17:21 UTC, jesconstantine approved these changes
Thank you @labbydev - this is great work!

2017-08-15 17:38 UTC, merged