Dp 4297 footnote fix
massgov/mayflower-patternlab pull request #541
Opened 2017-08-08 17:43 UTC by gleroux02

Footnotes have been simplified and there might not always be all of the data needed to display the footnote anchor. If there are no numbered footnotes hide the anchor.

2017-08-08 18:27 UTC, legostud commented
I'm confused by this change.  Not having a number seems to defeat the purpose of footnotes since we don't know what this relates to which makes me wonder if the request was actually to remove the link from number instead of removing the number.

Outside of that there are a couple issues here.  
1. The `js-footnote` class needs to be removed to prevent the JavaScript from being processed on this note.
2. There is extra padding on the left side of the footnote where the number used to be.  Should that still be there when the number is removed?

2017-08-18 12:35 UTC, gender404 requested changes

2017-08-18 12:35 UTC, legostud commented on styleguide/source/_patterns/02-molecules/footnote.twig
> +{% set footnoteJs = footnote.number ? '' : 'js-footnote' %}
this is backwards.

2017-08-18 12:55 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/footnote.twig
> +{% set footnoteJs = footnote.number ? '' : 'js-footnote' %}
Ha - I was just testing YOU. :) I'll fix it, thanks.

2017-08-18 12:57 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/footnote.twig
> +{% set footnoteJs = footnote.number ? '' : 'js-footnote' %}
Those tricky ternaries.  Fixed in https://github.com/massgov/mayflower/pull/541/commits/812aa25546acd5b6cebc3e9f3509e41f99a389ec

2017-08-18 13:03 UTC, gender404 approved these changes

2017-08-18 14:16 UTC, merged