Release 5.6.0
massgov/mayflower-patternlab pull request #548
Opened 2017-08-20 20:56 UTC by jesconstantine

2017-08-21 10:42 UTC, jesconstantine commented on styleguide/source/_patterns/01-atoms/11-text/link.twig
> +{# Updated to use info instead of label after version 5.5 #}
@legostud Is this a typical backwards compatibility comment?

2017-08-21 10:42 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/01-content-types/event.twig
> +      {% block pageContent %}
We should check implementation and possible update event theming. /cc: @gleroux02

2017-08-21 16:16 UTC, legostud commented on styleguide/source/_patterns/01-atoms/11-text/link.twig
> +{# Updated to use info instead of label after version 5.5 #}
yes.  I don't have a real standard yet, but I try to mention the current version.

2017-08-21 16:20 UTC, legostud commented on styleguide/source/_patterns/04-templates/01-content-types/event.twig
> +      {% block pageContent %}
I guess this could be a breaking change.  I can revert it if needed.

2017-08-22 10:31 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/01-content-types/event.twig
> +      {% block pageContent %}
I think that's a good idea, let's keep this release as safe and minor as possible.

2017-08-22 10:35 UTC, jesconstantine reviewed
@legostud I think I found a couple more changes that we should consider reverting.

2017-08-22 10:35 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/single-column.twig
> +{% block header %}
@legostud I think this is another one we should consider reverting.  Seems like a breaking change - right?

2017-08-22 10:35 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/two-column.twig
> +{% block header %}
Same - I think this is a change we should revert for this release.

2017-08-22 13:56 UTC, legostud commented on styleguide/source/_patterns/04-templates/single-column.twig
> +{% block header %}
This one doesn't break anything.  It is safe to add a block to a template as long as, by default, it contains the same patterns.  The Event page modified an existing Block which is why it could be a breaking change.

2017-08-22 14:21 UTC, legostud commented on release-notes.md
> +All notable changes to this project will be documented in this file.
Shouldn't this file also contain the 5.6.0 release as part of this PR.

2017-08-22 14:21 UTC, legostud commented on styleguide/source/_patterns/04-templates/two-column.twig
> +{% block header %}
not a breaking changed

2017-08-22 14:22 UTC, gender404 approved these changes

2017-08-22 20:53 UTC, jesconstantine commented on release-notes.md
> +All notable changes to this project will be documented in this file.
Yep - I was probably in the process of creating them when you were leaving this comment.  They have been added to the PR now. :)

2017-08-22 20:55 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/single-column.twig
> +{% block header %}
Right - because of the pattern extending this template pattern doesn't overwrite the block contents then the patterns will render.  Got it.  Thanks!

2017-08-23 14:29 UTC, gender404 requested changes

2017-08-23 14:29 UTC, legostud commented on release-notes.md
> + - Outside contribution from @evanlovely - Developers will notice an improvement to the autmoatic  build + browser reload during local development. ([PR #506](https://github.com/massgov/mayflower/pul
typo - 'autmoatic'

2017-08-23 14:56 UTC, jesconstantine commented on release-notes.md
> + - Outside contribution from @evanlovely - Developers will notice an improvement to the autmoatic  build + browser reload during local development. ([PR #506](https://github.com/massgov/mayflower/pul
Thanks, updated in https://github.com/massgov/mayflower/pull/548/commits/68874780a2c8a7d37fd2b485603c7be1ed85f284

2017-08-23 17:05 UTC, EvanLovely commented
Congrats!! Glad to help a little bit! By the way: your Pattern Lab is gorgeous! Nice work!

2017-08-23 17:16 UTC, mrossi113 approved these changes
👍 LGTM @legostud

2017-08-23 17:16 UTC, merged