DP-4581 - Init event listing
massgov/mayflower-patternlab pull request #558
Opened 2017-08-23 18:59 UTC by nstriedinger

2017-08-24 15:06 UTC, gender404 requested changes
It's a decent start, but needs some help.  I would suggest adding a `js` class to the page itself to start the event-listing.js code.

2017-08-24 15:06 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/event-listing.twig
> +    <ul class="ma__event-listing__items"></ul>
I'm assuming your planning on having JS render this content anywhere it gets used.  It would be better to leave it as is and just have JS regenerate the list on the Event Listing page.

2017-08-24 15:06 UTC, legostud commented on styleguide/source/assets/js/modules/eventListing.js
> +  let resultsHeader = $('.ma__results-heading__title');
CSS classes should not be used in a JS file.  Use `js-event-listing-items` style classes instead to keep CSS styles and JS functionality separated.

2017-08-24 15:06 UTC, legostud commented on styleguide/source/assets/js/modules/eventListing.js
> +export default function (window,document,$,undefined) {
I feel like this code isn't isolated (namespaced) enough to prevent some of it from running on the location listing page.

I would have expected a $('js-event-listing-page').each(function(){ ... }); used to initialize and start the code.

2017-08-24 15:06 UTC, legostud commented on styleguide/source/assets/js/templates/eventListingRow.html
> +  <section class="ma__event-teaser">
I'm concerned with the `li` being included here, because it makes it less re-usable.  Maybe there is another way.

2017-08-29 00:37 UTC, jesconstantine commented
Close in favor of #564 (WIP)

2017-08-29 00:37 UTC, closed without merging