DP-3222/3914 Heading level adjustment for accessibility
massgov/mayflower-patternlab pull request #567
Opened 2017-08-24 16:03 UTC by ygannett

Heading levels are adjusted from page (node) level templates to their descendant templates by passing the variable `level` or specific variables to propagate proper heading levels.  Templates use default values if such variables don't have their values.

As a result, the heading levels in the page semantically streamed lined through the page.

## Note:
To make this change take effect, below Drupal change needs to be implemented together.

## Related PR for Drupal change:

## JIRA
- [DP-3914 [a11y] The headings are not semantically correct](https://jira.state.ma.us/browse/DP-3914)
- [DP

-3222 A11y Heading Levels used incorrectly](https://jira.state.ma.us/browse/DP-3222)

## Screenshots of after-change:
### Right rail
![right-rail](https://user-images.githubusercontent.com/9633303/29675599-9d0c87ee-88c3-11e7-8c02-65f24f1a4590.png)

### Advisory
![advisory](https://user-images.githubusercontent.com/9633303/29675411-12d0d828-88c3-11e7-8b3a-ad6a1ad1bc4f.png)

### Decision
![decision](https://user-images.githubusercontent.com/9633303/29675431-21401fae-88c3-11e7-83c0-aa416d61a01e.png)

### Event
![event](https://user-images.githubusercontent.com/9633303/29675439-25b975c6-88c3-11e7-8573-aa17bd8eadee.png)

### Executive order
![executive-order](https://user-images.githubusercontent.com/9633303/29675443-2a301eb6-88c3-11e7-9444-307b07c795eb.png)

### From
![form](https://user-images.githubusercontent.com/9633303/29675453-32a8c80e-88c3-11e7-84be-83538728a455.png)

### Guide
![guide](https://user-images.githubusercontent.com/9633303/29675460-388aabb6-88c3-11e7-8c8e-d92ff796ad63.png)

### How to
![how-to](https://user-images.githubusercontent.com/9633303/29675470-406b70b8-88c3-11e7-8462-4fbc60b78194.png)

### Location detail
![location-detail](https://user-images.githubusercontent.com/9633303/29675481-496f0aee-88c3-11e7-8762-684f8dd12392.png)

### Location
![location-office](https://user-images.githubusercontent.com/9633303/29675495-52d5dc70-88c3-11e7-8b6b-6d0cbb078f0c.png)

![location-park](https://user-images.githubusercontent.com/9633303/29675514-5e9ecc24-88c3-11e7-86c3-c6fcf0dff180.png)

### News
![news](https://user-images.githubusercontent.com/9633303/29675531-6809a19e-88c3-11e7-81e4-647c13d9998b.png)

### Organization landing
![organization-landing](https://user-images.githubusercontent.com/9633303/29675539-7132cc1e-88c3-11e7-9dde-f49ba98bc398.png)

### Stacked layout
![stacked-layout](https://user-images.githubusercontent.com/9633303/29675555-7b8b6fd6-88c3-11e7-8c42-de802d9f21a4.png)

### Service detail
![service-detail](https://user-images.githubusercontent.com/9633303/29675565-8474dac4-88c3-11e7-9e40-1a0a0f347514.png)

### Service
![service](https://user-images.githubusercontent.com/9633303/29675575-8edc28fa-88c3-11e7-9bb5-02f8526e2817.png)

2017-08-24 17:52 UTC, gender404 requested changes
I need to get some work done so I'm going to pause my review here.  I'll review the rest tomorrow or later today.

2017-08-24 17:52 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.json
> +    "sub": "",
`sub` is no longer relevant since level is accomplishing the same task.  It should be removed from here and the md file

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.json
> +    "sub": "",
also remove it from each variant of the comp heading

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.twig
> +{% if compHeading.sub %}
compHeading.sub should set the level to 3 for backward compatibility

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.twig
> +{% endif %}
Why do we need a global 'level' variable or a global 'content.data.level`.  These don't feel like they belong when the parent pattern can easily do a `compHeading|merge` to set the compHeading.level value.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.twig
> +{% endif %}
you made and if / else that has the same values.  You don't need the conditional anymore.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.json
> +    "centered": ""
not sure why this changed.  maybe it's a merge issue.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.twig
> +{% endif %}
Also I would use a ternary {% set level = compHeading.level ?: 2 %}

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/01-atoms/04-headings/sidebar-heading.twig
> +{% endif %}
Still not sure why we're checking for `level`.  I'd use a ternary `{% set level = sidebarHeading.level ?: 3 %}` to set the value

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/01-atoms/04-headings/sidebar-heading.twig
> +{% endif %}
This change currently isn't backward compatible so it would have to be part of a new major release (6.0) since there is no default for `level` set

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/02-molecules/action-section.twig
>  {% include actionSection.path with actionSection.data %}
This is technically and obsolete pattern so I'm not sure how much I should review.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/02-molecules/action-step.twig
> +</section>
Looks like the white space got converted can you switch that so just the change is visible.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +</div>
White space issue with linux vs windows line endings is making this appear like the whole file has changed.  please correct so it's easier to see what's changed.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +{% set level = contactGroup.level ?: 2 %}
Is two going to work for backwards compatibility?  I know it fixes the current bug in the location header, but will it create more issues when used in the Right Rail.  2 is probably the better value, but to make it more compatible you should have use five so it continued to render as previous `h5`

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +    <h{{ level }} class="ma__contact-group__name">
I think I would have set `level` here since it's the only place used.

~~~
{% set level ...
<h {{ level }}>...
~~~

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/02-molecules/contact-us.twig
> +</section>
White space change is making it hard to review the changes.  please fix.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/02-molecules/contact-us.twig
> +      {% set columnHeadingLevel = level %}
Feels like we're working too hard to set these levels.  I'll need to review this later.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/02-molecules/press-teaser.twig
> +</section>
white space issue needs to be resolve to show just what was changed.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/02-molecules/press-teaser.twig
> +{% set level = pressTeaser.level ? : 2 %}
Since this is only used once, it would be better to put it next to where it is used.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/02-molecules/related-action.md
> +  	 type: intrger/required
indentation issue

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/02-molecules/related-action.md
> +  	 type: intrger/required
This is also an obsolete pattern

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/action-details.twig
>    </div>
This is an obsolete patter so I'm not sure how much to review

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/action-details.twig
> +{% set level = level ? : 2 %}
I think this is supposed to be `actionDetails.level ?: 2`

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/callout-time.twig
> +{% set level = content.data.level ? : 3 %}
not sure where `content.data.level` is coming from.  should this have been `calloutTime.level`

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/contact-list.twig
> +</section>
white space issue needs to be resolved

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/contact-list.twig
> +{% set contactListLevel = '' %}
this needs to be set to a default value.  if neither a compHeading or a sidebarHeading are used then your level becomes "" + 1.  I'm not sure what that will do, but I think it will pass "1" which is not a number and if it works would generate an `<h1>` title in the contactUs.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/form-downloads.twig
> +</section>
white space issue making it hard to see what changed.  please fix.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/form-downloads.twig
> +{% set level = stackedRowSection.level ? : 2 %}
I don't see where this is used.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/form-requirements.twig
> +        {% set columnHeading = columnHeading|merge({'level': formRequirements.level}) %}
No variable formRequirement.level also I don't think this is required since you are already passing the level as part of rteTitle.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/key-actions.json
> +      "sub":true
Not sure why sub changed values and id disappeared, but again sub isn't required anymore.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/key-actions.twig
> +
white space issues need to be resolve so I can see what changed.

2017-08-24 17:52 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/key-actions.twig
> +{% set level = content.data.level ? : 2 %}
this doesn't seem needed and uses `content.data.level` which I haven't found where or why that is being used.

2017-08-24 18:03 UTC, ygannett commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.json
> +    "centered": ""
I didn't touch this line since it's not related what I worked on.  As you mentioned, it could be a merge issue.  I'll put it back.

2017-08-24 18:08 UTC, ygannett commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.twig
> +{% endif %}
I should have more expressive with this condition.  There is a case `level` is propagated as `level` with value from its parent template, so I didn't use a ternary.

2017-08-24 18:11 UTC, ygannett commented on styleguide/source/_patterns/01-atoms/04-headings/sidebar-heading.twig
> +{% endif %}
This is also a case `level` is propagated as level with value from some of its parent template.

2017-08-24 18:14 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +{% set level = contactGroup.level ?: 2 %}
I learned right rail and stacked layout pages are using some templates set up in the theme (docroot/themes/custom/mass_theme/templates/).  Those templates take care of these two page types.

2017-08-24 18:16 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +</div>
Will do.

2017-08-25 12:44 UTC, legostud commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.twig
> +{% endif %}
that's what I was afraid of.  It's one of the things that Ian and I discussed in the comments.  We don't want variables to bleed between patterns (content.data.level).  All data consumed by a pattern should be explicitly set within that pattern's name space (ie: compHeading).  

Global variables like level are dangerous to consume.  Any variable you want to use should always be part of the patterns namespace (compHeading) or defined with a `set` before being used.  Doing `if (level == '' )` happens prior to it being set.

If the compHeading is used after a Contact List, then 'level' variable will start off as 4 having been set by the last contact group.  Your first conditional will fail because level = 4 not ''. if the level hasn't been set on the compHeading, then the next conditional will fail.  And if we're not in a Stacked Row then the content.data.level conditional will fail as well, leaving us with an `h4`.

2017-08-28 16:14 UTC, ygannett commented
Replaced with [DP-3222/3914 Heading level adjustment for accessibility (cleaned) #569](https://github.com/massgov/mayflower/pull/569)

2017-08-28 16:14 UTC, closed without merging