[TEST]
massgov/mayflower-patternlab pull request #579
Opened 2017-09-01 14:10 UTC by ygannett

## Description

## Related Issue / Ticket

- [JIRA issue]()
- [Github issue]()

## Steps to Test

1. 

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

#### Today I learned...

2017-09-05 20:11 UTC, gender404 requested changes
I wasn't able to review all the files, but I think we have enough changes to work with for now.  

One of the overarching issues I see is the use of global variables `level` and `content.data.level`.  Global variables are not ideal.  We should just be setting the level values in the JSON files instead.  If the levels have to be strictly enforced by the parent, then we should be using a |merge to set the level on included patterns.

The other issue is a potential that I haven't looked at yet.  I don't see any CSS changes.  I would have assumed that at least one of these patterns would have rendered incorrectly when the heading level was changed so did we compare the local rendered pattern to the one in production to see if is the same?

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/04-headings/column-heading.twig
> +{% set level = columnHeading.level ?: 3 %}
This should be set to '4' to keep it backward compatible.  This component was originally rendering an `<h4>` and now it renders an `<h3>`

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.twig
> +{% endif %}
I'd rather not check for a global `level` or `content.data.level`.  Whatever pattern is setting those global value should instead be setting the compHeading.level value.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.twig
> +{% endif %}
This is also not a reliable way to set the default value.  if `level` was set in a previous pattern, then your logic statement fails.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.twig
>  {% endif %}
We don't need the if / else statement here.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/04-headings/comp-heading.twig
> +{% endif %}
we also need to set `level = 3` if `compHeading.sub` is set to true for backward compatibility with the current version.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/01-atoms/04-headings/sidebar-heading.twig
> +{% endif %}
This can be simplified => `{% set level = sidebarHeading.level ? : 3 %}`

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/action-step.twig
> +    {% set level = actionStep.level ? : 4 %}
This should be set to '2' to make sure it matches what it was to keep it backward compatible.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +{% set level = contactGroup.level ?: 2 %}
This should be set to '5' to make sure it matches what it was to keep it backward compatible.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/contact-us.twig
> +      {% if outerAccordion != true %}
Why is this important to test for?  What are we trying to solve?

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/contact-us.twig
> +  {% set contactGroupLevel = columnHeadingLevel + 1 %}
I would suggest setting the value of `contactGroupLevel` to '2' at the top of the file.  Then where you have `{% set columnHeadingLevel = level %}` change it to update the value of `contactGroupLevel`

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/image-promo.twig
> +{% set level = imagePromos.level ? : 4 %}
This should be set to '2' to make sure it matches what it was to keep it backward compatible.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/callout-time.twig
> +{% set level = content.data.level ? : 3 %}
This should be set to '5' to make sure it matches what it was to keep it backward compatible.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/contact-list.twig
> +  {% set contactUsHeadingLevel = contactListLevel + 1 %}
Just increment the value above `{% set  contactListLevel =  compHeading.level + 1 %}`  and `{% set  contactListLevel =  sidebarHeading.level + 1 %}`

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/contact-list.twig
> +    {% set contactUs = contactUs|merge({'subTitle': subTitle}) %}
can you explain why this is on two lines?  Is this due to how |merge works?

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/form-downloads.json
> +      "level": 3,
This should be set to '2' since this is just the organism level.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/contact-list.json
> +      "level": 3,
I would start this at level 2 since we're just rendering the organism itself.  localhost:3000/?p=organisms-contact-list

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/action-section.twig
>        "sub": true,
I would remove `"sub": true` since that variable is being replaced by `level`

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/02-molecules/action-section.twig
> +{% endif %}
I don't like this approach.  We have no guarantee that actionSection.id will be 'activities' when an image-promo is used.

I think we can skip all this code and just update the imagePromos `level` variable to the correct value when used on the page.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/action-details.twig
> +{% set level = level ? : 2 %}
should be `{% set level = actionDetails.level ? : 2 %}`

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/action-details.twig
> +      {% set actionSection = actionSection|merge({'level': level }) %}
I would pass it 'level + 1'.  This way you're declaring which level you want the section to render, which is more inline with the other patterns where you set `level = 2` and it renders an `<h2>`

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/form-downloads.twig
> +{% set level = stackedRowSection.level ? : 2 %}
Two issues here.  We're setting a global `level` variable and we're looking for a variable from another pattern `stackedRowSection`.  Neither of these are good ideas.  I think we should just let the page that includes the Download Links set it's data values to the correct level value.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/form-requirements.twig
> +        {% set columnHeading = columnHeading|merge({'level': formRequirements.level}) %}
I don't think this is needed.  We can just set the `columnHeading.level` value in the formRequirements JSON file.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/form-requirements.twig
> +          {% set columnHeading =  columnHeading|merge({'level': formRequirements.level}) %}
Same as above.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/key-actions.twig
> +    {% endif %}
Why did we add a Sidebar Heading to this pattern?

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/key-actions.twig
> +{% set level = content.data.level ? : 2 %}
This is bad idea, because we are using global variables that can be unpredictable.  We can handle the levels by updating the JSON values instead.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/steps-unordered.json
> +      "level": 3,
This should start at 2 since it's we're at the organism level so it's being included after another heading tag.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/press-listing.twig
> +{% set level = level ? : 2 %}
This is a bad pattern to use.  Global variables will cause bugs in the future.

2017-09-05 20:11 UTC, gender404 commented on styleguide/source/_patterns/03-organisms/by-author/steps-ordered.json
> +      "level": 3,
This should start at 2 since it's we're at the organism level so it's being included after another heading tag.

2017-09-05 20:11 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/press-listing.twig
> +{% set level = level ? : 2 %}
you should use `pressListing.level ? : 2`

2017-09-11 17:16 UTC, ygannett commented
After the 9/7 meeting, I did some work on files per group of base template files.  The following files were touched after the meeting. `level` is removed from not all JSON files which contain ones.
### Group 1:
- styleguide/source/_patterns/04-templates/two-column.twig
- styleguide/source/_patterns/05-pages/detail-for-service-howto-location.json
- styleguide/source/_patterns/05-pages/detail-for-service-howto-location.twig
-  styleguide/source/_patterns/05-pages/executive-order.twig

### Group 2:
- styleguide/source/_patterns/04-templates/01-content-types/details.twig
- styleguide/source/_patterns/05-pages/howto.twig

### Group 3:
- styleguide/source/_patterns/04-templates/01-content-types/location.json
- styleguide/source/_patterns/04-templates/01-content-types/location.twig
- styleguide/source/_patterns/05-pages/location-general-content.json
- styleguide/source/_patterns/05-pages/location-general-content.twig
- styleguide/source/_patterns/05-pages/location-park-content.json
- styleguide/source/_patterns/05-pages/location-park-content.twig

### Group 4:
- styleguide/source/_patterns/04-templates/01-content-types/form-page.json
- styleguide/source/_patterns/04-templates/01-content-types/form-page.twig
- styleguide/source/_patterns/03-organisms/by-author/form-requirements.twig

### Group 5:
- styleguide/source/_patterns/04-templates/01-content-types/event.json
- styleguide/source/_patterns/04-templates/01-content-types/event.twig
- styleguide/source/_patterns/05-pages/event.twig

### Heading templates which `level`s have been removed:
- styleguide/source/_patterns/01-atoms/04-headings/column-heading.json
- styleguide/source/_patterns/01-atoms/04-headings/comp-heading.json
- styleguide/source/_patterns/01-atoms/04-headings/sidebar-heading.json

2017-09-13 21:18 UTC, legostud commented
This PR has been replaced by https://github.com/massgov/mayflower/pull/590

2017-09-19 16:54 UTC, jesconstantine commented
Closing in favor of #590

2017-09-19 16:54 UTC, closed without merging