DP-5233 Fix basic table styles for tables in rich text editors
massgov/mayflower-patternlab pull request #586
Opened 2017-09-12 14:47 UTC by ygannett

Add a missing class, **.ma__rich-text** to apply the styles to tables in rich text editor.

## Description

## Related Issue / Ticket

- [DP-5233 Fix basic table styles for tables in rich text editors](https://jira.state.ma.us/browse/DP-5233)

## Steps to Test

1. 

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

#### Today I learned...

2017-09-14 15:32 UTC, gender404 requested changes

2017-09-14 15:32 UTC, legostud commented on styleguide/source/assets/scss/06-theme/01-atoms/_table.scss
>  .rich-text table,
you can remove the `.rich-text table` selector.  That's a typo.

2017-09-14 16:33 UTC, ygannett commented on styleguide/source/assets/scss/06-theme/01-atoms/_table.scss
>  .rich-text table,
Ok. Will do.  Thank you @legostud

2017-09-14 17:23 UTC, gender404 approved these changes

2017-09-19 16:53 UTC, jesconstantine commented
@ygannett Thanks for your work here!  As a next step, can you follow the steps listed in the [Contributing docs](https://github.com/massgov/mayflower/blob/dev/.github/CONTRIBUTING.md#getting-started) to push your branch to your fork's github pages branch so that it can be UAT'd and then merged into dev here?

2017-10-16 15:35 UTC, ygannett commented
Per @cmajel's comment in JIRA, this passed the external review. 
> Christine Bath added a comment - Oct 05, 2017 08:48 AM
> 
> Yukiko Gannett per our chat yesterday this looks good to me!

> Christine Bath made changes - Oct 05, 2017 09:12 AM
> Status | Ready for External Review [10518 ] | Passed External Review [10522 ]

2017-10-18 19:27 UTC, merged