DP 4717 -- Remove the css rule for the @molecules/header-tags pattern which curr…
massgov/mayflower-patternlab pull request #591
Opened 2017-09-14 14:57 UTC by nstriedinger

…ently forces this title case: text-transform: capitalize

## Description
Remove the css rule for the @molecules/header-tags pattern which currently forces this title case: text-transform: capitalize;

## Related Issue / Ticket

- https://jira.state.ma.us/browse/DP-4517
- [Github issue]()

## Steps to Test

1. Read ticket.
2. Verify that CSS rule has been removed by visiting a page with the relationship indicator.

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

#### Today I learned...

2017-09-14 15:31 UTC, gender404 approved these changes

2017-09-25 13:38 UTC, jesconstantine requested changes
@nstriedinger thanks for jumping in there - I think we only need one of your two changes.  Let me know what you think.  Thanks!

2017-09-25 13:38 UTC, jesconstantine commented on styleguide/source/assets/scss/02-molecules/_header-tags.scss
> -  text-transform: uppercase;
@nstriedinger does this mean that "more about" is no longer uppercase?  Because I don't think that's the desired affect of this change; we only want the tag terms to have their title case removed.

2017-10-12 13:56 UTC, jesconstantine approved these changes

2017-10-12 17:27 UTC, merged