DP-4534 - Add MF handling for many relationship indicators
massgov/mayflower-patternlab pull request #594
Opened 2017-09-15 15:11 UTC by nstriedinger

## Description

## Related Issue / Ticket

- [JIRA issue]()
- [Github issue]()

## Steps to Test

1. 

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

#### Today I learned...

2017-09-20 18:45 UTC, jesconstantine requested changes
@nstriedinger Thanks for your hard work here!  I think there are some areas that we can iterate on.  Let me know if you have any questions.

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/header-tags.twig
> +  <div id="terms" class="ma__header-tags__terms">
The `id` should be passed in as a variable in case it's used more than once

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/header-tags.twig
> +    <button type="button" class="js-accordion-link" aria-expanded="false" aria-controls="terms">
The `js` class should be unique to this component.  I'd suggest something like `.js-header-tag-button`

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/header-tags.twig
> +      <span>more</span><span>less</span>
The button text should be configurable, let's pass them both in as a variable

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/js/index.js
> +import relationshipIndicators  from "./modules/relationshipIndicators.js";
Could we alphabetize and line these up for readability?

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/js/modules/relationshipIndicators.js
> +
Our js module files should use `jQuery.each()` to ensure the code will work with multiple instances of a component and also to ensure that the code only runs when the pattern is present.

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/header-tags.twig
>        <a href="{{ item.href }}">{{ item.text }}</a>
Since you reference this element in your js, we need to use a js class (vs the css class), I'd suggest something like: `.js-header-tag-link`

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/js/modules/relationshipIndicators.js
> +  var moreThanThreeRelatedItems = relatedItems.length > 2 ? true : false;
1. We should use `const` to define variables that don't change (i.e. selectors)
1. `showHideButton` should reference the new js class from prior comment: `.js-header-tags-button`
    1. Since it references a jQuery object, it should also be `$showHideButton`
1. `relatedItems` should reference a js class (vs a css class), I'd suggest something like: `.js-header-tags-link`
    1. Since it references a jQuery object, it should also be `$relatedItems`
    1. Since the only `relatedItems` that we need to worry about are the 3rd+, what if your selector targeted `$('.js-header-tags-link:nth-child(n+3)')`?
1. For `moreThanThreeRelatedItems`:
    1. Including a number in the variable name could be brittle
    1. Since the variable name includes `Three` should you also be testing for `> 3`?
    1. This variable is actually not needed if your $relatedItems variable targets only the items that we ever reveal/hide and if you structure your logic below like:

```
if ($relatedItems.length) {
  showHideButton.hide();
  return; // none of the logic to show / implement the button is necessary
}

// Functionality from your 2nd if statement here
// Init just show 3.
$relatedItems.show()
...

```

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/js/modules/relationshipIndicators.js
> +    };
Since your `$relatedItems` selector includes only the items that we want to show/hide, we no longer need this function.

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/js/modules/relationshipIndicators.js
> +    };
Since your `$relatedItems` selector includes only the items that we want to show/hide, we no longer need this function.

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/js/modules/relationshipIndicators.js
> +    showThreeRelatedItems();
This can be `$relatedItems.show()`

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/js/modules/relationshipIndicators.js
> +    showHideButton.on('click', function(e) {
Please double check to make sure this works for keyboard interaction

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/js/modules/relationshipIndicators.js
> +      "use strict";
I think this should be moved to the top of the file (after the `export default` line)

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/js/modules/relationshipIndicators.js
> +        showAllRelatedItems();
This can be `$relatedItems.show()`

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/js/modules/relationshipIndicators.js
> +        showThreeRelatedItems();
This can be `$relatedItems.hide()`

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/scss/02-molecules/_header-tags.scss
> +  max-width: 820px;
What's the reasoning for constricting width? Also, if we were going to constrict the width, we should use the [`$l-max-content-width variable`](https://github.com/massgov/mayflower/blob/dev/styleguide/source/assets/scss/00-base/_variables.scss#L12)

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/scss/02-molecules/_header-tags.scss
> +      color: #14558f;
Rather than hard code a hex RGB color, this value should be a variable.  See [`$c-theme-primary`](https://github.com/massgov/mayflower/blob/dev/styleguide/source/assets/scss/06-theme/00-base/_colors.scss#L18)

Also any css rules that touch how a pattern will look (i.e. colors, font-size) should be defined in the scss theme directory: https://github.com/massgov/mayflower/tree/dev/styleguide/source/assets/scss/06-theme

2017-09-20 18:45 UTC, jesconstantine commented on styleguide/source/assets/scss/06-theme/03-organisms/_page-header.scss
> +      border-color: $c-bd-divider;
Nice!  Thanks for using the variable here!

2017-09-25 19:50 UTC, nstriedinger commented on styleguide/source/assets/js/modules/relationshipIndicators.js
> +  var moreThanThreeRelatedItems = relatedItems.length > 2 ? true : false;
This is great!

2017-09-25 20:14 UTC, nstriedinger commented on styleguide/source/assets/scss/02-molecules/_header-tags.scss
> +  max-width: 820px;
The design implied this.

2017-10-05 18:36 UTC, gender404 approved these changes

2017-10-12 19:34 UTC, jesconstantine reviewed
@gleroux02 nice work!  Just one small tiny scss change and a suggestion for button text defaults -- let me know what you think!

2017-10-12 19:34 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/header-tags.twig
> +      <span>{{ headerTags.moreLabel }}</span><span>{{ headerTags.lessLabel }}</span>
@gleroux02 what do you think about having these be configurable with reasonable defaults? I'm thinking something like this at the top of the file:

```
{% set moreLabel = headerTags.moreLabel ?: "show more" %}
```

2017-10-12 19:34 UTC, jesconstantine commented on styleguide/source/assets/scss/02-molecules/_header-tags.scss
> +      font-weight: 500;
I think `font-weight` needs to go in a `scss/06-theme/02-molecules/_header-tags.scss` file.  

Everything else seems to be in the right place though :)

2017-10-12 20:08 UTC, legostud commented on styleguide/source/assets/js/modules/relationshipIndicators.js
> +      $showHideButton.hide();
This should be done via CSS to avoid a blink cause be JS hiding and showing the button on page load.

2017-10-12 20:09 UTC, legostud commented on styleguide/source/assets/js/index.js
> +import relationshipIndicators  from "./modules/relationshipIndicators.js";
you line up the "from" column

2017-10-19 13:15 UTC, jesconstantine reviewed
@gleroux02 I think once we get the caret rotating this will be good to go!  See my comments below. Thanks!!

2017-10-19 13:15 UTC, jesconstantine commented on styleguide/source/assets/scss/02-molecules/_header-tags.scss
> +      &.is-open:after {
@gleroux02 I think this selector needs to be updated (just like you did for the spans) so that the caret rotates

2017-10-19 13:15 UTC, jesconstantine commented on styleguide/source/assets/scss/03-organisms/_page-header.scss
> +      top: 1px;
This indentation is intentional to show a dependency between `top` and `position` (a nice little trick from @legostud)

2017-10-20 18:53 UTC, jesconstantine approved these changes
Woo-hoo!!! Thanks @nstriedinger and @gleroux02 :)

2017-11-10 20:54 UTC, merged

2017-11-27 19:06 UTC, powpow12 commented on styleguide/source/_patterns/02-molecules/header-tags.twig
> +      <span>{{ headerTags.moreLabel }}</span><span>{{ headerTags.lessLabel }}</span>
this will circumvent line 1 & 2.  @jesconstantine will patch.

2017-11-27 19:07 UTC, powpow12 commented on styleguide/source/_patterns/02-molecules/header-tags.json
> +    "id": "terms",
this will be done through Js as we do not want to add a new mandatory property without providing some override.