DP 4313 - Remove logo from service page
massgov/mayflower-patternlab pull request #596
Opened 2017-09-15 18:20 UTC by nstriedinger

## Description
Remove optional logo from Service page.

## Related Issue / Ticket

- https://jira.state.ma.us/browse/DP-4313
- [Github issue]()

## Steps to Test

1. Read Ticket
2. View http://localhost:3000/?p=pages-service and verify the removal of logo.

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

#### Today I learned...

2017-09-20 14:57 UTC, gender404 approved these changes

2017-09-23 12:48 UTC, jesconstantine requested changes
@nstriedinger if we're removing the logo from this content type in such a way that it's no longer possible to include it in the future (i.e. removing it from the markup), then we also need to update the corresponding documentation `.md` file and the and the data `.json` file so that future developers understand the scope of the change.

If we want to make the change in a way that would allow us to add the logo back in the future (perhaps not a bad idea - thoughts?) then we should only remove the data sent in the .json file and leave the pattern markup `.twig` and documentation `.md` as is.

2017-09-25 18:10 UTC, nstriedinger commented
@jesconstantine It's up to you. What would you like me to do?

2017-09-25 18:13 UTC, jesconstantine commented
@nstriedinger let's remove the json data but leave the markup twig and docs md file as is; just make sure the markup only renders the image if the data is sent, and make sure the variable is optional in the md file.  Sound good?

2017-09-26 10:53 UTC, jesconstantine approved these changes
Thanks for your updates here @nstriedinger .

2017-09-27 12:01 UTC, merged