DP-4572 - Re-work Dateline
massgov/mayflower-patternlab pull request #599
Opened 2017-09-18 15:30 UTC by nstriedinger

## Description
I reworked the Dateline for the Drupal side. FYI -- I kept the <p> tag for current PL structure, but we will not be using this pattern on the Drupal end. (On the Drupal end, we're separating everything out and adding the Dateline, and reassembling programmatically.) 

## Related Issue / Ticket

- https://jira.state.ma.us/browse/DP-4572
- [Github issue]()

## Steps to Test

1. Read Ticket
2. Very Dateline looks correct.

## Screenshots
![screen shot 2017-09-18 at 11 29 29 am](https://user-images.githubusercontent.com/231467/30550221-cc4d01a0-9c64-11e7-811e-eebe4a33ecc0.png)

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

#### Today I learned...

2017-09-20 15:07 UTC, gender404 requested changes
What was the requirement for adding the extra class to make this bold instead of using the `b` tag?

Personally, I prefer the Drupal solution over what I created.  My solution is a bit brittle so I'd be okay with deleting the `ma__press__location-label` Markup and CSS in favor of just adding the content within the first paragraph of the RTE block.  Having it as part of the RTE block was my original solution, because it was simple and elegant.

2017-09-20 15:07 UTC, legostud commented on styleguide/source/assets/scss/04-templates/_press.scss
> +    font-weight: bold;
font-weight should be part of a theme CSS file not part of the base CSS file (ie: /06-theme/04-templates/_press.scss file.

2017-09-26 17:32 UTC, nstriedinger commented on styleguide/source/assets/scss/04-templates/_press.scss
> +    font-weight: bold;
Did I add this correctly?

2017-09-27 17:00 UTC, legostud commented on styleguide/source/assets/scss/04-templates/_press.scss
> +    font-weight: bold;
yes that looks good

2017-09-27 17:27 UTC, jesconstantine commented
@legostud I didn't fully understand your original change request - was it just to move the style rule into the theme scss or was there something else that you thought needed to be addressed here?

2017-09-27 18:20 UTC, nstriedinger commented
@legostud -- @gleroux02 suggested I use a '<span>'.

2017-09-28 13:08 UTC, legostud commented
This PR doesn't appear to solve any issues so I'm confused as to what's the goal with making this change?  

The `&__label` was already uppercase and the text was already bold.  The only difference I see here is that the &mdash; is no longer uppercase, which doesn't matter.  This PR seems to be just adding bloat for no reason.

2017-09-28 13:13 UTC, legostud commented
I feel like we're missing something.  Maybe there is actually more work that needs to be done in Mayflower to match the approach that Mass Gov is using.

2017-09-28 14:39 UTC, legostud commented
After talking with Jes, I better understand the desired outcome here.  I would suggest removing all the code for the `location-label` and just add the content `<span class="ma__rich-text__flame">Boston</span> &mdash; ` to the first paragraph of the Rich Text component in Mayflower.  In the _rich-text.scss files we can add the styling needed to make the `&__flame` selector uppercase and bold similar to what you've already created.

What we're doing is add a 'flame' option to the Rich Text pattern in Mayflower that you can leverage for your current solution.

2017-09-28 17:19 UTC, gender404 requested changes

2017-09-28 17:19 UTC, legostud commented on styleguide/source/assets/scss/06-theme/03-organisms/_rich-text.scss
> +    font-weight: bold;
This should be in the 'theme' file for rich-text.  Otherwise this looks really good.

2017-09-28 17:20 UTC, legostud commented on styleguide/source/assets/scss/06-theme/03-organisms/_rich-text.scss
> +    font-weight: bold;
the font-weight: bold that is

2017-09-28 17:29 UTC, gender404 approved these changes

2017-10-30 20:17 UTC, merged