DP-5636 Drop shadows on homepage - mobile
massgov/mayflower-patternlab pull request #610
Opened 2017-10-05 21:55 UTC by mariohernandez

## Description
https://jira.state.ma.us/browse/DP-5636
Some section breakers on homepage were showing box shadows that are not part
of the design requirements.  I went ahead and removed them.

## Related Issue / Ticket

- DP-5636
- N/A

## Steps to Test
* Visit Mass.gov's homepage
* Scroll through the page and look at the various row sections.  They should not have any box shadow.

## Screenshots
* Homepage showing box shadow: http://take.ms/KeuFT
* Homepage NOT showing box shadow: http://take.ms/BGHRj

## Additional Notes:

N/A

#### Impacted Areas in Application
Homepage mobile only.

#### @TODO
N/A

#### Today I learned...
Today I learned how to fix bugs in the mayflower repo.

2017-10-06 12:47 UTC, gender404 requested changes

2017-10-06 12:47 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_stacked-row-section.scss
> -    box-shadow: 0 0.5rem 0.5rem -0.25rem rgba(1, 1, 1, 0.25);
This was added for use on the Guide Pages.  I doubt they've changed the design there.  

You will probably need to add a twig variable that adds a modifier class to the parent of the stacked row sections telling CSS to skip the box shadows.  `.ma__stacked-row-content .ma__stacked-row-content--no-shadows`

2017-10-09 15:04 UTC, mariohernandez commented on styleguide/source/assets/scss/03-organisms/_stacked-row-section.scss
> -    box-shadow: 0 0.5rem 0.5rem -0.25rem rgba(1, 1, 1, 0.25);
Thanks.  I'll work on that.

2017-10-09 16:14 UTC, mariohernandez commented
Updated PR by appending conditional of **is-front** to **.ma__stacked-row-section** to remove box-shadow from homepage.  Originally tried to add no-shadows conditional class but then realized **is-front** was already available on body.
Updated line ending settings from Windows to Unix to avoid invalid characters being introduced to commit.

2017-10-10 13:04 UTC, gender404 approved these changes
That fixes my concern.  it's @jesconstantine call now.

2017-10-11 16:37 UTC, closed without merging

2017-10-11 16:37 UTC, mariohernandez commented
Closed commit as these changes are being made within Drupal's them rather than mayflower.  A new PR will be created.