DP-5523-action finder
massgov/mayflower-patternlab pull request #639
Opened 2017-10-26 16:53 UTC by mariohernandez

## Description
Updated action finder background position styles.

## Related Issue / Ticket
https://jira.state.ma.us/browse/DP-5523

## Steps to Test
* http://localhost:3000/?p=pages-service

## Screenshots
http://take.ms/VgYq0

## Additional Notes:

N/A

#### Impacted Areas in Application

* 

#### @TODO

*

#### Today I learned...

2017-10-26 17:00 UTC, gender404 requested changes

2017-10-26 17:00 UTC, gender404 commented on styleguide/source/assets/scss/06-theme/03-organisms/_action-finder.scss
>    &--no-background + &--no-background {
Well that's a pretty silly selector.  The `+` is used to skip the first child and then you put the first child back in so now it selects all => `&--no-background {`

2017-10-26 17:04 UTC, legostud commented on styleguide/source/assets/scss/06-theme/03-organisms/_action-finder.scss
>    &--no-background + &--no-background {
also just noticed that :first-child is targeting all .ma__action-finders that are the first item in the parent container regardless of whether or not it is flagged as `--no-background`

2017-10-26 23:02 UTC, mariohernandez commented
Good points @legostud.  I went ahead and removed the styles redundancy.

2017-10-30 13:15 UTC, gender404 approved these changes

2017-11-20 16:23 UTC, merged