DP-5991 [mf] Create "Public Meeting Notice" event variant
massgov/mayflower-patternlab pull request #642
Opened 2017-11-08 15:03 UTC by jaymejohnson

## Description
At this time this PR represents a work in progress. The ticket will be updated with QA steps and more robust notes when the PR is ready to me merged. 

## Additional Notes:

In attempting to create a heading for the agenda section (see the area around comment 6: https://projects.invisionapp.com/share/Z4E9SVHGM#/screens/252099676/comments) I ran into a bug that isn't allowing for the creating of dynamic variable names in include statements. 

* Proof of concept for the solution can be found [here](https://twigfiddle.com/r62etw)
* A reduced test case exposing the bug I am having can be found [here](https://twigfiddle.com/w6ydal)

#### @TODO
* Once this bug is squashed, there will still be more to be done to complete the agenda section. For the definition of done, see [the originla Jira ticket](https://jira.state.ma.us/browse/DP-5991)

#### Today I learned...

2017-12-06 17:39 UTC, jaymejohnson commented
@jesconstantine  This PR is ready for review!

2017-12-11 20:00 UTC, jesconstantine requested changes
@jaymejohnson awesome work here!  See my few questions / comments here and let me know if you have any questions.

2017-12-11 20:00 UTC, jesconstantine commented on styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
> +        "location": "251 Causeway St., Suite 900, Boston, MA 02114",
@jaymejohnson can we have the data shown here reflect the "parent" event data: https://jaymejohnson.github.io/mayflower/?p=pages-event-public-meeting

2017-12-11 20:00 UTC, jesconstantine commented on styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
> +          "summary": "Sunday, August 12, 2018 9:10 a.m. - Monday, August 13, 2018 9:35 a.m. "
@jaymejohnson can we have the data shown here reflect the "parent" even data: https://jaymejohnson.github.io/mayflower/?p=pages-event-public-meeting

2017-12-11 20:00 UTC, jesconstantine commented on styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
> +          "text": "Another Optional Link",
@cmajel here's the screenshot of where this data is rendered:
![image](https://user-images.githubusercontent.com/3279883/33838331-427bf888-de5d-11e7-82a5-2ceecc0ee8f9.png)

It is clear to me how the minutes link is populated, but what about the other optional link? Is there a field associated with this information? (I didn't see one in the google sheet)

If there is not field data for this, can we remove the 2nd link?  It's a bit confusing for implementers.

2017-12-11 20:00 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-author/rich-text.twig
> +  {% block rteElements %}
@jaymejohnson can we add a comment here which describes the purpose of this block?  Something along the lines of: This twig block allows implementers to iterate through their own loop to render molecule content.

Or maybe have the comment in the twig just reference the pattern `.md` docs and talk more about it in the docs

2017-12-11 20:00 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/01-content-types/event.json
> +            "heading6": {
@jaymejohnson please update these h6's to be h3's because that's what they need for semantic / accessibility purposes

2017-12-11 20:00 UTC, jesconstantine commented on styleguide/source/_patterns/05-pages/event~public-meeting-minutes.json
> +        "location": "251 Causeway St., Suite 900, Boston, MA 02114",
@jaymejohnson same comment here re: making the address match that of the "parent" event

2017-12-11 20:00 UTC, jesconstantine commented on styleguide/source/_patterns/05-pages/event~public-meeting-minutes.json
> +          "summary": "Sunday, August 12, 2018 9:10 a.m. - Monday, August 13, 2018 9:35 a.m. "
@jaymejohnson same comment here re: making the event day / time match that of the "parent" event

2017-12-11 20:00 UTC, jesconstantine commented on styleguide/source/_patterns/05-pages/event~public-meeting-minutes.json
> +        "text":"Another Optional Link",
@jaymejohnson just calling out the other instance in the event that @cmajel approves removing this link to make it clearer for implementers

2017-12-11 22:21 UTC, jaymejohnson commented on styleguide/source/_patterns/04-templates/01-content-types/event.json
> +            "heading6": {
No problem. But the styling will not match the designs anymore. I hope that's ok.

2017-12-11 22:45 UTC, jaymejohnson commented on styleguide/source/_patterns/04-templates/01-content-types/event.json
> +            "heading6": {
The change is now pushed up.

2017-12-11 22:51 UTC, jaymejohnson commented on styleguide/source/_patterns/03-organisms/by-author/rich-text.twig
> +  {% block rteElements %}
I added it right to the template. I didn't see a place where it naturally fit in the md file, and also, I think devs would get more out of it having it right there in the twig file.

2017-12-11 22:58 UTC, jaymejohnson commented on styleguide/source/_patterns/04-templates/01-content-types/event.json
> +            "heading6": {
Note that in all three public meeting variants these are h6's. I am just going to leave those until we are extra sure.

2017-12-11 23:05 UTC, jaymejohnson commented on styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
> +        "location": "251 Causeway St., Suite 900, Boston, MA 02114",
I don't understand what you are asking me to do here. The page matches the design here.

2017-12-11 23:06 UTC, jaymejohnson commented on styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
> +          "summary": "Sunday, August 12, 2018 9:10 a.m. - Monday, August 13, 2018 9:35 a.m. "
I don't understand what you are asking me to do here. The page matches the design here.

2017-12-11 23:06 UTC, jaymejohnson commented on styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
> +          "text": "Another Optional Link",
I'm not sure if this not is for me or not. But here again, the "Another optional link" has been included because it's in the designs.

2017-12-11 23:07 UTC, jaymejohnson commented on styleguide/source/_patterns/05-pages/event~public-meeting-minutes.json
> +        "location": "251 Causeway St., Suite 900, Boston, MA 02114",
see above comments.

2017-12-11 23:07 UTC, jaymejohnson commented on styleguide/source/_patterns/05-pages/event~public-meeting-minutes.json
> +        "text":"Another Optional Link",
Ok. Sounds like I need to wait to hear back before I know whether this is something that needs changing or not then.

2017-12-11 23:10 UTC, jaymejohnson commented
@jesconstantine 
I commented specifically above where it made sense to. For the data content changes, I followed the designs on all fronts. So it sounds like maybe there is some internal discrepancies in the designs?

2017-12-12 12:17 UTC, jesconstantine commented on styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
> +        "location": "251 Causeway St., Suite 900, Boston, MA 02114",
The related event information shown on the agenda and minutes pages should reflect the meeting information from the public meeting notice page.  Specifically: 

Please update the address shown at this line of code to match the address of the public meeting notice page address:
```
Division of Fisheries and Wildlife Field Headquarters, Richard Cronin Building,\n1 Rabbit Hill Road, Westborough, MA 01966
```

2017-12-12 12:53 UTC, jesconstantine commented on styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
> +          "summary": "Sunday, August 12, 2018 9:10 a.m. - Monday, August 13, 2018 9:35 a.m. "
The related event information shown on the agenda and minutes pages should reflect the meeting information from the public meeting notice page. 

Please update the date and time shown above to match the date/time of the public meeting notice page:
```
       "eventTeaser": {
          "title": null,
          "location": "this should come from the other event, see prior comment",
          "date": {
            "summary": "Sunday, November 5, 2017"
          },
          "time": "10:00 a.m. - 11:00 a.m.",
          "description": ""
        }
```

2017-12-12 12:54 UTC, jesconstantine commented on styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
> +          "text": "Another Optional Link",
Yep thanks @jaymejohnson -- my gut tells me we'll want to remove this but let's wait for @cmajel or @cjbowes to chime in.

2017-12-12 12:57 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-author/rich-text.twig
> +  {% block rteElements %}
@jaymejohnson Can we add a new section to the md file for this content?  This is an update that we're going to start to see more often in mayflower patterns.  I think it makes sense to find a home for it in the documentation and to reference it from the twig template.

2017-12-12 18:53 UTC, jaymejohnson commented on styleguide/source/_patterns/03-organisms/by-author/rich-text.twig
> +  {% block rteElements %}
Moved it into the .md file.

2017-12-12 18:56 UTC, jaymejohnson commented on styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
> +        "location": "251 Causeway St., Suite 900, Boston, MA 02114",
Fixed.

2017-12-12 18:57 UTC, jaymejohnson commented on styleguide/source/_patterns/05-pages/event~public-meeting-agenda.json
> +          "text": "Another Optional Link",
I removed it. It's super easy to put back if we want to.

2017-12-12 18:57 UTC, jaymejohnson commented on styleguide/source/_patterns/05-pages/event~public-meeting-minutes.json
> +        "location": "251 Causeway St., Suite 900, Boston, MA 02114",
Fixed.

2017-12-12 18:57 UTC, jaymejohnson commented on styleguide/source/_patterns/05-pages/event~public-meeting-minutes.json
> +        "text":"Another Optional Link",
Fixed!

2017-12-12 19:05 UTC, jaymejohnson commented
@jesconstantine I think I got all the changes you requested now. :) 
The changes are pushed up to my dev site. 
https://jaymejohnson.github.io/mayflower/?p=pages-event-public-meeting
https://jaymejohnson.github.io/mayflower/?p=pages-event-public-meeting-agenda
https://jaymejohnson.github.io/mayflower/?p=pages-event-public-meeting-minutes

2017-12-12 20:13 UTC, jesconstantine approved these changes
Great work @jaymejohnson I think this is ready to go!

2017-12-12 20:14 UTC, merged