DP-5817 rules of court
massgov/mayflower-patternlab pull request #651
Opened 2017-11-30 14:38 UTC by jaymejohnson

This PR is for work on the Rules of Court content type and related elements. It should be considered a WIP PR until updated to say otherwise. 

The definition of done can be found here: https://jira.state.ma.us/browse/DP-5817

## Steps to Test

QA steps, when they exist will be written in the original ticket, here: https://jira.state.ma.us/browse/DP-5817

2017-12-01 00:12 UTC, jesconstantine reviewed
@jaymejohnson - off to a great start here!  I think my comments here address some of your questions from slack.

I also think we an remove any work re: accordion-content and collapsible-header -- that was just POC code that I was playing around with, nothing that should be deployed.  I also see some work related to other page types here - curious what that's about?

Let me know if you have any questions.  Thanks!

2017-12-01 00:12 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/01-content-types/court-rules.md
> +### JavaScript Used
@jaymejohnson - We should mention the javascript for adding heading anchor tags and also heading indentation here

2017-12-01 00:12 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/01-content-types/court-rules.twig
> +      <div class="page-content js-insert-heading-anchors js-outline-indent">
I believe we were talking about scoping these 2 js classes at the `@organisms/by-author/rich-text` level as opposed to hard coding them here in the template.  Maybe it could look like 2 new variants of the rich text organism which each key off of a new boolean property that we'll be sure to set for the court rules content type and page patterns.

That way the rich text js module can also be cleaner and not have to crawl up the DOM for a parent class.

2017-12-01 00:12 UTC, jesconstantine commented on styleguide/source/_patterns/05-pages/court-rules~with-indentation.json
> +        "title": "with Indentation",
What do you think about using this data structure for the court-rules.json page data instead of adding this page variant / version?

2017-12-01 00:12 UTC, jesconstantine commented on styleguide/source/assets/js/helpers/headerAnchorLinks.js
> +  $('.js-insert-heading-anchors').each(function(){
If we scope this class to the rich text organism, should this JS live there as well?  Do you think there's value in having this class applied to other patterns?  I can't think of many that would need it because most will have an id... thoughts?

2017-12-01 00:12 UTC, jesconstantine commented on styleguide/source/assets/js/modules/richText.js
> +    if ($el.parents('.js-outline-indent').length) {
If we make this class scoped to rich text, then we can just check for this class on the element itself which is cleaner.

2017-12-01 00:23 UTC, jaymejohnson commented
> I also think we an remove any work re: accordion-content and collapsible-header -- that was just POC code that I was playing around with, nothing that should be deployed.

Oops. I thought that those were new patterns at first, so they slipped past me.

>  I also see some work related to other page types here - curious what that's about?

I have no idea! Hahahaha. It came in with merges. I thought if I pulled down the upstream and merged it into my feature branch this other stuff would go away, but it didn't...

2017-12-01 16:27 UTC, jaymejohnson commented
- [] I also think we an remove any work re: accordion-content and collapsible-header -- that was just POC code that I was playing around with, nothing that should be deployed

2017-12-01 17:28 UTC, jaymejohnson commented on styleguide/source/_patterns/05-pages/court-rules~with-indentation.json
> +        "title": "with Indentation",
I thought it felt redundant to have both pages anyway. I'm adding this to my checklist below.

2017-12-01 17:32 UTC, jaymejohnson commented on styleguide/source/assets/js/helpers/headerAnchorLinks.js
> +  $('.js-insert-heading-anchors').each(function(){
If we could know for certain that we would never be able to use it anywhere else, I'd say scope it to the rich-text organism. But for now, the idea of having it at least available to other patterns if we would need it seems better than having a future developer have to reverse engineer what we did and pull it out again anyway. That's my thinking on it right now, anyway.

2017-12-04 16:55 UTC, jaymejohnson commented
This is ready for review, @jesconstantine. :)

2017-12-05 12:16 UTC, jesconstantine requested changes
This is great work @jaymejohnson !!  I wrote several small comments that I think we can breeze through together and then this will be good to go!  Let me know how I can help.  Thanks :)

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-author/rich-text.twig
> +{% set headerIndent =  richText.headerIndent ? 'js-insert-heading-anchors js-outline-indent' : '' %}
@jaymejohnson are you having the `richText.headerIndent` property add both a `js-outline-indent` and the `js-insert-heading anchors` classes intentionally here?  I think we'll need a separate property and separate local variable for the anchor tags functionality.

Also - please update the documentation `.md` file associated with this pattern with the new variable(s) and their usage guidelines.

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-template/page-header.twig
> +      {% set compHeading = pageHeader.subCategory.compHeading %}
@jaymejohnson this seems like an instance where we will always know what level of heading we want to use - what do you think?  could we set a default value here in the twig?

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-template/page-header.md
> +    subcategory:
Please bump this indentation out to be a sibling to `category` and please also update the capitalization to `subCategory`

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-template/page-header.md
> +    type: string / optional,
I think this type should be `Comp Heading` instead of `string` right?

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-template/page-header~for-court-rules.json
> +      "compHeading": {
I'm not sure we need to retain the `compHeading` property - could we namespace it with `subCategory` like you have here but just have the properties of a `compHeading` nested directly under?  That seems to be the pattern that we follow - so long as we document this in the `.md` file and we update the variable assignment accordingly.

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-template/page-header~for-court-rules.json
> +        "path": "@atoms/11-text/paragraph.twig",
I think the pattern that [we've established for similar instances of this description text](https://github.com/massgov/mayflower/blob/dev/styleguide/source/_patterns/04-templates/01-content-types/policy-advisory.json#L38) is to have this paragraph text contained in a rich text organism, so the data structure would be: `pageHeader.optionalContents[].path` set to the rich text twig and `pageHeader.optionalContents[].data` set to the `richText` data structure which would contain this paragraph `path` and `data` here.

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-template/page-header~for-court-rules.md
> +* Set subCategory to null if no subCategory is desired, otherwise set the compHeading title.
Thanks for adding these docs!  I think we want more than just the title populated, please update this documentation line to something like: "Set the `subCategory` variable to null (if no sub category is needed) or populate it with the variables for a `compHeading`"

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/01-content-types/court-rules.json
> +        "path": "@atoms/11-text/paragraph.twig",
Just noting another occurrence of this data structure where we want to contain this paragraph in a rich text organism.

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/01-content-types/court-rules.md
> +* Anchor tags (js/helpers/headerAnchorLinks.js)
Can we add a little more context here by saying something like: "Anchor tags for headings within rich text"

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/_patterns/04-templates/01-content-types/court-rules.twig
> +          {#{% include "@base/placeholder.twig" with {'placeholder':{'text':'Page Content'}} %}#}
Let's leave this placeholder uncommented so implementers know there's a block in which they can add other patterns.

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/_patterns/05-pages/rules-of-court.twig
> +
Please add an empty block for page content here: `{% block pageContent %}{% endblock %}`

(See https://github.com/massgov/mayflower/blob/dev/styleguide/source/_patterns/05-pages/policy-advisory-directive.twig#L7 for an example)

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/assets/js/helpers/headerAnchorLinks.js
> +  $('.js-insert-heading-anchors').each(function(){
I'm not sure we'd need this for headings outside of rich text (because most heading patterns have `id` variables.  So I think we should move this js into rich text js - what do you think?

I also think we need to add a separate local variable `headingAnchors` to the rich text twig template which is empty by default but can be populated with the appropriate js class when a config boolean value on rich text data structures is set to true: `richText.headingAnchors`

What do you think?

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/assets/js/helpers/headerAnchorLinks.js
> +    function slugify(text)
Please move this function to it's own helper file

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/assets/js/modules/richText.js
> +    // Allow heading and contents to be indented.
Please add a little more context to this comment which mentions the relationship between this js and the scss

2017-12-05 12:16 UTC, jesconstantine commented on styleguide/source/assets/scss/03-organisms/_rich-text.scss
> +      margin-left: 20px;
Please set a local sass variable here set to the value of `$gutter` (see: https://github.com/massgov/mayflower/blob/dev/styleguide/source/assets/scss/00-base/_variables.scss#L3) and use that instead of hard coding pixels in this line and in the following lines.

2017-12-05 18:18 UTC, jaymejohnson commented on styleguide/source/assets/js/helpers/headerAnchorLinks.js
> +  $('.js-insert-heading-anchors').each(function(){
I agree. This has been changed and pushed.

2017-12-05 18:49 UTC, jaymejohnson commented on styleguide/source/_patterns/03-organisms/by-author/rich-text.twig
> +{% set headerIndent =  richText.headerIndent ? 'js-insert-heading-anchors js-outline-indent' : '' %}
You are right, they are definitely better separated. I guess I was thinking that there probably wouldn't be a need for the one without the other. At any rate, this has been fixed and pushed. An update to the `rich-text.md` file has also been pushed up.

2017-12-05 18:54 UTC, jaymejohnson commented on styleguide/source/_patterns/03-organisms/by-template/page-header.md
> +    subcategory:
Fixed.

2017-12-05 18:54 UTC, jaymejohnson commented on styleguide/source/_patterns/03-organisms/by-template/page-header.md
> +    type: string / optional,
Fixed.

2017-12-05 19:50 UTC, jaymejohnson commented on styleguide/source/_patterns/03-organisms/by-template/page-header~for-court-rules.json
> +        "path": "@atoms/11-text/paragraph.twig",
Fixed.

2017-12-05 20:44 UTC, jaymejohnson commented on styleguide/source/_patterns/03-organisms/by-template/page-header.twig
> +      {% set compHeading = pageHeader.subCategory.compHeading %}
@jesconstantine 
I changed it to this:
```{% if pageHeader.subCategory %}
      {% set compHeading = pageHeader.subCategory %}
      {% include "@atoms/04-headings/comp-heading.twig" %}
    {% endif %}
```

Is that what you had in mind? And then I changed the data structure for
`page-header~for-court-rules.json` as follows:

```
 "subCategory": {
        "title": "Rule of Court Optional Sub-category",
        "level": 3,
        "color": "",
        "id": "",
        "centered": ""
    },
```

2017-12-05 20:44 UTC, jaymejohnson commented on styleguide/source/_patterns/03-organisms/by-template/page-header~for-court-rules.json
> +      "compHeading": {
See above comment.

2017-12-05 20:46 UTC, jaymejohnson commented on styleguide/source/_patterns/03-organisms/by-template/page-header~for-court-rules.md
> +* Set subCategory to null if no subCategory is desired, otherwise set the compHeading title.
Fixed.

2017-12-05 20:47 UTC, jaymejohnson commented on styleguide/source/_patterns/04-templates/01-content-types/court-rules.json
> +        "path": "@atoms/11-text/paragraph.twig",
I think I fixed this when I fixed the others.

2017-12-05 20:53 UTC, jaymejohnson commented on styleguide/source/_patterns/04-templates/01-content-types/court-rules.md
> +* Anchor tags (js/helpers/headerAnchorLinks.js)
Fixed. Also, I changed the path to reflect the fact that functionality for this lives in `rich-text.js `

2017-12-05 21:14 UTC, jaymejohnson commented on styleguide/source/_patterns/04-templates/01-content-types/court-rules.twig
> +          {#{% include "@base/placeholder.twig" with {'placeholder':{'text':'Page Content'}} %}#}
Fixed. I restored all the placeholders in that file while I was at it.

2017-12-05 21:19 UTC, jaymejohnson commented on styleguide/source/_patterns/05-pages/rules-of-court.twig
> +
Fixed.

2017-12-05 22:51 UTC, jaymejohnson commented on styleguide/source/assets/js/helpers/headerAnchorLinks.js
> +    function slugify(text)
Fixed.

2017-12-05 23:25 UTC, jaymejohnson commented on styleguide/source/assets/scss/03-organisms/_rich-text.scss
> +      margin-left: 20px;
Fixed.

2017-12-06 12:32 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-template/page-header.twig
> +      {% set compHeading = pageHeader.subCategory.compHeading %}
For the part about restructuring the data that's exactly what I meant.

For the part about having the `pageHeader` be opinionated with a `subCategory.level` default value, I meant setting a default in twig (which could be overridden in json - by implementers).

I just pushed up a commit with this update: https://github.com/massgov/mayflower/pull/651/commits/d75080c255219d6a33782eb81d3e1f11c0799a92

2017-12-06 12:33 UTC, jesconstantine commented on styleguide/source/assets/scss/03-organisms/_rich-text.scss
> +      margin-left: 20px;
Nice.  I just realized we were hard coding a scope for the ability to use these js / css hooks for outline indentation.  Fixed in https://github.com/massgov/mayflower/pull/651/commits/6501f09ee7ae700001e7a9cf7db7ce5aced9516e

2017-12-06 12:36 UTC, jesconstantine commented on styleguide/source/_patterns/02-molecules/listing-table.twig
> +          {# Backwards compatible with 5.8.x where listingTable.rows array item objects expect label and text properties instead of a label and an "items" array. #}
@gleroux02 Just wanted you to see that this new show/hide functionality of the listing table pattern is non-breaking.  We do require a new data structure to use the new functionality, but the old data structure will still work just as it always did.

2017-12-06 12:37 UTC, jesconstantine commented on styleguide/source/_patterns/03-organisms/by-author/rich-text.md
> +  },
@gleroux02 in order to get the anchor links and outline indentation for the rules of court content type, when you pass the `richText` data structure for the necessary fields, set these new variables to true.

2017-12-06 14:18 UTC, jesconstantine approved these changes
@jaymejohnson IMO this is ready to go!

Wondering if you or @gleroux02 (whoever has time!) could just take a look at my 3 commits on top of your branch which I mentioned in our comment dialogue:

RE: letting page header pattern be opinionated about what level that compHeading pattern should be (but also overridable): https://github.com/massgov/mayflower/commit/d75080c255219d6a33782eb81d3e1f11c0799a92

RE: Allowing any page type to implement rich text with outline indentation: https://github.com/massgov/mayflower/commit/6501f09ee7ae700001e7a9cf7db7ce5aced9516e and refactored to fold into existing rich text heading styles (and to resolve a sass compile error) https://github.com/massgov/mayflower/commit/2eefa5f31457a7270f6bd83b197348c46a4be718

Once either of you is happy with those commits, we can squash and merge!!

2017-12-06 17:33 UTC, jaymejohnson commented
Looks good. Let's ship it!

2017-12-06 18:37 UTC, merged