DP-7193
massgov/mayflower-patternlab pull request #667
Opened 2018-01-04 17:33 UTC by isaacchansky

## Description

Contact list accordions' contact groups only stack, so on wider widths this looks funny. This PR adds a flexbox layout to the content within contact me accordions, which works at any accordion width.  

## Related Issue / Ticket

- [JIRA issue](https://jira.state.ma.us/browse/DP-7193)

## Steps to Test

1. View comp: https://projects.invisionapp.com/share/VNEV7ARM5#/screens/268281226
2. Run locally or view hosted PR here: http://www.isaacchansky.com/mayflower/?p=organisms-contact-list
3. Ensure that things look right at each any viewport width (note: comp only displays desktop)
4. Ensure that this does not mess with other content groups at all viewport widths
    - http://www.isaacchansky.com/mayflower/patterns/05-pages-executive-order/05-pages-executive-order.html 
    - http://www.isaacchansky.com/mayflower/patterns/05-pages-howto/05-pages-howto.html
    - http://www.isaacchansky.com/mayflower/patterns/05-pages-site-alert/05-pages-site-alert.html

## Screenshots
![contact-list](https://user-images.githubusercontent.com/1397914/34576231-3c5a2398-f14b-11e7-9f25-e999d6716ea0.gif)

## Additional Notes:

#### Impacted Areas in Application

* molecule/contact-us
* organism/contact-list

#### @TODO

*

#### Today I learned...

2018-01-11 22:56 UTC, tnathanjames approved these changes
Looks good to me.

2018-01-17 19:19 UTC, iansholtys requested changes
Found some margin/padding quirks.

Also, while I couldn't find a contextual place to post the comments, margin/padding is off when Contact Lists are used in sidebars. At desktop resolutions they're fine, but when the sidebar becomes full-width and contact items go into columns, things aren't quite right. There's no space between the individual items, and second+ items have padding on top which causes them to be misaligned.

2018-01-17 19:19 UTC, iansholtys commented on styleguide/source/assets/scss/02-molecules/_contact-us.scss
> -    padding: 0 20px 30px;
Removal of these padding rules is causing issues for the organism in general at mobile resolutions (there's no padding at the bottom) and for implementations which have a more info link at all resolutions. A screenshot of the latter is attached below.

<img width="634" src="https://user-images.githubusercontent.com/18170074/35060809-72bb268e-fb8d-11e7-8977-e23ea1c54d69.png">

It doesn't appear to be broken on http://www.isaacchansky.com/mayflower/patterns/05-pages-howto/05-pages-howto.html but I'm not convinced this has been properly updated; rules (such as this one) which are clearly removed from the PR are still showing up in the Inspector.

Related to the refactoring of margins and padding, there's substantially more vertical space between Contact List items on the How To page at a bunch of resolutions (one example, when the window is ~1200px wide) and it looks a bit off to me.

2018-01-18 15:27 UTC, isaacchansky commented
@iansholtys I refactored a bit and think got things working in a better way - If the contact list in the sidebar is still an issue can you provide a link to where you're seeing it? thanks!

2018-01-18 15:35 UTC, iansholtys commented
@isaacchansky, your changes resolve a lot of issues I had with margin and padding, with the exception of the contact list when used in the sidebar. You can see it on the Site Alert Page at mobile and desktop resolutions: http://localhost:3000/?p=pages-site-alert

Screenshot attached.

<img width="409" src="https://user-images.githubusercontent.com/18170074/35105995-127b2324-fc3b-11e7-8111-c031144c4e93.png">

2018-01-19 03:30 UTC, iansholtys commented
@isaacchansky, that takes care of the issues at desktop resolution, though when the sidebar goes full-width under the main content and the Contact Groups are side-by-side, the `.ma__contact-group + .ma__contact-group {padding-top: 20px}` is causing them to be misaligned. That said, if there are >2 items and they wrap onto a second line, having space between them is important... the best fix I've been able to come up with is to use padding- or margin-top on each contact group, then using the same amount of negative margin-top on `.ma__contact-us__content-wrap` to offset it. Maybe I'm missing an easier fix, though.

2018-01-23 15:56 UTC, iansholtys approved these changes

2018-01-23 15:57 UTC, iansholtys commented
All the issues I noticed have been resolved.

2018-01-24 20:38 UTC, merged