DP-7307 & DP-7483 organization image links
massgov/mayflower-patternlab pull request #670
Opened 2018-01-12 16:55 UTC by isaacchansky

## Description

Create new Image Link molecule with block variant and Image Link List organism for use on the service page 'offered by' section within the sidebar, or as a stacked row item on the Organization Elected Official page.

## Related Issue / Ticket

- [DP-7307](https://jira.state.ma.us/browse/DP-7307)
- [DP-7483](https://jira.state.ma.us/browse/DP-7483)

## Steps to Test

1. View invision file https://projects.invisionapp.com/share/VYF2N5JX2#/screens/270254806
2. Confirm that the service page 'Offered By' section looks as expected: https://mayflower.digital.mass.gov/?p=pages-service 
3. View invision file https://projects.invisionapp.com/share/VYF2N5JX2#/screens
4. Confirm that the organization elected official page 'Our Organizations' section looks as expected

## Screenshots
You can see these two organisms in action here:
http://www.isaacchansky.com/mayflower/?p=pages-organization-elected-official
and here:
http://www.isaacchansky.com/mayflower/?p=pages-service

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* new `molecules/image-link`
* new `organisms/image-link-list`
* change `templates/content-types/services` to use image-link-list instead of link-list
* add to `pages/organization-elected-official` to include image-link-list for 'our organizations' section

#### @TODO

* 

#### Today I learned...

2018-01-23 21:09 UTC, tnathanjames commented on styleguide/source/_patterns/03-organisms/by-author/logo-link-list.twig
> +        {% for logoLink in logoLinkList.links %}
Missing indent here.

2018-01-23 21:12 UTC, tnathanjames commented on styleguide/source/_patterns/02-molecules/logo-link.json
> +        "src":"../../assets/images/placeholder/250x250.png",
Indent 2 spaces instead of 4.

2018-01-23 21:12 UTC, tnathanjames requested changes
A couple quick indention corrections.

2018-01-24 20:22 UTC, clair0917 commented on styleguide/source/_patterns/04-templates/01-content-types/services.json
> +      },{
add a carriage return

2018-01-24 20:23 UTC, clair0917 commented on styleguide/source/assets/scss/03-organisms/_link-list.scss
> +
extra line

2018-02-08 15:19 UTC, clair0917 approved these changes
looks good to me

2018-02-08 15:40 UTC, tnathanjames approved these changes

2018-02-08 15:42 UTC, merged