DP-6181 [a11y] Add supplemental info to phone and email links for screen readers
massgov/mayflower-patternlab pull request #680
Opened 2018-01-29 20:57 UTC by ygannett

## Description

When screen reader users browse a page from link to link and hit contact information such as phone numbers and email addresses, they don't get what those links are for.  To support that, add their contact name as hidden text only read by screen readers to phone number and email links.

## Related Issue / Ticket

- [DP-6181 ]A11y use aria-label to provide additional text to screen reader user for phone and email links()

## Steps to Test

1. 

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

#### Today I learned...

2018-02-21 19:46 UTC, rbayliss requested changes

2018-02-21 19:46 UTC, rbayliss commented on styleguide/source/_patterns/02-molecules/contact-group.json
> +    "contactName": "",
Does this need addition to the markdown file?

2018-02-21 19:46 UTC, rbayliss commented on styleguide/source/_patterns/02-molecules/contact-group~as-fax.json
> +    "contactName": "",
Needs addition to markdown file?

2018-02-21 19:46 UTC, rbayliss commented on styleguide/source/_patterns/02-molecules/contact-us.json
> +    "contactName": "",
Needs addition to markdown file?

2018-02-21 19:46 UTC, rbayliss commented on styleguide/source/_patterns/02-molecules/contact-group~as-online.json
> +    "contactName": "",
Needs addition to markdown file?

2018-02-28 14:53 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/contact-group.json
> +    "contactName": "",
Thank you for catching this.  I missed that.  I took care of all related md files.

2018-02-28 18:39 UTC, clairesunstudio commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +          {% if contactGroup.name == "Phone" %}<span class="visually-hidden">Call {{ contactName }}{% if item.label %}, {{item.label}} {% endif %}at </span>
contactName should be contactGroup.contactName

2018-02-28 19:06 UTC, rbayliss commented on styleguide/source/_patterns/02-molecules/contact-group.md
> +    type: string / required
@ygannett - I'm sorry I didn't catch this sooner.  Is this property a hard requirement for accessibility?  Asking because adding a new required property here might be a bigger deal.

2018-03-13 14:28 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/contact-group.md
> +    type: string / required
@rbayliss Yes, missing contactName data is the reason to fail accessibility test.

2018-03-13 20:06 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/contact-group.twig
> +          {% if contactGroup.name == "Phone" %}<span class="visually-hidden">Call {{ contactName }}{% if item.label %}, {{item.label}} {% endif %}at </span>
@clairesunstudio It's set at L. 42 in 02-molecules/contact-us.twig.  If the setup is not proper, please let me know.

2018-03-19 18:14 UTC, ygannett commented on styleguide/source/_patterns/02-molecules/contact-group.md
> +    type: string / required
@rbayliss Thank you for the explanation.  I made the change to "optional".  Would you take a look again?

2018-03-19 19:52 UTC, rbayliss approved these changes

2018-03-19 20:00 UTC, merged