DP-7622  mayflower for information details page
massgov/mayflower-patternlab pull request #690
Opened 2018-02-08 14:56 UTC by clair0917

DP-7622 Mayflower for information details page without JS

## Description
PR adds a template for the information details content type, a pullquote component and a js fullWidth image treatment. 

## Steps to Test
Review the Information Details page here: 
https://clair0917.github.io/mayflower/?p=pages-information-details

inVision designs can be found here: 
https://jira.state.ma.us/browse/DP-7282

2018-02-28 22:28 UTC, isaacchansky requested changes
Looks good! Just a few comments

2018-02-28 22:28 UTC, isaacchansky commented on styleguide/source/assets/js/modules/imageFill.js
> +  console.log(sidebarHeight);
remove console log

2018-02-28 22:28 UTC, isaacchansky commented on styleguide/source/assets/scss/03-organisms/_pullquote.scss
> +    background-color: green;
Should this be $c-theme-green?

2018-03-05 14:03 UTC, clair0917 commented on styleguide/source/assets/js/modules/imageFill.js
> +  console.log(sidebarHeight);
this log has been removed with the PR for DP-7766

2018-03-05 15:32 UTC, isaacchansky approved these changes

2018-03-05 15:34 UTC, merged