DP 7341  add about pattern for elected officials
massgov/mayflower-patternlab pull request #730
Opened 2018-03-14 15:32 UTC by clair0917

## Description
Adds a person card organism and an About section organism for use on elected officials pages

## Related Issue / Ticket

- [JIRA issue](https://jira.state.ma.us/browse/DP-7341)

## Steps to Test
1. View the [circular image atom](https://clair0917.github.io/mayflower/?p=atoms-image-circular) here
2. View the [person card organism](https://clair0917.github.io/mayflower/?p=organisms-person-card) here
3. View [the organization elected official page](https://clair0917.github.io/mayflower/?p=pages-organization-elected-official) to see about section in place

## Screenshots
![about-section](https://user-images.githubusercontent.com/18662734/37412254-f2b3b676-277a-11e8-88d4-c3166ee4924e.jpg)

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application
* Image Atom
* Organization Elected Officials Page

2018-03-21 18:14 UTC, isaacchansky approved these changes
Overall looks good!

One question about using `rem` instead of `px`, and in general if you think we can use `rem` for spacing/sizing of things, but leaving the decision up to you.

2018-03-21 18:14 UTC, isaacchansky commented on styleguide/source/assets/scss/06-theme/03-organisms/_about-section.scss
> +      margin: 5px 0 2.5rem;
do you think we can use rem instead of pixels here?

2018-03-21 18:43 UTC, gender404 requested changes
The BEM syntax is incorrect and could use some fixes.

I'm lurking in the slack channel (Jonathan Dallas) if you have questions.

2018-03-21 18:43 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/person-card.twig
> +  <div class="ma__person-card--wrapper">
In correct BEM syntax => `ma__person-card--wrapper` would be a modifier not a block element

I'm guessing you wanted ma__person-card`__wrapper`.  Otherwise the modifier should be added to the element with the same base class `class="ma__person-card ma__person-card--wrapper`

2018-03-21 18:43 UTC, legostud commented on styleguide/source/_patterns/03-organisms/by-author/person-card.twig
> +      <div class="ma__person-card--title">
should be `__title`

2018-03-21 18:43 UTC, gender404 commented on styleguide/source/assets/scss/01-atoms/_image.scss
> +}
missing line-ending

2018-03-21 18:43 UTC, gender404 commented on styleguide/source/assets/scss/03-organisms/_person-card.scss
> +  .ma__person-card--wrapper {
The purpose of BEM syntax is to avoid the nesting the of classes to keep all elements to a single class of specificity.  Also as mentioned before this should be `&__wrappper`

syntax would then be 
```
.ma__person-card { 
&__wrapper { ... }
...
}
```

2018-03-21 18:43 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_person-card.scss
> +    .ma__person-card--name {
Same issue as `--wrapper`

2018-03-21 18:43 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_person-card.scss
> +    .ma__person-card--title {
same issue as `--wrapper`

2018-03-21 18:43 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_person-card.scss
> +}
missing line ending - add an extra line-break.

2018-03-21 18:43 UTC, legostud commented on styleguide/source/assets/scss/06-theme/03-organisms/_about-section.scss
> +    .ma__about-section__content-container {
I think this would just be `&__content-container` outside of the `&__content` selector

2018-03-21 18:43 UTC, legostud commented on styleguide/source/assets/scss/06-theme/03-organisms/_about-section.scss
> +    .ma__about-section__content-text {
`&__content-text` outside of `&__content`  unless there is a reason why you need it to be `.ma__about-section__content .ma__about-section__content-text` at which point you can do `&__content &__content-text`

2018-03-21 18:43 UTC, legostud commented on styleguide/source/assets/scss/06-theme/03-organisms/_about-section.scss
> +      margin: 5px 0 2.5rem;
rem seems a bit off.  I could see ems if the spacing needs to change based on the items font-size.

2018-03-21 18:43 UTC, legostud commented on styleguide/source/assets/scss/06-theme/03-organisms/_about-section.scss
> +  .ma__person-card {
placement seems a bit random to me.  I'm worried this override will get lost among the other selectors.  Not sure if there is a better placement.

2018-03-23 13:28 UTC, clair0917 commented on styleguide/source/assets/scss/06-theme/03-organisms/_about-section.scss
> +  .ma__person-card {
My thought process was that this placement is about the layout of the about section, not the person card. Since these styles have no affect on the person card, I thought this was the most logic place to put it.

2018-03-23 14:29 UTC, legostud commented on styleguide/source/assets/scss/06-theme/03-organisms/_about-section.scss
> +  .ma__person-card {
makes sense.

2018-03-23 14:33 UTC, gender404 requested changes
much better.  Just two more potential tweaks.

2018-03-23 14:33 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_person-card.scss
> +    .ma__person-card__name {
I don't understand why this needs to be nested within `&__person-info`.  I think it could be at the root level `&__name` instead.

2018-03-23 14:33 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_person-card.scss
> +    .ma__person-card__title {
I don't understand why this needs to be nested within `&__person-info`.  I think it could be at the root level `&__title` instead.

2018-03-23 15:09 UTC, merged