Dp 8290 add clear all to filters
massgov/mayflower-patternlab pull request #735
Opened 2018-03-16 21:27 UTC by clairesunstudio

Any PRs being created needs a changelog.txt file before being merged into dev. See: [Change Log Instructions](https://github.com/massgov/mayflower/blob/dev/docs/change-log-instructions.md)

## Description

Adds optional clearAll button to PressFilters for search
## Related Issue / Ticket

- [JIRA issue ](https://jira.state.ma.us/secure/RapidBoard.jspa?rapidView=2841&view=detail&selectedIssue=DP-8290)
- [Github issue]()

## Steps to Test

1.  Standup localhost and go to http://localhost:3000/?p=organisms-press-filters

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.
<img width="1035" alt="screen shot 2018-03-16 at 5 25 43 pm" src="https://user-images.githubusercontent.com/5789411/37545440-37f242c8-293f-11e8-9219-2ac462c107a4.png">

2018-03-20 14:08 UTC, avrilpearl requested changes
Looks good, have a few changes in there relating to accessibilty

2018-03-20 14:08 UTC, avrilpearl commented on styleguide/source/_patterns/03-organisms/by-author/press-filters.json
> +      "text": "Clear all filters"
for accessibility, add info element here that can be passed to aria-label (similar to button atom)

2018-03-20 14:08 UTC, avrilpearl commented on styleguide/source/_patterns/03-organisms/by-author/press-filters.md
> +      type: string / optional
add info here per comment above

2018-03-20 14:08 UTC, avrilpearl commented on styleguide/source/_patterns/03-organisms/by-author/press-filters.twig
> +        <button type="button" class="ma__press-filters__clear js-press-filters-clear">{{pressFilters.clearButton.text}}</button>
add `aria-label="{{ pressFilters.clearButton.info }}`

2018-03-21 14:22 UTC, avrilpearl approved these changes
looks good now!

2018-03-21 14:22 UTC, merged

2018-03-21 14:52 UTC, legostud commented on styleguide/source/assets/scss/03-organisms/_press-filters.scss
> +      border-bottom-width: 3px;
Sorry, I'm a little late on this comment.  This CSS is a bit confused.  

`border-bottom: 3px solid transparent;` and then you immediately override the width to be `border-bottom-width: 1px;` instead of just setting it as 1px to start with `border-bottom: 1px solid transparent;`.

I would also suggest not setting the color at all to avoid specificity issues:
`border-bottom-style: solid;`
`border-bottom-width: 1px;`

If you set the color to `transparent` then the selector in the theme file has to have the same specificity to override the `transparent` color.  If you omit it the color, then the specificity doesn't have to match making it much easier to set in the theme files.