Dp 7766  mayflower for information details page toc sticky js
massgov/mayflower-patternlab pull request #737
Opened 2018-03-20 20:58 UTC by clair0917

## Description
Adds a sticky table fo contents with required patterns for Information details pages

## Related Issue / Ticket

- [DP-7766](https://jira.state.ma.us/browse/DP-7766)
- [Github issue]()

## Steps to Test
1. Go to [github page](https://clair0917.github.io/mayflower/?p=pages-information-details-table-of-contents) to view working sticky TOC

## Screenshots
<img width="1547" alt="screen shot 2018-03-20 at 4 57 55 pm" src="https://user-images.githubusercontent.com/18662734/37682415-e2c43166-2c5f-11e8-916a-d3f9492da0fd.png">

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application
* Created Sticky Table of Contents pattern 
* Updated info details template for sticky TOC

2018-03-21 18:25 UTC, isaacchansky requested changes
Just a few comments & needs merge conflict resolution

2018-03-21 18:25 UTC, isaacchansky commented on styleguide/source/assets/js/modules/imageFill.js
> +  const sidebarHeight = $('.sidebar').outerHeight( true ) + 100;
This could use a comment as to where 100 comes from

2018-03-21 18:25 UTC, isaacchansky commented on styleguide/source/assets/js/modules/stickyTOC.js
> +          $tocSections = $('.ma__information-details__content, .ma__link-list').find('h2'),
Is this 100% always an `h2`? I know some components can have a level param passed to them.

2018-03-22 15:49 UTC, clair0917 commented on styleguide/source/assets/js/modules/stickyTOC.js
> +          $tocSections = $('.ma__information-details__content, .ma__link-list').find('h2'),
This is certainly a discussion that needs to be had again. For now the stickyTOC is only in the info details template and the h2s work, but it they want to use the for other pages it will require some lite refactoring .

2018-03-22 15:51 UTC, clair0917 commented
Comments and merge conflicts have been addressed

2018-03-22 15:51 UTC, isaacchansky commented on styleguide/source/assets/js/modules/stickyTOC.js
> +          $tocSections = $('.ma__information-details__content, .ma__link-list').find('h2'),
Sounds good for now then!

2018-03-22 15:54 UTC, isaacchansky approved these changes

2018-03-22 15:54 UTC, merged