[TEST] DP-8362 Update most/all Mayflower icons to use the Twig icon() function
massgov/mayflower-patternlab pull request #764
Opened 2018-04-04 18:18 UTC by ygannett

Replace the svg icon templates and the template calls with the icon() function.

## Description

## Related Issue / Ticket

- [DP-8362 Update most/all Mayflower icons to use the Twig icon() function](https://jira.state.ma.us/browse/DP-8362)

## Steps to Test

1. 

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

#### Today I learned...

2018-04-10 13:46 UTC, rbayliss commented on styleguide/source/_patterns/03-organisms/by-author/action-card.twig
> +          {{ icon('action.icon') }}
This is the problem, @ygannett.  There is no icon called `action.icon`.  I think you want `{{ icon(action.icon) }}` - no quotes.

2018-04-16 18:18 UTC, rbayliss commented
@clairesunstudio @isaacchansky - Just wanted to give you guys a heads up this is coming down the pipe - it's the followup to the icon work that was done on download links a couple weeks ago.  Most notably, we're removing the Twig templates for the icons here.  This may or may not be a BC break, depending on how we're thinking about it.  We still have BC layers in place so that if you try to pass one of the old names (eg: `@atoms/05-icons/svg-phone.twig`) into the `icon` function, it'll map directly to the SVG file, so this shouldn't cause breakage on the Drupal site.

I'd like to get this merged and shipped as soon as we can.  Are you ok with this going out in a minor release in its current state, or should we restore the legacy icon Twig templates until the next major?

2018-04-16 19:29 UTC, isaacchansky commented
I'm good with this going out in a minor release

2018-04-18 12:43 UTC, rbayliss commented
This looks great!  I think we're ready for @mrossi113's review here.  Melissa, this is the Mayflower PR, which can be pulled into the Drupal PR (https://github.com/massgov/mass/pull/2128) using `composer require massgov/mayflower-artifacts:dev-DP-8362_svg-opt-r2`.

2018-04-18 12:44 UTC, rbayliss approved these changes

2018-04-18 12:47 UTC, rbayliss commented
Actually, I just had a thought, which is that removing the icon Twig templates could cause us some heartache on deployment.  If we had to revert the Drupal PR for any reason, we'd also have to revert the Mayflower update (and any other PRs that depend on the Mayflower update).  I don't think we want to put ourselves in that situation, so I'm going to restore the Twig files, which we can remove in a followup.

2018-04-18 13:20 UTC, mrossi113 commented
@rbayliss is this good to review now?

2018-04-18 13:22 UTC, rbayliss commented
@mrossi113, yeah.  It's failing on an unrelated change that I'm working out now.  Whatever the fix ends up being, it shouldn't impact the functionality here.

2018-04-18 14:28 UTC, mrossi113 requested changes
The generic icon seems to be appearing in multiple location within Drupal. I will add comments to each section in this PR.

2018-04-18 14:30 UTC, mrossi113 commented
How-To the How to apply section
![screen shot 2018-04-18 at 10 17 19 am](https://user-images.githubusercontent.com/19477691/38938342-49be2440-42f3-11e8-95ee-9ccf70fcd7dc.png)

Topic page banner icon
![screen shot 2018-04-18 at 10 24 05 am](https://user-images.githubusercontent.com/19477691/38938362-54837cea-42f3-11e8-87c2-4bc38007a4ef.png)

Service page social media icons
![screen shot 2018-04-18 at 10 26 11 am](https://user-images.githubusercontent.com/19477691/38938412-734bb3c2-42f3-11e8-86ea-718222ab34e2.png)

Footer
![screen shot 2018-04-18 at 10 29 45 am](https://user-images.githubusercontent.com/19477691/38938422-789b954a-42f3-11e8-84fe-7f0b15db067a.png)

Parks location page
![screen shot 2018-04-18 at 10 26 42 am](https://user-images.githubusercontent.com/19477691/38938448-8807d110-42f3-11e8-99dd-6b5d6bd34f99.png)

2018-04-18 15:15 UTC, mrossi113 approved these changes

2018-04-18 15:15 UTC, mrossi113 commented
LGTM after the fix for mayflower artifacts!

2018-04-18 15:16 UTC, merged