DP-8897  relationship indicators to expose organizations on public pages
massgov/mayflower-patternlab pull request #838
Opened 2018-05-16 15:41 UTC by clair0917

## Description
Adds relationship indicators pattern and updates org page with pattern for review

## Related Issue / Ticket

- [DP-8897](https://jira.state.ma.us/browse/DP-8897)

## Steps to Test

1.  The pattern can be viewed here: /?p=molecules-relationship-indicators
2. The pattern has also been added to the org page here: /?p=pages-organization

## Screenshots
<img width="1551" alt="screen shot 2018-05-16 at 10 39 36 am" src="https://user-images.githubusercontent.com/18662734/40127641-760dcc72-58f5-11e8-997c-d70b6b6f29df.png">

2018-05-16 20:10 UTC, isaacchansky requested changes
Just two small questions, overall looks solid

2018-05-16 20:10 UTC, isaacchansky commented on styleguide/source/_patterns/02-molecules/relationship-indicators.twig
> +  <div class="ma__relationship-indicators--section offered-by">
Should we check that offered-by is non-empty, since we check for relatedTo?

2018-05-16 20:10 UTC, isaacchansky commented on styleguide/source/assets/js/modules/headerTags.js
> +      $button.toggle();
I'm assuming this toggles _off_ the button, should we pass a boolean here?

2018-05-18 14:34 UTC, clair0917 commented on styleguide/source/_patterns/02-molecules/relationship-indicators.twig
> +  <div class="ma__relationship-indicators--section offered-by">
The offered by will always have at least one tag. The related too will be optional.

2018-05-18 14:34 UTC, clair0917 commented on styleguide/source/assets/js/modules/headerTags.js
> +      $button.toggle();
This actually toggles the button _on_. It's hidden by default and only toggles when more than one tag is present.

2018-05-18 14:57 UTC, isaacchansky commented on styleguide/source/_patterns/02-molecules/relationship-indicators.md
> +  offeredBy: [{
I'd document the required min-length of 1 here

2018-05-18 14:57 UTC, isaacchansky commented on styleguide/source/_patterns/02-molecules/relationship-indicators.md
> +   relatedTo: [{
document that the relatedTo array itself is optional

2018-05-18 14:58 UTC, isaacchansky commented on styleguide/source/_patterns/02-molecules/relationship-indicators.twig
> +  <div class="ma__relationship-indicators--section offered-by">
Gotcha, added a comment about this in the MD file

2018-05-22 02:14 UTC, isaacchansky approved these changes
This looks good to me once we update the assumed usage in the readme (i.e related-to is optional, offered-by is 1+)

2018-05-29 17:23 UTC, clair0917 commented
Dev has been updated a few times since this ticket was started and the backstop files are incredibly conflicted. Closing this PR in favor if https://github.com/massgov/mayflower/pull/853 from a clean branch

2018-05-29 17:23 UTC, closed without merging