DP-9017  image placement on guide pages using focal point
massgov/mayflower-patternlab pull request #850
Opened 2018-05-24 17:09 UTC by clair0917

Adds a variant for the focal point update to the illustrated header, including adding optional retina display image

## Description
Adds image-centered variant for illustrated header
update illustrated header template for optional retina display image

## Related Issue / Ticket

- [DP-9017](https://jira.mass.gov/browse/DP-9017)

## Steps to Test

1. The image centered variant can be visited at /?p=organisms-illustrated-header-image-centered
2. View that page on a retina and non retina screen to see the placeholder image change 

## Screenshots
On retina:
<img width="1671" alt="screen shot 2018-05-24 at 12 01 39 pm" src="https://user-images.githubusercontent.com/18662734/40500732-4a8e362a-5f4b-11e8-8a9c-f6c6580697e6.png">

On standard:
![screen shot 2018-05-24 at 12 01 52 pm](https://user-images.githubusercontent.com/18662734/40500739-5386c774-5f4b-11e8-99fe-1d215efc7abc.png)

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

#### Today I learned...

2018-05-31 15:44 UTC, tnathanjames approved these changes

2018-05-31 20:10 UTC, tnathanjames requested changes

2018-05-31 20:10 UTC, tnathanjames commented on styleguide/source/_patterns/03-organisms/by-template/illustrated-header.twig
> +      {% endif %};
@clair0917 While integrating this in Drupal, I noticed this stray semicolon.

2018-06-20 13:19 UTC, tnathanjames commented on styleguide/source/_patterns/03-organisms/by-template/illustrated-header.twig
> +<section class="{{illustratedHeaderClass}} {% if illustratedHeader.bgCentered %}{{ image-centered }}{% endif %}">
Is this: `{% if illustratedHeader.bgCentered %}{{ image-centered }}{% endif %}` necessary?  I don't see where the variable 'image-centered' is set and the centered class is being added above.

2018-06-20 14:06 UTC, clair0917 commented on styleguide/source/_patterns/03-organisms/by-template/illustrated-header.twig
> +<section class="{{illustratedHeaderClass}} {% if illustratedHeader.bgCentered %}{{ image-centered }}{% endif %}">
When we discussed the addition, we decided to use a class to target only the images that had been touched by the focal point module. 
I'll dig up my notes from the call, they couldn't have gone far...

2018-06-20 14:38 UTC, tnathanjames approved these changes

2018-06-20 14:58 UTC, merged